// Copyright 2019 Yunion
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deploy.proto

package apis

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GuestDesc struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Nics                 []*Nic   `protobuf:"bytes,4,rep,name=nics,proto3" json:"nics,omitempty"`
	NicsStandby          []*Nic   `protobuf:"bytes,5,rep,name=nics_standby,json=nicsStandby,proto3" json:"nics_standby,omitempty"`
	Disks                []*Disk  `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestDesc) Reset()         { *m = GuestDesc{} }
func (m *GuestDesc) String() string { return proto.CompactTextString(m) }
func (*GuestDesc) ProtoMessage()    {}
func (*GuestDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{0}
}

func (m *GuestDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestDesc.Unmarshal(m, b)
}
func (m *GuestDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestDesc.Marshal(b, m, deterministic)
}
func (m *GuestDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestDesc.Merge(m, src)
}
func (m *GuestDesc) XXX_Size() int {
	return xxx_messageInfo_GuestDesc.Size(m)
}
func (m *GuestDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestDesc.DiscardUnknown(m)
}

var xxx_messageInfo_GuestDesc proto.InternalMessageInfo

func (m *GuestDesc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GuestDesc) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GuestDesc) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *GuestDesc) GetNics() []*Nic {
	if m != nil {
		return m.Nics
	}
	return nil
}

func (m *GuestDesc) GetNicsStandby() []*Nic {
	if m != nil {
		return m.NicsStandby
	}
	return nil
}

func (m *GuestDesc) GetDisks() []*Disk {
	if m != nil {
		return m.Disks
	}
	return nil
}

type Disk struct {
	DiskId               string   `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	Driver               string   `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	CacheMode            string   `protobuf:"bytes,3,opt,name=cache_mode,json=cacheMode,proto3" json:"cache_mode,omitempty"`
	AioMode              string   `protobuf:"bytes,4,opt,name=aio_mode,json=aioMode,proto3" json:"aio_mode,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	TemplateId           string   `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ImagePath            string   `protobuf:"bytes,7,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	StorageId            string   `protobuf:"bytes,8,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Migrating            bool     `protobuf:"varint,9,opt,name=migrating,proto3" json:"migrating,omitempty"`
	TargetStorageId      string   `protobuf:"bytes,10,opt,name=target_storage_id,json=targetStorageId,proto3" json:"target_storage_id,omitempty"`
	Path                 string   `protobuf:"bytes,11,opt,name=path,proto3" json:"path,omitempty"`
	Format               string   `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty"`
	Index                int32    `protobuf:"varint,13,opt,name=index,proto3" json:"index,omitempty"`
	MergeSnapshot        bool     `protobuf:"varint,14,opt,name=merge_snapshot,json=mergeSnapshot,proto3" json:"merge_snapshot,omitempty"`
	Fs                   string   `protobuf:"bytes,15,opt,name=fs,proto3" json:"fs,omitempty"`
	Mountpoint           string   `protobuf:"bytes,16,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Dev                  string   `protobuf:"bytes,17,opt,name=dev,proto3" json:"dev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disk) Reset()         { *m = Disk{} }
func (m *Disk) String() string { return proto.CompactTextString(m) }
func (*Disk) ProtoMessage()    {}
func (*Disk) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{1}
}

func (m *Disk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disk.Unmarshal(m, b)
}
func (m *Disk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disk.Marshal(b, m, deterministic)
}
func (m *Disk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disk.Merge(m, src)
}
func (m *Disk) XXX_Size() int {
	return xxx_messageInfo_Disk.Size(m)
}
func (m *Disk) XXX_DiscardUnknown() {
	xxx_messageInfo_Disk.DiscardUnknown(m)
}

var xxx_messageInfo_Disk proto.InternalMessageInfo

func (m *Disk) GetDiskId() string {
	if m != nil {
		return m.DiskId
	}
	return ""
}

func (m *Disk) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Disk) GetCacheMode() string {
	if m != nil {
		return m.CacheMode
	}
	return ""
}

func (m *Disk) GetAioMode() string {
	if m != nil {
		return m.AioMode
	}
	return ""
}

func (m *Disk) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Disk) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *Disk) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Disk) GetStorageId() string {
	if m != nil {
		return m.StorageId
	}
	return ""
}

func (m *Disk) GetMigrating() bool {
	if m != nil {
		return m.Migrating
	}
	return false
}

func (m *Disk) GetTargetStorageId() string {
	if m != nil {
		return m.TargetStorageId
	}
	return ""
}

func (m *Disk) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Disk) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Disk) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Disk) GetMergeSnapshot() bool {
	if m != nil {
		return m.MergeSnapshot
	}
	return false
}

func (m *Disk) GetFs() string {
	if m != nil {
		return m.Fs
	}
	return ""
}

func (m *Disk) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

func (m *Disk) GetDev() string {
	if m != nil {
		return m.Dev
	}
	return ""
}

type Nic struct {
	Mac                  string    `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip                   string    `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Net                  string    `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	NetId                string    `protobuf:"bytes,4,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	Virtual              bool      `protobuf:"varint,5,opt,name=virtual,proto3" json:"virtual,omitempty"`
	Gateway              string    `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns                  string    `protobuf:"bytes,7,opt,name=dns,proto3" json:"dns,omitempty"`
	Domain               string    `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	Routes               []*Routes `protobuf:"bytes,9,rep,name=routes,proto3" json:"routes,omitempty"`
	Ifname               string    `protobuf:"bytes,10,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Masklen              int32     `protobuf:"varint,11,opt,name=masklen,proto3" json:"masklen,omitempty"`
	Driver               string    `protobuf:"bytes,12,opt,name=driver,proto3" json:"driver,omitempty"`
	Bridge               string    `protobuf:"bytes,13,opt,name=bridge,proto3" json:"bridge,omitempty"`
	WireId               string    `protobuf:"bytes,14,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	Vlan                 int32     `protobuf:"varint,15,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Interface            string    `protobuf:"bytes,16,opt,name=interface,proto3" json:"interface,omitempty"`
	Bw                   int32     `protobuf:"varint,17,opt,name=bw,proto3" json:"bw,omitempty"`
	Index                int32     `protobuf:"varint,18,opt,name=index,proto3" json:"index,omitempty"`
	VirtualIps           []string  `protobuf:"bytes,19,rep,name=virtual_ips,json=virtualIps,proto3" json:"virtual_ips,omitempty"`
	ExternelId           string    `protobuf:"bytes,20,opt,name=externel_id,json=externelId,proto3" json:"externel_id,omitempty"`
	TeamWith             string    `protobuf:"bytes,21,opt,name=team_with,json=teamWith,proto3" json:"team_with,omitempty"`
	Manual               bool      `protobuf:"varint,22,opt,name=manual,proto3" json:"manual,omitempty"`
	NicType              string    `protobuf:"bytes,23,opt,name=nic_type,json=nicType,proto3" json:"nic_type,omitempty"`
	LinkUp               bool      `protobuf:"varint,24,opt,name=link_up,json=linkUp,proto3" json:"link_up,omitempty"`
	Mtu                  int64     `protobuf:"varint,25,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Name                 string    `protobuf:"bytes,26,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Nic) Reset()         { *m = Nic{} }
func (m *Nic) String() string { return proto.CompactTextString(m) }
func (*Nic) ProtoMessage()    {}
func (*Nic) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{2}
}

func (m *Nic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nic.Unmarshal(m, b)
}
func (m *Nic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nic.Marshal(b, m, deterministic)
}
func (m *Nic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nic.Merge(m, src)
}
func (m *Nic) XXX_Size() int {
	return xxx_messageInfo_Nic.Size(m)
}
func (m *Nic) XXX_DiscardUnknown() {
	xxx_messageInfo_Nic.DiscardUnknown(m)
}

var xxx_messageInfo_Nic proto.InternalMessageInfo

func (m *Nic) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Nic) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Nic) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *Nic) GetNetId() string {
	if m != nil {
		return m.NetId
	}
	return ""
}

func (m *Nic) GetVirtual() bool {
	if m != nil {
		return m.Virtual
	}
	return false
}

func (m *Nic) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Nic) GetDns() string {
	if m != nil {
		return m.Dns
	}
	return ""
}

func (m *Nic) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Nic) GetRoutes() []*Routes {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *Nic) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

func (m *Nic) GetMasklen() int32 {
	if m != nil {
		return m.Masklen
	}
	return 0
}

func (m *Nic) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Nic) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

func (m *Nic) GetWireId() string {
	if m != nil {
		return m.WireId
	}
	return ""
}

func (m *Nic) GetVlan() int32 {
	if m != nil {
		return m.Vlan
	}
	return 0
}

func (m *Nic) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *Nic) GetBw() int32 {
	if m != nil {
		return m.Bw
	}
	return 0
}

func (m *Nic) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Nic) GetVirtualIps() []string {
	if m != nil {
		return m.VirtualIps
	}
	return nil
}

func (m *Nic) GetExternelId() string {
	if m != nil {
		return m.ExternelId
	}
	return ""
}

func (m *Nic) GetTeamWith() string {
	if m != nil {
		return m.TeamWith
	}
	return ""
}

func (m *Nic) GetManual() bool {
	if m != nil {
		return m.Manual
	}
	return false
}

func (m *Nic) GetNicType() string {
	if m != nil {
		return m.NicType
	}
	return ""
}

func (m *Nic) GetLinkUp() bool {
	if m != nil {
		return m.LinkUp
	}
	return false
}

func (m *Nic) GetMtu() int64 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *Nic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Routes struct {
	Route                []string `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Routes) Reset()         { *m = Routes{} }
func (m *Routes) String() string { return proto.CompactTextString(m) }
func (*Routes) ProtoMessage()    {}
func (*Routes) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{3}
}

func (m *Routes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Routes.Unmarshal(m, b)
}
func (m *Routes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Routes.Marshal(b, m, deterministic)
}
func (m *Routes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Routes.Merge(m, src)
}
func (m *Routes) XXX_Size() int {
	return xxx_messageInfo_Routes.Size(m)
}
func (m *Routes) XXX_DiscardUnknown() {
	xxx_messageInfo_Routes.DiscardUnknown(m)
}

var xxx_messageInfo_Routes proto.InternalMessageInfo

func (m *Routes) GetRoute() []string {
	if m != nil {
		return m.Route
	}
	return nil
}

type DeployInfo struct {
	PublicKey               *SSHKeys         `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Deploys                 []*DeployContent `protobuf:"bytes,2,rep,name=deploys,proto3" json:"deploys,omitempty"`
	Password                string           `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	IsInit                  bool             `protobuf:"varint,4,opt,name=is_init,json=isInit,proto3" json:"is_init,omitempty"`
	EnableTty               bool             `protobuf:"varint,5,opt,name=enable_tty,json=enableTty,proto3" json:"enable_tty,omitempty"`
	DefaultRootUser         bool             `protobuf:"varint,6,opt,name=default_root_user,json=defaultRootUser,proto3" json:"default_root_user,omitempty"`
	WindowsDefaultAdminUser bool             `protobuf:"varint,7,opt,name=windows_default_admin_user,json=windowsDefaultAdminUser,proto3" json:"windows_default_admin_user,omitempty"`
	EnableCloudInit         bool             `protobuf:"varint,8,opt,name=enable_cloud_init,json=enableCloudInit,proto3" json:"enable_cloud_init,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{4}
}

func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (m *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(m, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetPublicKey() *SSHKeys {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *DeployInfo) GetDeploys() []*DeployContent {
	if m != nil {
		return m.Deploys
	}
	return nil
}

func (m *DeployInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DeployInfo) GetIsInit() bool {
	if m != nil {
		return m.IsInit
	}
	return false
}

func (m *DeployInfo) GetEnableTty() bool {
	if m != nil {
		return m.EnableTty
	}
	return false
}

func (m *DeployInfo) GetDefaultRootUser() bool {
	if m != nil {
		return m.DefaultRootUser
	}
	return false
}

func (m *DeployInfo) GetWindowsDefaultAdminUser() bool {
	if m != nil {
		return m.WindowsDefaultAdminUser
	}
	return false
}

func (m *DeployInfo) GetEnableCloudInit() bool {
	if m != nil {
		return m.EnableCloudInit
	}
	return false
}

type SSHKeys struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	DeletePublicKey      string   `protobuf:"bytes,2,opt,name=delete_public_key,json=deletePublicKey,proto3" json:"delete_public_key,omitempty"`
	AdminPublicKey       string   `protobuf:"bytes,3,opt,name=admin_public_key,json=adminPublicKey,proto3" json:"admin_public_key,omitempty"`
	ProjectPublicKey     string   `protobuf:"bytes,4,opt,name=project_public_key,json=projectPublicKey,proto3" json:"project_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSHKeys) Reset()         { *m = SSHKeys{} }
func (m *SSHKeys) String() string { return proto.CompactTextString(m) }
func (*SSHKeys) ProtoMessage()    {}
func (*SSHKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{5}
}

func (m *SSHKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSHKeys.Unmarshal(m, b)
}
func (m *SSHKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSHKeys.Marshal(b, m, deterministic)
}
func (m *SSHKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSHKeys.Merge(m, src)
}
func (m *SSHKeys) XXX_Size() int {
	return xxx_messageInfo_SSHKeys.Size(m)
}
func (m *SSHKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_SSHKeys.DiscardUnknown(m)
}

var xxx_messageInfo_SSHKeys proto.InternalMessageInfo

func (m *SSHKeys) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SSHKeys) GetDeletePublicKey() string {
	if m != nil {
		return m.DeletePublicKey
	}
	return ""
}

func (m *SSHKeys) GetAdminPublicKey() string {
	if m != nil {
		return m.AdminPublicKey
	}
	return ""
}

func (m *SSHKeys) GetProjectPublicKey() string {
	if m != nil {
		return m.ProjectPublicKey
	}
	return ""
}

type DeployContent struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployContent) Reset()         { *m = DeployContent{} }
func (m *DeployContent) String() string { return proto.CompactTextString(m) }
func (*DeployContent) ProtoMessage()    {}
func (*DeployContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{6}
}

func (m *DeployContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployContent.Unmarshal(m, b)
}
func (m *DeployContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployContent.Marshal(b, m, deterministic)
}
func (m *DeployContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployContent.Merge(m, src)
}
func (m *DeployContent) XXX_Size() int {
	return xxx_messageInfo_DeployContent.Size(m)
}
func (m *DeployContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployContent.DiscardUnknown(m)
}

var xxx_messageInfo_DeployContent proto.InternalMessageInfo

func (m *DeployContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DeployContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DeployContent) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DeployGuestFsResponse struct {
	Distro               string   `protobuf:"bytes,1,opt,name=distro,proto3" json:"distro,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Os                   string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Account              string   `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	Key                  string   `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployGuestFsResponse) Reset()         { *m = DeployGuestFsResponse{} }
func (m *DeployGuestFsResponse) String() string { return proto.CompactTextString(m) }
func (*DeployGuestFsResponse) ProtoMessage()    {}
func (*DeployGuestFsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{8}
}

func (m *DeployGuestFsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployGuestFsResponse.Unmarshal(m, b)
}
func (m *DeployGuestFsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployGuestFsResponse.Marshal(b, m, deterministic)
}
func (m *DeployGuestFsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployGuestFsResponse.Merge(m, src)
}
func (m *DeployGuestFsResponse) XXX_Size() int {
	return xxx_messageInfo_DeployGuestFsResponse.Size(m)
}
func (m *DeployGuestFsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployGuestFsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployGuestFsResponse proto.InternalMessageInfo

func (m *DeployGuestFsResponse) GetDistro() string {
	if m != nil {
		return m.Distro
	}
	return ""
}

func (m *DeployGuestFsResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeployGuestFsResponse) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *DeployGuestFsResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DeployGuestFsResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *DeployGuestFsResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DeployGuestFsResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeployParams struct {
	DiskPath             string      `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	GuestDesc            *GuestDesc  `protobuf:"bytes,2,opt,name=guest_desc,json=guestDesc,proto3" json:"guest_desc,omitempty"`
	DeployInfo           *DeployInfo `protobuf:"bytes,3,opt,name=deploy_info,json=deployInfo,proto3" json:"deploy_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeployParams) Reset()         { *m = DeployParams{} }
func (m *DeployParams) String() string { return proto.CompactTextString(m) }
func (*DeployParams) ProtoMessage()    {}
func (*DeployParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{9}
}

func (m *DeployParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployParams.Unmarshal(m, b)
}
func (m *DeployParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployParams.Marshal(b, m, deterministic)
}
func (m *DeployParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployParams.Merge(m, src)
}
func (m *DeployParams) XXX_Size() int {
	return xxx_messageInfo_DeployParams.Size(m)
}
func (m *DeployParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeployParams proto.InternalMessageInfo

func (m *DeployParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *DeployParams) GetGuestDesc() *GuestDesc {
	if m != nil {
		return m.GuestDesc
	}
	return nil
}

func (m *DeployParams) GetDeployInfo() *DeployInfo {
	if m != nil {
		return m.DeployInfo
	}
	return nil
}

type ResizeFsParams struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResizeFsParams) Reset()         { *m = ResizeFsParams{} }
func (m *ResizeFsParams) String() string { return proto.CompactTextString(m) }
func (*ResizeFsParams) ProtoMessage()    {}
func (*ResizeFsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{10}
}

func (m *ResizeFsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResizeFsParams.Unmarshal(m, b)
}
func (m *ResizeFsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResizeFsParams.Marshal(b, m, deterministic)
}
func (m *ResizeFsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResizeFsParams.Merge(m, src)
}
func (m *ResizeFsParams) XXX_Size() int {
	return xxx_messageInfo_ResizeFsParams.Size(m)
}
func (m *ResizeFsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ResizeFsParams.DiscardUnknown(m)
}

var xxx_messageInfo_ResizeFsParams proto.InternalMessageInfo

func (m *ResizeFsParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

type FormatFsParams struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	FsFormat             string   `protobuf:"bytes,2,opt,name=fs_format,json=fsFormat,proto3" json:"fs_format,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormatFsParams) Reset()         { *m = FormatFsParams{} }
func (m *FormatFsParams) String() string { return proto.CompactTextString(m) }
func (*FormatFsParams) ProtoMessage()    {}
func (*FormatFsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{11}
}

func (m *FormatFsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatFsParams.Unmarshal(m, b)
}
func (m *FormatFsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatFsParams.Marshal(b, m, deterministic)
}
func (m *FormatFsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatFsParams.Merge(m, src)
}
func (m *FormatFsParams) XXX_Size() int {
	return xxx_messageInfo_FormatFsParams.Size(m)
}
func (m *FormatFsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatFsParams.DiscardUnknown(m)
}

var xxx_messageInfo_FormatFsParams proto.InternalMessageInfo

func (m *FormatFsParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *FormatFsParams) GetFsFormat() string {
	if m != nil {
		return m.FsFormat
	}
	return ""
}

func (m *FormatFsParams) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ReleaseInfo struct {
	Distro               string   `protobuf:"bytes,1,opt,name=distro,proto3" json:"distro,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseInfo) Reset()         { *m = ReleaseInfo{} }
func (m *ReleaseInfo) String() string { return proto.CompactTextString(m) }
func (*ReleaseInfo) ProtoMessage()    {}
func (*ReleaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{12}
}

func (m *ReleaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseInfo.Unmarshal(m, b)
}
func (m *ReleaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseInfo.Marshal(b, m, deterministic)
}
func (m *ReleaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseInfo.Merge(m, src)
}
func (m *ReleaseInfo) XXX_Size() int {
	return xxx_messageInfo_ReleaseInfo.Size(m)
}
func (m *ReleaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseInfo proto.InternalMessageInfo

func (m *ReleaseInfo) GetDistro() string {
	if m != nil {
		return m.Distro
	}
	return ""
}

func (m *ReleaseInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReleaseInfo) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *ReleaseInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type SaveToGlanceParams struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	Compress             bool     `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveToGlanceParams) Reset()         { *m = SaveToGlanceParams{} }
func (m *SaveToGlanceParams) String() string { return proto.CompactTextString(m) }
func (*SaveToGlanceParams) ProtoMessage()    {}
func (*SaveToGlanceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{13}
}

func (m *SaveToGlanceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveToGlanceParams.Unmarshal(m, b)
}
func (m *SaveToGlanceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveToGlanceParams.Marshal(b, m, deterministic)
}
func (m *SaveToGlanceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveToGlanceParams.Merge(m, src)
}
func (m *SaveToGlanceParams) XXX_Size() int {
	return xxx_messageInfo_SaveToGlanceParams.Size(m)
}
func (m *SaveToGlanceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveToGlanceParams.DiscardUnknown(m)
}

var xxx_messageInfo_SaveToGlanceParams proto.InternalMessageInfo

func (m *SaveToGlanceParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *SaveToGlanceParams) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

type SaveToGlanceResponse struct {
	OsInfo               string       `protobuf:"bytes,1,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	ReleaseInfo          *ReleaseInfo `protobuf:"bytes,2,opt,name=release_info,json=releaseInfo,proto3" json:"release_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SaveToGlanceResponse) Reset()         { *m = SaveToGlanceResponse{} }
func (m *SaveToGlanceResponse) String() string { return proto.CompactTextString(m) }
func (*SaveToGlanceResponse) ProtoMessage()    {}
func (*SaveToGlanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{14}
}

func (m *SaveToGlanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveToGlanceResponse.Unmarshal(m, b)
}
func (m *SaveToGlanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveToGlanceResponse.Marshal(b, m, deterministic)
}
func (m *SaveToGlanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveToGlanceResponse.Merge(m, src)
}
func (m *SaveToGlanceResponse) XXX_Size() int {
	return xxx_messageInfo_SaveToGlanceResponse.Size(m)
}
func (m *SaveToGlanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveToGlanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveToGlanceResponse proto.InternalMessageInfo

func (m *SaveToGlanceResponse) GetOsInfo() string {
	if m != nil {
		return m.OsInfo
	}
	return ""
}

func (m *SaveToGlanceResponse) GetReleaseInfo() *ReleaseInfo {
	if m != nil {
		return m.ReleaseInfo
	}
	return nil
}

type ProbeImageInfoPramas struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeImageInfoPramas) Reset()         { *m = ProbeImageInfoPramas{} }
func (m *ProbeImageInfoPramas) String() string { return proto.CompactTextString(m) }
func (*ProbeImageInfoPramas) ProtoMessage()    {}
func (*ProbeImageInfoPramas) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{15}
}

func (m *ProbeImageInfoPramas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeImageInfoPramas.Unmarshal(m, b)
}
func (m *ProbeImageInfoPramas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeImageInfoPramas.Marshal(b, m, deterministic)
}
func (m *ProbeImageInfoPramas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeImageInfoPramas.Merge(m, src)
}
func (m *ProbeImageInfoPramas) XXX_Size() int {
	return xxx_messageInfo_ProbeImageInfoPramas.Size(m)
}
func (m *ProbeImageInfoPramas) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeImageInfoPramas.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeImageInfoPramas proto.InternalMessageInfo

func (m *ProbeImageInfoPramas) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

type ImageInfo struct {
	OsInfo                *ReleaseInfo `protobuf:"bytes,1,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	OsType                string       `protobuf:"bytes,2,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	IsUefiSupport         bool         `protobuf:"varint,3,opt,name=is_uefi_support,json=isUefiSupport,proto3" json:"is_uefi_support,omitempty"`
	IsLvmPartition        bool         `protobuf:"varint,4,opt,name=is_lvm_partition,json=isLvmPartition,proto3" json:"is_lvm_partition,omitempty"`
	IsReadonly            bool         `protobuf:"varint,5,opt,name=is_readonly,json=isReadonly,proto3" json:"is_readonly,omitempty"`
	PhysicalPartitionType string       `protobuf:"bytes,6,opt,name=physical_partition_type,json=physicalPartitionType,proto3" json:"physical_partition_type,omitempty"`
	IsInstalledCloudInit  bool         `protobuf:"varint,7,opt,name=is_installed_cloud_init,json=isInstalledCloudInit,proto3" json:"is_installed_cloud_init,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *ImageInfo) Reset()         { *m = ImageInfo{} }
func (m *ImageInfo) String() string { return proto.CompactTextString(m) }
func (*ImageInfo) ProtoMessage()    {}
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{16}
}

func (m *ImageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageInfo.Unmarshal(m, b)
}
func (m *ImageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageInfo.Marshal(b, m, deterministic)
}
func (m *ImageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageInfo.Merge(m, src)
}
func (m *ImageInfo) XXX_Size() int {
	return xxx_messageInfo_ImageInfo.Size(m)
}
func (m *ImageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImageInfo proto.InternalMessageInfo

func (m *ImageInfo) GetOsInfo() *ReleaseInfo {
	if m != nil {
		return m.OsInfo
	}
	return nil
}

func (m *ImageInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *ImageInfo) GetIsUefiSupport() bool {
	if m != nil {
		return m.IsUefiSupport
	}
	return false
}

func (m *ImageInfo) GetIsLvmPartition() bool {
	if m != nil {
		return m.IsLvmPartition
	}
	return false
}

func (m *ImageInfo) GetIsReadonly() bool {
	if m != nil {
		return m.IsReadonly
	}
	return false
}

func (m *ImageInfo) GetPhysicalPartitionType() string {
	if m != nil {
		return m.PhysicalPartitionType
	}
	return ""
}

func (m *ImageInfo) GetIsInstalledCloudInit() bool {
	if m != nil {
		return m.IsInstalledCloudInit
	}
	return false
}

func init() {
	proto.RegisterType((*GuestDesc)(nil), "apis.GuestDesc")
	proto.RegisterType((*Disk)(nil), "apis.Disk")
	proto.RegisterType((*Nic)(nil), "apis.Nic")
	proto.RegisterType((*Routes)(nil), "apis.Routes")
	proto.RegisterType((*DeployInfo)(nil), "apis.DeployInfo")
	proto.RegisterType((*SSHKeys)(nil), "apis.SSHKeys")
	proto.RegisterType((*DeployContent)(nil), "apis.DeployContent")
	proto.RegisterType((*Empty)(nil), "apis.Empty")
	proto.RegisterType((*DeployGuestFsResponse)(nil), "apis.DeployGuestFsResponse")
	proto.RegisterType((*DeployParams)(nil), "apis.DeployParams")
	proto.RegisterType((*ResizeFsParams)(nil), "apis.ResizeFsParams")
	proto.RegisterType((*FormatFsParams)(nil), "apis.FormatFsParams")
	proto.RegisterType((*ReleaseInfo)(nil), "apis.ReleaseInfo")
	proto.RegisterType((*SaveToGlanceParams)(nil), "apis.SaveToGlanceParams")
	proto.RegisterType((*SaveToGlanceResponse)(nil), "apis.SaveToGlanceResponse")
	proto.RegisterType((*ProbeImageInfoPramas)(nil), "apis.ProbeImageInfoPramas")
	proto.RegisterType((*ImageInfo)(nil), "apis.ImageInfo")
}

func init() { proto.RegisterFile("deploy.proto", fileDescriptor_05f09e103004e384) }

var fileDescriptor_05f09e103004e384 = []byte{
	// 1535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5f, 0x6f, 0x23, 0xb7,
	0x11, 0x87, 0x64, 0xfd, 0x59, 0x8d, 0x64, 0xd9, 0xc7, 0xf8, 0xce, 0x1b, 0xa5, 0x49, 0x8c, 0x45,
	0x5b, 0x18, 0x87, 0xbb, 0x03, 0xea, 0xb4, 0x7d, 0x29, 0x0a, 0x34, 0x88, 0x7b, 0xa9, 0x90, 0x26,
	0x30, 0xd6, 0x77, 0xe8, 0x5b, 0x17, 0xd4, 0x2e, 0x25, 0xb3, 0xde, 0x25, 0x17, 0x24, 0x65, 0x45,
	0xfd, 0x10, 0xfd, 0x24, 0x7d, 0x0a, 0xd0, 0x97, 0x7e, 0x8c, 0xbe, 0xf5, 0x9b, 0xf4, 0xb1, 0x98,
	0x21, 0x77, 0xb5, 0xbe, 0x1c, 0xd0, 0x7b, 0xe9, 0x93, 0x38, 0xbf, 0x19, 0x92, 0xc3, 0xf9, 0xf3,
	0x9b, 0x15, 0xcc, 0x0a, 0x51, 0x97, 0x7a, 0xff, 0xaa, 0x36, 0xda, 0x69, 0x36, 0xe0, 0xb5, 0xb4,
	0xc9, 0x3f, 0x7b, 0x30, 0xf9, 0x7a, 0x2b, 0xac, 0xbb, 0x16, 0x36, 0x67, 0x0c, 0x06, 0x8a, 0x57,
	0x22, 0xee, 0x5d, 0xf4, 0x2e, 0x27, 0x29, 0xad, 0x11, 0xdb, 0x6e, 0x65, 0x11, 0xf7, 0x3d, 0x86,
	0x6b, 0xf6, 0x0c, 0x46, 0x85, 0xae, 0xb8, 0x54, 0xf1, 0x11, 0xa1, 0x41, 0x62, 0x9f, 0xc2, 0x40,
	0xc9, 0xdc, 0xc6, 0x83, 0x8b, 0xa3, 0xcb, 0xe9, 0xd5, 0xe4, 0x15, 0x5e, 0xf1, 0xea, 0x3b, 0x99,
	0xa7, 0x04, 0xb3, 0x17, 0x30, 0xc3, 0xdf, 0xcc, 0x3a, 0xae, 0x8a, 0xd5, 0x3e, 0x1e, 0xbe, 0x6b,
	0x36, 0x45, 0xf5, 0xad, 0xd7, 0xb2, 0x0b, 0x18, 0x16, 0xd2, 0xde, 0xdb, 0x78, 0x44, 0x66, 0xe0,
	0xcd, 0xae, 0xa5, 0xbd, 0x4f, 0xbd, 0x22, 0xf9, 0xf7, 0x11, 0x0c, 0x50, 0x66, 0xe7, 0x30, 0x46,
	0x24, 0x93, 0x45, 0x70, 0x7d, 0x84, 0xe2, 0xd2, 0x3b, 0x6a, 0xe4, 0x83, 0x30, 0xc1, 0xfd, 0x20,
	0xb1, 0x4f, 0x01, 0x72, 0x9e, 0xdf, 0x89, 0xac, 0xd2, 0x85, 0x08, 0x8f, 0x98, 0x10, 0xf2, 0xad,
	0x2e, 0x04, 0xfb, 0x18, 0x22, 0x2e, 0xb5, 0x57, 0x0e, 0x48, 0x39, 0xe6, 0x52, 0x93, 0x8a, 0xc1,
	0xc0, 0xca, 0xbf, 0x8a, 0x78, 0x78, 0xd1, 0xbb, 0x3c, 0x4a, 0x69, 0xcd, 0x3e, 0x87, 0xa9, 0x13,
	0x55, 0x5d, 0x72, 0x27, 0xd0, 0x85, 0x11, 0xed, 0x80, 0x06, 0x5a, 0x16, 0x78, 0x9d, 0xac, 0xf8,
	0x46, 0x64, 0x35, 0x77, 0x77, 0xf1, 0xd8, 0x5f, 0x47, 0xc8, 0x0d, 0x77, 0x77, 0xa8, 0xb6, 0x4e,
	0x1b, 0x34, 0x90, 0x45, 0x1c, 0x79, 0x75, 0x40, 0x96, 0x05, 0xfb, 0x09, 0x4c, 0x2a, 0xb9, 0x31,
	0xdc, 0x49, 0xb5, 0x89, 0x27, 0x17, 0xbd, 0xcb, 0x28, 0x3d, 0x00, 0xec, 0x39, 0x3c, 0x71, 0xdc,
	0x6c, 0x84, 0xcb, 0x3a, 0x67, 0x00, 0x9d, 0x71, 0xe2, 0x15, 0xb7, 0xed, 0x49, 0x0c, 0x06, 0xe4,
	0xc1, 0xd4, 0xe7, 0x12, 0xd7, 0x18, 0xa2, 0xb5, 0x36, 0x15, 0x77, 0xf1, 0xcc, 0x87, 0xc8, 0x4b,
	0xec, 0x0c, 0x86, 0x52, 0x15, 0xe2, 0xfb, 0xf8, 0xf8, 0xa2, 0x77, 0x39, 0x4c, 0xbd, 0xc0, 0x7e,
	0x06, 0xf3, 0x4a, 0x98, 0x8d, 0xc8, 0xac, 0xe2, 0xb5, 0xbd, 0xd3, 0x2e, 0x9e, 0x93, 0x43, 0xc7,
	0x84, 0xde, 0x06, 0x90, 0xcd, 0xa1, 0xbf, 0xb6, 0xf1, 0x09, 0x1d, 0xd8, 0x5f, 0x5b, 0xf6, 0x19,
	0x40, 0xa5, 0xb7, 0xca, 0xd5, 0x5a, 0x2a, 0x17, 0x9f, 0xfa, 0x00, 0x1d, 0x10, 0x76, 0x0a, 0x47,
	0x85, 0x78, 0x88, 0x9f, 0x90, 0x02, 0x97, 0xc9, 0x7f, 0x06, 0x70, 0xf4, 0x9d, 0xcc, 0x51, 0x53,
	0xf1, 0x3c, 0xa4, 0x15, 0x97, 0x78, 0xb6, 0xac, 0x43, 0x3e, 0xfb, 0xb2, 0x46, 0x0b, 0x25, 0x5c,
	0x48, 0x22, 0x2e, 0xd9, 0x53, 0x18, 0x29, 0xe1, 0x30, 0x0e, 0x3e, 0x79, 0x43, 0x25, 0xdc, 0xb2,
	0x60, 0x31, 0x8c, 0x1f, 0xa4, 0x71, 0x5b, 0x5e, 0x52, 0xf6, 0xa2, 0xb4, 0x11, 0x51, 0xb3, 0xe1,
	0x4e, 0xec, 0xf8, 0x3e, 0x24, 0xaf, 0x11, 0xc9, 0x31, 0x65, 0x43, 0xca, 0x70, 0xd9, 0xa9, 0xfd,
	0xe8, 0x51, 0xed, 0xff, 0x14, 0x46, 0x46, 0x6f, 0x9d, 0xb0, 0xf1, 0x84, 0xea, 0x75, 0xe6, 0xeb,
	0x35, 0x25, 0x2c, 0x0d, 0x3a, 0xdc, 0x2d, 0xd7, 0xd4, 0x63, 0x3e, 0x45, 0x41, 0x42, 0x0f, 0x2a,
	0x6e, 0xef, 0x4b, 0xa1, 0x28, 0x39, 0xc3, 0xb4, 0x11, 0x3b, 0x25, 0x3c, 0x7b, 0x54, 0xc2, 0xcf,
	0x60, 0xb4, 0x32, 0xb2, 0xd8, 0x08, 0x4a, 0xd0, 0x24, 0x0d, 0x12, 0xf6, 0xc2, 0x4e, 0x1a, 0xaa,
	0x82, 0xb9, 0x57, 0xa0, 0xe8, 0x93, 0xff, 0x50, 0x72, 0x45, 0x59, 0x19, 0xa6, 0xb4, 0xc6, 0xd2,
	0x92, 0xca, 0x09, 0xb3, 0xe6, 0xb9, 0x08, 0x69, 0x39, 0x00, 0x18, 0xe9, 0xd5, 0x8e, 0x92, 0x32,
	0x4c, 0xfb, 0xab, 0xdd, 0xa1, 0x24, 0x58, 0xb7, 0x24, 0x3e, 0x87, 0x69, 0x88, 0x63, 0x26, 0x6b,
	0x1b, 0x7f, 0x74, 0x71, 0x84, 0xc9, 0x0d, 0xd0, 0xb2, 0xb6, 0x68, 0x20, 0xbe, 0x77, 0xc2, 0x28,
	0x51, 0xa2, 0x57, 0x67, 0x3e, 0xfb, 0x0d, 0xb4, 0x2c, 0xd8, 0x27, 0x30, 0x71, 0x82, 0x57, 0xd9,
	0x4e, 0xba, 0xbb, 0xf8, 0x29, 0xa9, 0x23, 0x04, 0xfe, 0x24, 0x7d, 0x7d, 0x56, 0x5c, 0x61, 0xd2,
	0x9e, 0x51, 0xd2, 0x82, 0x84, 0x3d, 0xaa, 0x64, 0x9e, 0xb9, 0x7d, 0x2d, 0xe2, 0x73, 0x9f, 0x34,
	0x25, 0xf3, 0x37, 0xfb, 0x9a, 0x42, 0x50, 0x4a, 0x75, 0x9f, 0x6d, 0xeb, 0x38, 0xf6, 0x7b, 0x50,
	0x7c, 0x4b, 0xa5, 0x52, 0xb9, 0x6d, 0xfc, 0x31, 0xf5, 0x2e, 0x2e, 0x5b, 0xc6, 0x5b, 0x1c, 0x18,
	0x2f, 0xf9, 0x0c, 0x46, 0x3e, 0x6b, 0xf8, 0x60, 0xca, 0x5b, 0xdc, 0xa3, 0x47, 0x79, 0x21, 0xf9,
	0x57, 0x1f, 0xe0, 0x9a, 0xa8, 0x74, 0xa9, 0xd6, 0x9a, 0xbd, 0x00, 0xa8, 0xb7, 0xab, 0x52, 0xe6,
	0xd9, 0xbd, 0xd8, 0x53, 0xa1, 0x4e, 0xaf, 0x8e, 0x7d, 0xf2, 0x6f, 0x6f, 0xff, 0xf0, 0x8d, 0xd8,
	0xdb, 0x74, 0xe2, 0x0d, 0xbe, 0x11, 0x7b, 0xf6, 0x12, 0xc6, 0x9e, 0x86, 0x6d, 0xdc, 0xa7, 0x3a,
	0xf9, 0x28, 0xf0, 0x1a, 0x81, 0x5f, 0x69, 0xe5, 0x84, 0x72, 0x69, 0x63, 0xc3, 0x16, 0x10, 0xd5,
	0xdc, 0xda, 0x9d, 0x36, 0x45, 0xa8, 0xf0, 0x56, 0xc6, 0x67, 0x4a, 0x9b, 0x49, 0x25, 0x1d, 0xd5,
	0x79, 0x94, 0x8e, 0xa4, 0x5d, 0x2a, 0xe9, 0x90, 0x4f, 0x84, 0xe2, 0xab, 0x52, 0x64, 0xce, 0xed,
	0x43, 0xad, 0x4f, 0x3c, 0xf2, 0xc6, 0xed, 0x91, 0x31, 0x0a, 0xb1, 0xe6, 0xdb, 0xd2, 0x65, 0x46,
	0x6b, 0x97, 0x6d, 0xad, 0x30, 0x54, 0xf7, 0x51, 0x7a, 0x12, 0x14, 0xa9, 0xd6, 0xee, 0xad, 0x15,
	0x86, 0xfd, 0x06, 0x16, 0x3b, 0xa9, 0x0a, 0xbd, 0xb3, 0x59, 0xb3, 0x87, 0x17, 0x95, 0x54, 0x7e,
	0xd3, 0x98, 0x36, 0x9d, 0x07, 0x8b, 0x6b, 0x6f, 0xf0, 0x25, 0xea, 0x69, 0xf3, 0x73, 0x78, 0x12,
	0xfc, 0xc8, 0x4b, 0xbd, 0x2d, 0xbc, 0xab, 0x91, 0xbf, 0xc8, 0x2b, 0xbe, 0x42, 0x1c, 0x7d, 0x4e,
	0xfe, 0xde, 0x83, 0x71, 0x08, 0x17, 0xfa, 0xff, 0x4e, 0x44, 0x27, 0xdd, 0x10, 0x92, 0xff, 0xa5,
	0x70, 0x22, 0xeb, 0x58, 0x79, 0x3e, 0x38, 0xf1, 0x8a, 0x9b, 0xd6, 0xf6, 0x12, 0x4e, 0xbd, 0xbf,
	0x1d, 0x53, 0x1f, 0xc7, 0x39, 0xe1, 0x07, 0xcb, 0x17, 0xc0, 0x6a, 0xa3, 0xff, 0x22, 0x72, 0xd7,
	0xb5, 0xf5, 0x04, 0x72, 0x1a, 0x34, 0xad, 0x75, 0xf2, 0x16, 0x8e, 0x1f, 0x65, 0xac, 0xa5, 0xd6,
	0x5e, 0x87, 0x5a, 0x63, 0x18, 0xe7, 0x5e, 0x1d, 0xdc, 0x6b, 0x44, 0x2c, 0x6a, 0x9e, 0x3b, 0xa9,
	0xdb, 0x01, 0xea, 0xa5, 0x64, 0x0c, 0xc3, 0xdf, 0x57, 0xb5, 0xdb, 0x27, 0xff, 0xe8, 0xc1, 0x53,
	0x7f, 0x01, 0x4d, 0xe7, 0xd7, 0x36, 0x15, 0xb6, 0xd6, 0xca, 0x0a, 0xe2, 0x03, 0x69, 0x9d, 0xd1,
	0x9d, 0x51, 0xe7, 0x8c, 0x26, 0x76, 0x13, 0xc6, 0xe2, 0x99, 0xe1, 0xb2, 0x20, 0xa2, 0x6b, 0xdc,
	0xe4, 0x77, 0xe1, 0x2a, 0x5a, 0x63, 0x5d, 0x95, 0x5c, 0x6d, 0xb6, 0x7c, 0xd3, 0x4c, 0xb8, 0x56,
	0xc6, 0xb6, 0xd7, 0x96, 0xca, 0x66, 0x92, 0xf6, 0xb5, 0xc5, 0x93, 0x79, 0x9e, 0x23, 0x59, 0x37,
	0xec, 0x18, 0x44, 0xec, 0x27, 0x0c, 0x52, 0x60, 0xc7, 0x7b, 0xb1, 0x4f, 0xfe, 0xd6, 0x83, 0x99,
	0xf7, 0xfb, 0x86, 0x1b, 0x5e, 0x59, 0xec, 0x6d, 0x1a, 0xcd, 0x9d, 0xe0, 0x44, 0x08, 0xd0, 0xe0,
	0x7b, 0x05, 0xb0, 0xc1, 0xe7, 0x65, 0x85, 0xb0, 0x39, 0xb9, 0x3d, 0xbd, 0x3a, 0xf1, 0xfd, 0xd0,
	0x7e, 0x94, 0xa4, 0x93, 0x4d, 0xfb, 0x7d, 0xf2, 0x0b, 0x98, 0xfa, 0xc6, 0xc8, 0xa4, 0x5a, 0x6b,
	0x7a, 0xd0, 0xf4, 0xea, 0xb4, 0xdb, 0x40, 0xd8, 0x91, 0x29, 0x14, 0xed, 0x3a, 0x79, 0x09, 0xf3,
	0x54, 0xe0, 0x94, 0x7e, 0x6d, 0x3f, 0xc0, 0xa3, 0xe4, 0xcf, 0x30, 0x7f, 0x4d, 0xf3, 0xef, 0x83,
	0xcc, 0x51, 0xb9, 0xb6, 0x59, 0x98, 0x9f, 0x3e, 0xec, 0xd1, 0xda, 0xfa, 0x13, 0xda, 0x2f, 0xa7,
	0xa3, 0xc3, 0x97, 0x53, 0xa2, 0x61, 0x9a, 0x8a, 0x52, 0x70, 0x2b, 0x88, 0x3b, 0xfe, 0xef, 0xc9,
	0x4c, 0xbe, 0x05, 0x76, 0xcb, 0x1f, 0xc4, 0x1b, 0xfd, 0x75, 0xc9, 0x55, 0x2e, 0x3e, 0xe4, 0x51,
	0x0b, 0x88, 0x72, 0x5d, 0xd5, 0x46, 0x58, 0x4b, 0xb7, 0x47, 0x69, 0x2b, 0x27, 0x02, 0xce, 0xba,
	0xc7, 0xb5, 0x55, 0x79, 0x0e, 0x63, 0x6d, 0x7d, 0x56, 0xc2, 0x4b, 0xb4, 0xa5, 0x17, 0xfe, 0x12,
	0x66, 0xc6, 0x3f, 0xd8, 0x6b, 0x7d, 0x92, 0x9f, 0x84, 0xe1, 0x78, 0x08, 0x45, 0x3a, 0x35, 0x07,
	0x21, 0xf9, 0x02, 0xce, 0x6e, 0x8c, 0x5e, 0x89, 0x25, 0x7e, 0x23, 0x21, 0x72, 0x63, 0x78, 0xc5,
	0xff, 0x47, 0xee, 0x7e, 0xe8, 0xc3, 0xa4, 0xdd, 0xc0, 0x9e, 0x3f, 0xf6, 0xe8, 0xbd, 0x77, 0x36,
	0x4e, 0x7a, 0xef, 0x69, 0x94, 0xf4, 0x1b, 0xef, 0x69, 0x92, 0xfc, 0x1c, 0x4e, 0xa4, 0xcd, 0xb6,
	0x62, 0x2d, 0x33, 0xbb, 0xad, 0x6b, 0x6d, 0xfc, 0x77, 0x46, 0x94, 0x1e, 0x4b, 0xfb, 0x56, 0xac,
	0xe5, 0xad, 0x07, 0x91, 0x66, 0xa4, 0xcd, 0xca, 0x87, 0x2a, 0xab, 0xb9, 0x71, 0x92, 0x3a, 0xdb,
	0x73, 0xf2, 0x5c, 0xda, 0x3f, 0x3e, 0x54, 0x37, 0x0d, 0x8a, 0xc3, 0x50, 0xda, 0xcc, 0x08, 0x5e,
	0x68, 0x55, 0x36, 0xe4, 0x0c, 0xd2, 0xa6, 0x01, 0x61, 0xbf, 0x86, 0xf3, 0xfa, 0x6e, 0x6f, 0x65,
	0xce, 0xcb, 0xc3, 0x61, 0xde, 0x37, 0xdf, 0x7d, 0x4f, 0x1b, 0x75, 0x7b, 0x28, 0xb9, 0xfa, 0x2b,
	0x38, 0xa7, 0x69, 0x60, 0x1d, 0x2f, 0x4b, 0x51, 0x74, 0x29, 0xd7, 0xd3, 0xf4, 0x19, 0x4e, 0x87,
	0xa0, 0x6d, 0x79, 0xf7, 0xea, 0x87, 0x3e, 0x4c, 0x7d, 0xeb, 0x7c, 0xb9, 0x41, 0x66, 0xfa, 0x5d,
	0x43, 0x6c, 0x81, 0x77, 0x18, 0xeb, 0xb6, 0x97, 0x2f, 0x9f, 0xc5, 0x27, 0x5d, 0xec, 0x5d, 0x82,
	0x7a, 0x09, 0x51, 0xd3, 0x71, 0xec, 0xac, 0x89, 0x79, 0xb7, 0x03, 0x17, 0x53, 0x8f, 0x12, 0xd3,
	0xa1, 0x79, 0xd3, 0x71, 0x8d, 0xf9, 0xe3, 0x0e, 0x7c, 0x6c, 0x7e, 0x0d, 0xb3, 0x6e, 0x01, 0xb2,
	0x38, 0x4c, 0xda, 0x1f, 0xd5, 0xf8, 0x62, 0xf1, 0x63, 0x4d, 0xeb, 0xe3, 0x6f, 0x61, 0xfe, 0xb8,
	0xbe, 0x58, 0xb0, 0x7e, 0x5f, 0xd5, 0x2d, 0x02, 0x25, 0xb5, 0xf0, 0x6a, 0x44, 0x7f, 0xa1, 0xbe,
	0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xf1, 0x62, 0xcb, 0x52, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeployAgentClient is the client API for DeployAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployAgentClient interface {
	DeployGuestFs(ctx context.Context, in *DeployParams, opts ...grpc.CallOption) (*DeployGuestFsResponse, error)
	ResizeFs(ctx context.Context, in *ResizeFsParams, opts ...grpc.CallOption) (*Empty, error)
	FormatFs(ctx context.Context, in *FormatFsParams, opts ...grpc.CallOption) (*Empty, error)
	SaveToGlance(ctx context.Context, in *SaveToGlanceParams, opts ...grpc.CallOption) (*SaveToGlanceResponse, error)
	ProbeImageInfo(ctx context.Context, in *ProbeImageInfoPramas, opts ...grpc.CallOption) (*ImageInfo, error)
}

type deployAgentClient struct {
	cc *grpc.ClientConn
}

func NewDeployAgentClient(cc *grpc.ClientConn) DeployAgentClient {
	return &deployAgentClient{cc}
}

func (c *deployAgentClient) DeployGuestFs(ctx context.Context, in *DeployParams, opts ...grpc.CallOption) (*DeployGuestFsResponse, error) {
	out := new(DeployGuestFsResponse)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/DeployGuestFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) ResizeFs(ctx context.Context, in *ResizeFsParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/ResizeFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) FormatFs(ctx context.Context, in *FormatFsParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/FormatFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) SaveToGlance(ctx context.Context, in *SaveToGlanceParams, opts ...grpc.CallOption) (*SaveToGlanceResponse, error) {
	out := new(SaveToGlanceResponse)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/SaveToGlance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) ProbeImageInfo(ctx context.Context, in *ProbeImageInfoPramas, opts ...grpc.CallOption) (*ImageInfo, error) {
	out := new(ImageInfo)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/ProbeImageInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployAgentServer is the server API for DeployAgent service.
type DeployAgentServer interface {
	DeployGuestFs(context.Context, *DeployParams) (*DeployGuestFsResponse, error)
	ResizeFs(context.Context, *ResizeFsParams) (*Empty, error)
	FormatFs(context.Context, *FormatFsParams) (*Empty, error)
	SaveToGlance(context.Context, *SaveToGlanceParams) (*SaveToGlanceResponse, error)
	ProbeImageInfo(context.Context, *ProbeImageInfoPramas) (*ImageInfo, error)
}

// UnimplementedDeployAgentServer can be embedded to have forward compatible implementations.
type UnimplementedDeployAgentServer struct {
}

func (*UnimplementedDeployAgentServer) DeployGuestFs(ctx context.Context, req *DeployParams) (*DeployGuestFsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployGuestFs not implemented")
}
func (*UnimplementedDeployAgentServer) ResizeFs(ctx context.Context, req *ResizeFsParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeFs not implemented")
}
func (*UnimplementedDeployAgentServer) FormatFs(ctx context.Context, req *FormatFsParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FormatFs not implemented")
}
func (*UnimplementedDeployAgentServer) SaveToGlance(ctx context.Context, req *SaveToGlanceParams) (*SaveToGlanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveToGlance not implemented")
}
func (*UnimplementedDeployAgentServer) ProbeImageInfo(ctx context.Context, req *ProbeImageInfoPramas) (*ImageInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProbeImageInfo not implemented")
}

func RegisterDeployAgentServer(s *grpc.Server, srv DeployAgentServer) {
	s.RegisterService(&_DeployAgent_serviceDesc, srv)
}

func _DeployAgent_DeployGuestFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).DeployGuestFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/DeployGuestFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).DeployGuestFs(ctx, req.(*DeployParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_ResizeFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeFsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).ResizeFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/ResizeFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).ResizeFs(ctx, req.(*ResizeFsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_FormatFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormatFsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).FormatFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/FormatFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).FormatFs(ctx, req.(*FormatFsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_SaveToGlance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveToGlanceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).SaveToGlance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/SaveToGlance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).SaveToGlance(ctx, req.(*SaveToGlanceParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_ProbeImageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeImageInfoPramas)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).ProbeImageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/ProbeImageInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).ProbeImageInfo(ctx, req.(*ProbeImageInfoPramas))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.DeployAgent",
	HandlerType: (*DeployAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployGuestFs",
			Handler:    _DeployAgent_DeployGuestFs_Handler,
		},
		{
			MethodName: "ResizeFs",
			Handler:    _DeployAgent_ResizeFs_Handler,
		},
		{
			MethodName: "FormatFs",
			Handler:    _DeployAgent_FormatFs_Handler,
		},
		{
			MethodName: "SaveToGlance",
			Handler:    _DeployAgent_SaveToGlance_Handler,
		},
		{
			MethodName: "ProbeImageInfo",
			Handler:    _DeployAgent_ProbeImageInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploy.proto",
}
