// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/hostman/hostdeployer/apis/deploy.proto

// protoc --version=libprotoc 3.11.3
// protoc-gen-go --version=v1.3.5
// protoc --go_out=plugins=grpc:.  pkg/hostman/hostdeployer/apis/deploy.proto

package apis

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GuestDesc struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Nics                 []*Nic   `protobuf:"bytes,4,rep,name=nics,proto3" json:"nics,omitempty"`
	NicsStandby          []*Nic   `protobuf:"bytes,5,rep,name=nics_standby,json=nicsStandby,proto3" json:"nics_standby,omitempty"`
	Disks                []*Disk  `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	Hypervisor           string   `protobuf:"bytes,7,opt,name=Hypervisor,proto3" json:"Hypervisor,omitempty"`
	Hostname             string   `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestDesc) Reset()         { *m = GuestDesc{} }
func (m *GuestDesc) String() string { return proto.CompactTextString(m) }
func (*GuestDesc) ProtoMessage()    {}
func (*GuestDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{0}
}

func (m *GuestDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestDesc.Unmarshal(m, b)
}
func (m *GuestDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestDesc.Marshal(b, m, deterministic)
}
func (m *GuestDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestDesc.Merge(m, src)
}
func (m *GuestDesc) XXX_Size() int {
	return xxx_messageInfo_GuestDesc.Size(m)
}
func (m *GuestDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestDesc.DiscardUnknown(m)
}

var xxx_messageInfo_GuestDesc proto.InternalMessageInfo

func (m *GuestDesc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GuestDesc) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GuestDesc) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *GuestDesc) GetNics() []*Nic {
	if m != nil {
		return m.Nics
	}
	return nil
}

func (m *GuestDesc) GetNicsStandby() []*Nic {
	if m != nil {
		return m.NicsStandby
	}
	return nil
}

func (m *GuestDesc) GetDisks() []*Disk {
	if m != nil {
		return m.Disks
	}
	return nil
}

func (m *GuestDesc) GetHypervisor() string {
	if m != nil {
		return m.Hypervisor
	}
	return ""
}

func (m *GuestDesc) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type Disk struct {
	DiskId               string   `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	Driver               string   `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	CacheMode            string   `protobuf:"bytes,3,opt,name=cache_mode,json=cacheMode,proto3" json:"cache_mode,omitempty"`
	AioMode              string   `protobuf:"bytes,4,opt,name=aio_mode,json=aioMode,proto3" json:"aio_mode,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	TemplateId           string   `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ImagePath            string   `protobuf:"bytes,7,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	StorageId            string   `protobuf:"bytes,8,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Migrating            bool     `protobuf:"varint,9,opt,name=migrating,proto3" json:"migrating,omitempty"`
	TargetStorageId      string   `protobuf:"bytes,10,opt,name=target_storage_id,json=targetStorageId,proto3" json:"target_storage_id,omitempty"`
	Path                 string   `protobuf:"bytes,11,opt,name=path,proto3" json:"path,omitempty"`
	Format               string   `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty"`
	Index                int32    `protobuf:"varint,13,opt,name=index,proto3" json:"index,omitempty"`
	MergeSnapshot        bool     `protobuf:"varint,14,opt,name=merge_snapshot,json=mergeSnapshot,proto3" json:"merge_snapshot,omitempty"`
	Fs                   string   `protobuf:"bytes,15,opt,name=fs,proto3" json:"fs,omitempty"`
	Mountpoint           string   `protobuf:"bytes,16,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Dev                  string   `protobuf:"bytes,17,opt,name=dev,proto3" json:"dev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disk) Reset()         { *m = Disk{} }
func (m *Disk) String() string { return proto.CompactTextString(m) }
func (*Disk) ProtoMessage()    {}
func (*Disk) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{1}
}

func (m *Disk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disk.Unmarshal(m, b)
}
func (m *Disk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disk.Marshal(b, m, deterministic)
}
func (m *Disk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disk.Merge(m, src)
}
func (m *Disk) XXX_Size() int {
	return xxx_messageInfo_Disk.Size(m)
}
func (m *Disk) XXX_DiscardUnknown() {
	xxx_messageInfo_Disk.DiscardUnknown(m)
}

var xxx_messageInfo_Disk proto.InternalMessageInfo

func (m *Disk) GetDiskId() string {
	if m != nil {
		return m.DiskId
	}
	return ""
}

func (m *Disk) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Disk) GetCacheMode() string {
	if m != nil {
		return m.CacheMode
	}
	return ""
}

func (m *Disk) GetAioMode() string {
	if m != nil {
		return m.AioMode
	}
	return ""
}

func (m *Disk) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Disk) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *Disk) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Disk) GetStorageId() string {
	if m != nil {
		return m.StorageId
	}
	return ""
}

func (m *Disk) GetMigrating() bool {
	if m != nil {
		return m.Migrating
	}
	return false
}

func (m *Disk) GetTargetStorageId() string {
	if m != nil {
		return m.TargetStorageId
	}
	return ""
}

func (m *Disk) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Disk) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Disk) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Disk) GetMergeSnapshot() bool {
	if m != nil {
		return m.MergeSnapshot
	}
	return false
}

func (m *Disk) GetFs() string {
	if m != nil {
		return m.Fs
	}
	return ""
}

func (m *Disk) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

func (m *Disk) GetDev() string {
	if m != nil {
		return m.Dev
	}
	return ""
}

type Nic struct {
	Mac                  string   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Net                  string   `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	NetId                string   `protobuf:"bytes,4,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	Virtual              bool     `protobuf:"varint,5,opt,name=virtual,proto3" json:"virtual,omitempty"`
	Gateway              string   `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns                  string   `protobuf:"bytes,7,opt,name=dns,proto3" json:"dns,omitempty"`
	Domain               string   `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	Routes               string   `protobuf:"bytes,9,opt,name=routes,proto3" json:"routes,omitempty"`
	Ifname               string   `protobuf:"bytes,10,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Masklen              int32    `protobuf:"varint,11,opt,name=masklen,proto3" json:"masklen,omitempty"`
	Driver               string   `protobuf:"bytes,12,opt,name=driver,proto3" json:"driver,omitempty"`
	Bridge               string   `protobuf:"bytes,13,opt,name=bridge,proto3" json:"bridge,omitempty"`
	WireId               string   `protobuf:"bytes,14,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	Vlan                 int32    `protobuf:"varint,15,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Interface            string   `protobuf:"bytes,16,opt,name=interface,proto3" json:"interface,omitempty"`
	Bw                   int32    `protobuf:"varint,17,opt,name=bw,proto3" json:"bw,omitempty"`
	Index                int32    `protobuf:"varint,18,opt,name=index,proto3" json:"index,omitempty"`
	VirtualIps           []string `protobuf:"bytes,19,rep,name=virtual_ips,json=virtualIps,proto3" json:"virtual_ips,omitempty"`
	ExternelId           string   `protobuf:"bytes,20,opt,name=externel_id,json=externelId,proto3" json:"externel_id,omitempty"`
	TeamWith             string   `protobuf:"bytes,21,opt,name=team_with,json=teamWith,proto3" json:"team_with,omitempty"`
	Manual               bool     `protobuf:"varint,22,opt,name=manual,proto3" json:"manual,omitempty"`
	NicType              string   `protobuf:"bytes,23,opt,name=nic_type,json=nicType,proto3" json:"nic_type,omitempty"`
	LinkUp               bool     `protobuf:"varint,24,opt,name=link_up,json=linkUp,proto3" json:"link_up,omitempty"`
	Mtu                  int64    `protobuf:"varint,25,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Name                 string   `protobuf:"bytes,26,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nic) Reset()         { *m = Nic{} }
func (m *Nic) String() string { return proto.CompactTextString(m) }
func (*Nic) ProtoMessage()    {}
func (*Nic) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{2}
}

func (m *Nic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nic.Unmarshal(m, b)
}
func (m *Nic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nic.Marshal(b, m, deterministic)
}
func (m *Nic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nic.Merge(m, src)
}
func (m *Nic) XXX_Size() int {
	return xxx_messageInfo_Nic.Size(m)
}
func (m *Nic) XXX_DiscardUnknown() {
	xxx_messageInfo_Nic.DiscardUnknown(m)
}

var xxx_messageInfo_Nic proto.InternalMessageInfo

func (m *Nic) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Nic) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Nic) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *Nic) GetNetId() string {
	if m != nil {
		return m.NetId
	}
	return ""
}

func (m *Nic) GetVirtual() bool {
	if m != nil {
		return m.Virtual
	}
	return false
}

func (m *Nic) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Nic) GetDns() string {
	if m != nil {
		return m.Dns
	}
	return ""
}

func (m *Nic) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Nic) GetRoutes() string {
	if m != nil {
		return m.Routes
	}
	return ""
}

func (m *Nic) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

func (m *Nic) GetMasklen() int32 {
	if m != nil {
		return m.Masklen
	}
	return 0
}

func (m *Nic) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Nic) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

func (m *Nic) GetWireId() string {
	if m != nil {
		return m.WireId
	}
	return ""
}

func (m *Nic) GetVlan() int32 {
	if m != nil {
		return m.Vlan
	}
	return 0
}

func (m *Nic) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *Nic) GetBw() int32 {
	if m != nil {
		return m.Bw
	}
	return 0
}

func (m *Nic) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Nic) GetVirtualIps() []string {
	if m != nil {
		return m.VirtualIps
	}
	return nil
}

func (m *Nic) GetExternelId() string {
	if m != nil {
		return m.ExternelId
	}
	return ""
}

func (m *Nic) GetTeamWith() string {
	if m != nil {
		return m.TeamWith
	}
	return ""
}

func (m *Nic) GetManual() bool {
	if m != nil {
		return m.Manual
	}
	return false
}

func (m *Nic) GetNicType() string {
	if m != nil {
		return m.NicType
	}
	return ""
}

func (m *Nic) GetLinkUp() bool {
	if m != nil {
		return m.LinkUp
	}
	return false
}

func (m *Nic) GetMtu() int64 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *Nic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VDDKConInfo struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Passwd               string   `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Vmref                string   `protobuf:"bytes,5,opt,name=vmref,proto3" json:"vmref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VDDKConInfo) Reset()         { *m = VDDKConInfo{} }
func (m *VDDKConInfo) String() string { return proto.CompactTextString(m) }
func (*VDDKConInfo) ProtoMessage()    {}
func (*VDDKConInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{3}
}

func (m *VDDKConInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VDDKConInfo.Unmarshal(m, b)
}
func (m *VDDKConInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VDDKConInfo.Marshal(b, m, deterministic)
}
func (m *VDDKConInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VDDKConInfo.Merge(m, src)
}
func (m *VDDKConInfo) XXX_Size() int {
	return xxx_messageInfo_VDDKConInfo.Size(m)
}
func (m *VDDKConInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VDDKConInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VDDKConInfo proto.InternalMessageInfo

func (m *VDDKConInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *VDDKConInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *VDDKConInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *VDDKConInfo) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *VDDKConInfo) GetVmref() string {
	if m != nil {
		return m.Vmref
	}
	return ""
}

type DeployInfo struct {
	PublicKey               *SSHKeys         `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Deploys                 []*DeployContent `protobuf:"bytes,2,rep,name=deploys,proto3" json:"deploys,omitempty"`
	Password                string           `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	IsInit                  bool             `protobuf:"varint,4,opt,name=is_init,json=isInit,proto3" json:"is_init,omitempty"`
	EnableTty               bool             `protobuf:"varint,5,opt,name=enable_tty,json=enableTty,proto3" json:"enable_tty,omitempty"`
	DefaultRootUser         bool             `protobuf:"varint,6,opt,name=default_root_user,json=defaultRootUser,proto3" json:"default_root_user,omitempty"`
	WindowsDefaultAdminUser bool             `protobuf:"varint,7,opt,name=windows_default_admin_user,json=windowsDefaultAdminUser,proto3" json:"windows_default_admin_user,omitempty"`
	EnableCloudInit         bool             `protobuf:"varint,8,opt,name=enable_cloud_init,json=enableCloudInit,proto3" json:"enable_cloud_init,omitempty"`
	LoginAccount            string           `protobuf:"bytes,9,opt,name=login_account,json=loginAccount,proto3" json:"login_account,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{4}
}

func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (m *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(m, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetPublicKey() *SSHKeys {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *DeployInfo) GetDeploys() []*DeployContent {
	if m != nil {
		return m.Deploys
	}
	return nil
}

func (m *DeployInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DeployInfo) GetIsInit() bool {
	if m != nil {
		return m.IsInit
	}
	return false
}

func (m *DeployInfo) GetEnableTty() bool {
	if m != nil {
		return m.EnableTty
	}
	return false
}

func (m *DeployInfo) GetDefaultRootUser() bool {
	if m != nil {
		return m.DefaultRootUser
	}
	return false
}

func (m *DeployInfo) GetWindowsDefaultAdminUser() bool {
	if m != nil {
		return m.WindowsDefaultAdminUser
	}
	return false
}

func (m *DeployInfo) GetEnableCloudInit() bool {
	if m != nil {
		return m.EnableCloudInit
	}
	return false
}

func (m *DeployInfo) GetLoginAccount() string {
	if m != nil {
		return m.LoginAccount
	}
	return ""
}

type SSHKeys struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	DeletePublicKey      string   `protobuf:"bytes,2,opt,name=delete_public_key,json=deletePublicKey,proto3" json:"delete_public_key,omitempty"`
	AdminPublicKey       string   `protobuf:"bytes,3,opt,name=admin_public_key,json=adminPublicKey,proto3" json:"admin_public_key,omitempty"`
	ProjectPublicKey     string   `protobuf:"bytes,4,opt,name=project_public_key,json=projectPublicKey,proto3" json:"project_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSHKeys) Reset()         { *m = SSHKeys{} }
func (m *SSHKeys) String() string { return proto.CompactTextString(m) }
func (*SSHKeys) ProtoMessage()    {}
func (*SSHKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{5}
}

func (m *SSHKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSHKeys.Unmarshal(m, b)
}
func (m *SSHKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSHKeys.Marshal(b, m, deterministic)
}
func (m *SSHKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSHKeys.Merge(m, src)
}
func (m *SSHKeys) XXX_Size() int {
	return xxx_messageInfo_SSHKeys.Size(m)
}
func (m *SSHKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_SSHKeys.DiscardUnknown(m)
}

var xxx_messageInfo_SSHKeys proto.InternalMessageInfo

func (m *SSHKeys) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SSHKeys) GetDeletePublicKey() string {
	if m != nil {
		return m.DeletePublicKey
	}
	return ""
}

func (m *SSHKeys) GetAdminPublicKey() string {
	if m != nil {
		return m.AdminPublicKey
	}
	return ""
}

func (m *SSHKeys) GetProjectPublicKey() string {
	if m != nil {
		return m.ProjectPublicKey
	}
	return ""
}

type DeployContent struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployContent) Reset()         { *m = DeployContent{} }
func (m *DeployContent) String() string { return proto.CompactTextString(m) }
func (*DeployContent) ProtoMessage()    {}
func (*DeployContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{6}
}

func (m *DeployContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployContent.Unmarshal(m, b)
}
func (m *DeployContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployContent.Marshal(b, m, deterministic)
}
func (m *DeployContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployContent.Merge(m, src)
}
func (m *DeployContent) XXX_Size() int {
	return xxx_messageInfo_DeployContent.Size(m)
}
func (m *DeployContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployContent.DiscardUnknown(m)
}

var xxx_messageInfo_DeployContent proto.InternalMessageInfo

func (m *DeployContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DeployContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DeployContent) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DeployGuestFsResponse struct {
	Distro               string   `protobuf:"bytes,1,opt,name=distro,proto3" json:"distro,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Os                   string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Account              string   `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	Key                  string   `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployGuestFsResponse) Reset()         { *m = DeployGuestFsResponse{} }
func (m *DeployGuestFsResponse) String() string { return proto.CompactTextString(m) }
func (*DeployGuestFsResponse) ProtoMessage()    {}
func (*DeployGuestFsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{8}
}

func (m *DeployGuestFsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployGuestFsResponse.Unmarshal(m, b)
}
func (m *DeployGuestFsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployGuestFsResponse.Marshal(b, m, deterministic)
}
func (m *DeployGuestFsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployGuestFsResponse.Merge(m, src)
}
func (m *DeployGuestFsResponse) XXX_Size() int {
	return xxx_messageInfo_DeployGuestFsResponse.Size(m)
}
func (m *DeployGuestFsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployGuestFsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployGuestFsResponse proto.InternalMessageInfo

func (m *DeployGuestFsResponse) GetDistro() string {
	if m != nil {
		return m.Distro
	}
	return ""
}

func (m *DeployGuestFsResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeployGuestFsResponse) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *DeployGuestFsResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DeployGuestFsResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *DeployGuestFsResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DeployGuestFsResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeployParams struct {
	DiskPath             string       `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	GuestDesc            *GuestDesc   `protobuf:"bytes,2,opt,name=guest_desc,json=guestDesc,proto3" json:"guest_desc,omitempty"`
	DeployInfo           *DeployInfo  `protobuf:"bytes,3,opt,name=deploy_info,json=deployInfo,proto3" json:"deploy_info,omitempty"`
	VddkInfo             *VDDKConInfo `protobuf:"bytes,4,opt,name=vddk_info,json=vddkInfo,proto3" json:"vddk_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeployParams) Reset()         { *m = DeployParams{} }
func (m *DeployParams) String() string { return proto.CompactTextString(m) }
func (*DeployParams) ProtoMessage()    {}
func (*DeployParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{9}
}

func (m *DeployParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployParams.Unmarshal(m, b)
}
func (m *DeployParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployParams.Marshal(b, m, deterministic)
}
func (m *DeployParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployParams.Merge(m, src)
}
func (m *DeployParams) XXX_Size() int {
	return xxx_messageInfo_DeployParams.Size(m)
}
func (m *DeployParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeployParams proto.InternalMessageInfo

func (m *DeployParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *DeployParams) GetGuestDesc() *GuestDesc {
	if m != nil {
		return m.GuestDesc
	}
	return nil
}

func (m *DeployParams) GetDeployInfo() *DeployInfo {
	if m != nil {
		return m.DeployInfo
	}
	return nil
}

func (m *DeployParams) GetVddkInfo() *VDDKConInfo {
	if m != nil {
		return m.VddkInfo
	}
	return nil
}

type ResizeFsParams struct {
	DiskPath             string       `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	Hypervisor           string       `protobuf:"bytes,2,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	VddkInfo             *VDDKConInfo `protobuf:"bytes,3,opt,name=vddk_info,json=vddkInfo,proto3" json:"vddk_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResizeFsParams) Reset()         { *m = ResizeFsParams{} }
func (m *ResizeFsParams) String() string { return proto.CompactTextString(m) }
func (*ResizeFsParams) ProtoMessage()    {}
func (*ResizeFsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{10}
}

func (m *ResizeFsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResizeFsParams.Unmarshal(m, b)
}
func (m *ResizeFsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResizeFsParams.Marshal(b, m, deterministic)
}
func (m *ResizeFsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResizeFsParams.Merge(m, src)
}
func (m *ResizeFsParams) XXX_Size() int {
	return xxx_messageInfo_ResizeFsParams.Size(m)
}
func (m *ResizeFsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ResizeFsParams.DiscardUnknown(m)
}

var xxx_messageInfo_ResizeFsParams proto.InternalMessageInfo

func (m *ResizeFsParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *ResizeFsParams) GetHypervisor() string {
	if m != nil {
		return m.Hypervisor
	}
	return ""
}

func (m *ResizeFsParams) GetVddkInfo() *VDDKConInfo {
	if m != nil {
		return m.VddkInfo
	}
	return nil
}

type FormatFsParams struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	FsFormat             string   `protobuf:"bytes,2,opt,name=fs_format,json=fsFormat,proto3" json:"fs_format,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormatFsParams) Reset()         { *m = FormatFsParams{} }
func (m *FormatFsParams) String() string { return proto.CompactTextString(m) }
func (*FormatFsParams) ProtoMessage()    {}
func (*FormatFsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{11}
}

func (m *FormatFsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatFsParams.Unmarshal(m, b)
}
func (m *FormatFsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatFsParams.Marshal(b, m, deterministic)
}
func (m *FormatFsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatFsParams.Merge(m, src)
}
func (m *FormatFsParams) XXX_Size() int {
	return xxx_messageInfo_FormatFsParams.Size(m)
}
func (m *FormatFsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatFsParams.DiscardUnknown(m)
}

var xxx_messageInfo_FormatFsParams proto.InternalMessageInfo

func (m *FormatFsParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *FormatFsParams) GetFsFormat() string {
	if m != nil {
		return m.FsFormat
	}
	return ""
}

func (m *FormatFsParams) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ReleaseInfo struct {
	Distro               string   `protobuf:"bytes,1,opt,name=distro,proto3" json:"distro,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch                 string   `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseInfo) Reset()         { *m = ReleaseInfo{} }
func (m *ReleaseInfo) String() string { return proto.CompactTextString(m) }
func (*ReleaseInfo) ProtoMessage()    {}
func (*ReleaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{12}
}

func (m *ReleaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseInfo.Unmarshal(m, b)
}
func (m *ReleaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseInfo.Marshal(b, m, deterministic)
}
func (m *ReleaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseInfo.Merge(m, src)
}
func (m *ReleaseInfo) XXX_Size() int {
	return xxx_messageInfo_ReleaseInfo.Size(m)
}
func (m *ReleaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseInfo proto.InternalMessageInfo

func (m *ReleaseInfo) GetDistro() string {
	if m != nil {
		return m.Distro
	}
	return ""
}

func (m *ReleaseInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReleaseInfo) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *ReleaseInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type SaveToGlanceParams struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	Compress             bool     `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveToGlanceParams) Reset()         { *m = SaveToGlanceParams{} }
func (m *SaveToGlanceParams) String() string { return proto.CompactTextString(m) }
func (*SaveToGlanceParams) ProtoMessage()    {}
func (*SaveToGlanceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{13}
}

func (m *SaveToGlanceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveToGlanceParams.Unmarshal(m, b)
}
func (m *SaveToGlanceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveToGlanceParams.Marshal(b, m, deterministic)
}
func (m *SaveToGlanceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveToGlanceParams.Merge(m, src)
}
func (m *SaveToGlanceParams) XXX_Size() int {
	return xxx_messageInfo_SaveToGlanceParams.Size(m)
}
func (m *SaveToGlanceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveToGlanceParams.DiscardUnknown(m)
}

var xxx_messageInfo_SaveToGlanceParams proto.InternalMessageInfo

func (m *SaveToGlanceParams) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *SaveToGlanceParams) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

type SaveToGlanceResponse struct {
	OsInfo               string       `protobuf:"bytes,1,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	ReleaseInfo          *ReleaseInfo `protobuf:"bytes,2,opt,name=release_info,json=releaseInfo,proto3" json:"release_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SaveToGlanceResponse) Reset()         { *m = SaveToGlanceResponse{} }
func (m *SaveToGlanceResponse) String() string { return proto.CompactTextString(m) }
func (*SaveToGlanceResponse) ProtoMessage()    {}
func (*SaveToGlanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{14}
}

func (m *SaveToGlanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveToGlanceResponse.Unmarshal(m, b)
}
func (m *SaveToGlanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveToGlanceResponse.Marshal(b, m, deterministic)
}
func (m *SaveToGlanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveToGlanceResponse.Merge(m, src)
}
func (m *SaveToGlanceResponse) XXX_Size() int {
	return xxx_messageInfo_SaveToGlanceResponse.Size(m)
}
func (m *SaveToGlanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveToGlanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveToGlanceResponse proto.InternalMessageInfo

func (m *SaveToGlanceResponse) GetOsInfo() string {
	if m != nil {
		return m.OsInfo
	}
	return ""
}

func (m *SaveToGlanceResponse) GetReleaseInfo() *ReleaseInfo {
	if m != nil {
		return m.ReleaseInfo
	}
	return nil
}

type ProbeImageInfoPramas struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeImageInfoPramas) Reset()         { *m = ProbeImageInfoPramas{} }
func (m *ProbeImageInfoPramas) String() string { return proto.CompactTextString(m) }
func (*ProbeImageInfoPramas) ProtoMessage()    {}
func (*ProbeImageInfoPramas) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{15}
}

func (m *ProbeImageInfoPramas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeImageInfoPramas.Unmarshal(m, b)
}
func (m *ProbeImageInfoPramas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeImageInfoPramas.Marshal(b, m, deterministic)
}
func (m *ProbeImageInfoPramas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeImageInfoPramas.Merge(m, src)
}
func (m *ProbeImageInfoPramas) XXX_Size() int {
	return xxx_messageInfo_ProbeImageInfoPramas.Size(m)
}
func (m *ProbeImageInfoPramas) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeImageInfoPramas.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeImageInfoPramas proto.InternalMessageInfo

func (m *ProbeImageInfoPramas) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

type ImageInfo struct {
	OsInfo                *ReleaseInfo `protobuf:"bytes,1,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	OsType                string       `protobuf:"bytes,2,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	IsUefiSupport         bool         `protobuf:"varint,3,opt,name=is_uefi_support,json=isUefiSupport,proto3" json:"is_uefi_support,omitempty"`
	IsLvmPartition        bool         `protobuf:"varint,4,opt,name=is_lvm_partition,json=isLvmPartition,proto3" json:"is_lvm_partition,omitempty"`
	IsReadonly            bool         `protobuf:"varint,5,opt,name=is_readonly,json=isReadonly,proto3" json:"is_readonly,omitempty"`
	PhysicalPartitionType string       `protobuf:"bytes,6,opt,name=physical_partition_type,json=physicalPartitionType,proto3" json:"physical_partition_type,omitempty"`
	IsInstalledCloudInit  bool         `protobuf:"varint,7,opt,name=is_installed_cloud_init,json=isInstalledCloudInit,proto3" json:"is_installed_cloud_init,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *ImageInfo) Reset()         { *m = ImageInfo{} }
func (m *ImageInfo) String() string { return proto.CompactTextString(m) }
func (*ImageInfo) ProtoMessage()    {}
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{16}
}

func (m *ImageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageInfo.Unmarshal(m, b)
}
func (m *ImageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageInfo.Marshal(b, m, deterministic)
}
func (m *ImageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageInfo.Merge(m, src)
}
func (m *ImageInfo) XXX_Size() int {
	return xxx_messageInfo_ImageInfo.Size(m)
}
func (m *ImageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImageInfo proto.InternalMessageInfo

func (m *ImageInfo) GetOsInfo() *ReleaseInfo {
	if m != nil {
		return m.OsInfo
	}
	return nil
}

func (m *ImageInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *ImageInfo) GetIsUefiSupport() bool {
	if m != nil {
		return m.IsUefiSupport
	}
	return false
}

func (m *ImageInfo) GetIsLvmPartition() bool {
	if m != nil {
		return m.IsLvmPartition
	}
	return false
}

func (m *ImageInfo) GetIsReadonly() bool {
	if m != nil {
		return m.IsReadonly
	}
	return false
}

func (m *ImageInfo) GetPhysicalPartitionType() string {
	if m != nil {
		return m.PhysicalPartitionType
	}
	return ""
}

func (m *ImageInfo) GetIsInstalledCloudInit() bool {
	if m != nil {
		return m.IsInstalledCloudInit
	}
	return false
}

type EsxiDiskInfo struct {
	DiskPath             string   `protobuf:"bytes,1,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EsxiDiskInfo) Reset()         { *m = EsxiDiskInfo{} }
func (m *EsxiDiskInfo) String() string { return proto.CompactTextString(m) }
func (*EsxiDiskInfo) ProtoMessage()    {}
func (*EsxiDiskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{17}
}

func (m *EsxiDiskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EsxiDiskInfo.Unmarshal(m, b)
}
func (m *EsxiDiskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EsxiDiskInfo.Marshal(b, m, deterministic)
}
func (m *EsxiDiskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EsxiDiskInfo.Merge(m, src)
}
func (m *EsxiDiskInfo) XXX_Size() int {
	return xxx_messageInfo_EsxiDiskInfo.Size(m)
}
func (m *EsxiDiskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EsxiDiskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EsxiDiskInfo proto.InternalMessageInfo

func (m *EsxiDiskInfo) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

type ConnectEsxiDisksParams struct {
	VddkInfo             *VDDKConInfo    `protobuf:"bytes,1,opt,name=vddk_info,json=vddkInfo,proto3" json:"vddk_info,omitempty"`
	AccessInfo           []*EsxiDiskInfo `protobuf:"bytes,2,rep,name=access_info,json=accessInfo,proto3" json:"access_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConnectEsxiDisksParams) Reset()         { *m = ConnectEsxiDisksParams{} }
func (m *ConnectEsxiDisksParams) String() string { return proto.CompactTextString(m) }
func (*ConnectEsxiDisksParams) ProtoMessage()    {}
func (*ConnectEsxiDisksParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{18}
}

func (m *ConnectEsxiDisksParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectEsxiDisksParams.Unmarshal(m, b)
}
func (m *ConnectEsxiDisksParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectEsxiDisksParams.Marshal(b, m, deterministic)
}
func (m *ConnectEsxiDisksParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectEsxiDisksParams.Merge(m, src)
}
func (m *ConnectEsxiDisksParams) XXX_Size() int {
	return xxx_messageInfo_ConnectEsxiDisksParams.Size(m)
}
func (m *ConnectEsxiDisksParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectEsxiDisksParams.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectEsxiDisksParams proto.InternalMessageInfo

func (m *ConnectEsxiDisksParams) GetVddkInfo() *VDDKConInfo {
	if m != nil {
		return m.VddkInfo
	}
	return nil
}

func (m *ConnectEsxiDisksParams) GetAccessInfo() []*EsxiDiskInfo {
	if m != nil {
		return m.AccessInfo
	}
	return nil
}

type EsxiDisksConnectionInfo struct {
	Disks                []*EsxiDiskInfo `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EsxiDisksConnectionInfo) Reset()         { *m = EsxiDisksConnectionInfo{} }
func (m *EsxiDisksConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*EsxiDisksConnectionInfo) ProtoMessage()    {}
func (*EsxiDisksConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd896c9c60108af6, []int{19}
}

func (m *EsxiDisksConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EsxiDisksConnectionInfo.Unmarshal(m, b)
}
func (m *EsxiDisksConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EsxiDisksConnectionInfo.Marshal(b, m, deterministic)
}
func (m *EsxiDisksConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EsxiDisksConnectionInfo.Merge(m, src)
}
func (m *EsxiDisksConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_EsxiDisksConnectionInfo.Size(m)
}
func (m *EsxiDisksConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EsxiDisksConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EsxiDisksConnectionInfo proto.InternalMessageInfo

func (m *EsxiDisksConnectionInfo) GetDisks() []*EsxiDiskInfo {
	if m != nil {
		return m.Disks
	}
	return nil
}

func init() {
	proto.RegisterType((*GuestDesc)(nil), "apis.GuestDesc")
	proto.RegisterType((*Disk)(nil), "apis.Disk")
	proto.RegisterType((*Nic)(nil), "apis.Nic")
	proto.RegisterType((*VDDKConInfo)(nil), "apis.VDDKConInfo")
	proto.RegisterType((*DeployInfo)(nil), "apis.DeployInfo")
	proto.RegisterType((*SSHKeys)(nil), "apis.SSHKeys")
	proto.RegisterType((*DeployContent)(nil), "apis.DeployContent")
	proto.RegisterType((*Empty)(nil), "apis.Empty")
	proto.RegisterType((*DeployGuestFsResponse)(nil), "apis.DeployGuestFsResponse")
	proto.RegisterType((*DeployParams)(nil), "apis.DeployParams")
	proto.RegisterType((*ResizeFsParams)(nil), "apis.ResizeFsParams")
	proto.RegisterType((*FormatFsParams)(nil), "apis.FormatFsParams")
	proto.RegisterType((*ReleaseInfo)(nil), "apis.ReleaseInfo")
	proto.RegisterType((*SaveToGlanceParams)(nil), "apis.SaveToGlanceParams")
	proto.RegisterType((*SaveToGlanceResponse)(nil), "apis.SaveToGlanceResponse")
	proto.RegisterType((*ProbeImageInfoPramas)(nil), "apis.ProbeImageInfoPramas")
	proto.RegisterType((*ImageInfo)(nil), "apis.ImageInfo")
	proto.RegisterType((*EsxiDiskInfo)(nil), "apis.EsxiDiskInfo")
	proto.RegisterType((*ConnectEsxiDisksParams)(nil), "apis.ConnectEsxiDisksParams")
	proto.RegisterType((*EsxiDisksConnectionInfo)(nil), "apis.EsxiDisksConnectionInfo")
}

func init() {
	proto.RegisterFile("pkg/hostman/hostdeployer/apis/deploy.proto", fileDescriptor_dd896c9c60108af6)
}

var fileDescriptor_dd896c9c60108af6 = []byte{
	// 1760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0x1c, 0x49,
	0x15, 0xd6, 0xfc, 0x4f, 0x9f, 0xf1, 0x5f, 0x2a, 0x8e, 0xdd, 0x3b, 0xd9, 0xec, 0x5a, 0x83, 0x40,
	0x56, 0xc8, 0x3a, 0xc2, 0x01, 0x6e, 0x10, 0x12, 0x91, 0xbd, 0xd9, 0xb5, 0xc2, 0x2e, 0x56, 0x3b,
	0x81, 0x3b, 0x5a, 0xe5, 0xee, 0x9a, 0x99, 0xc2, 0xdd, 0x55, 0xad, 0xae, 0x9a, 0x99, 0x0c, 0xd2,
	0xbe, 0x11, 0x57, 0x48, 0xdc, 0x72, 0xc9, 0x3b, 0xf0, 0x0a, 0x3c, 0x00, 0xdc, 0xa2, 0x73, 0xaa,
	0xba, 0xa7, 0xc7, 0x1b, 0xb2, 0xb9, 0xe1, 0xaa, 0xeb, 0xfc, 0x54, 0xd5, 0xf9, 0xfd, 0x4e, 0x35,
	0x3c, 0x2d, 0xee, 0x66, 0xcf, 0xe7, 0xda, 0xd8, 0x9c, 0x2b, 0xfa, 0xa6, 0xa2, 0xc8, 0xf4, 0x5a,
	0x94, 0xcf, 0x79, 0x21, 0xcd, 0x73, 0x47, 0x9d, 0x15, 0xa5, 0xb6, 0x9a, 0x75, 0x91, 0x35, 0xf9,
	0x77, 0x0b, 0x82, 0xaf, 0x16, 0xc2, 0xd8, 0x4b, 0x61, 0x12, 0xc6, 0xa0, 0xab, 0x78, 0x2e, 0xc2,
	0xd6, 0x49, 0xeb, 0x34, 0x88, 0x68, 0x8d, 0xbc, 0xc5, 0x42, 0xa6, 0x61, 0xdb, 0xf1, 0x70, 0xcd,
	0x8e, 0xa0, 0x9f, 0xea, 0x9c, 0x4b, 0x15, 0x76, 0x88, 0xeb, 0x29, 0xf6, 0x04, 0xba, 0x4a, 0x26,
	0x26, 0xec, 0x9e, 0x74, 0x4e, 0x47, 0xe7, 0xc1, 0x19, 0x5e, 0x71, 0xf6, 0xad, 0x4c, 0x22, 0x62,
	0xb3, 0x67, 0xb0, 0x83, 0xdf, 0xd8, 0x58, 0xae, 0xd2, 0xdb, 0x75, 0xd8, 0xbb, 0xaf, 0x36, 0x42,
	0xf1, 0x8d, 0x93, 0xb2, 0x13, 0xe8, 0xa5, 0xd2, 0xdc, 0x99, 0xb0, 0x4f, 0x6a, 0xe0, 0xd4, 0x2e,
	0xa5, 0xb9, 0x8b, 0x9c, 0x80, 0x7d, 0x06, 0xf0, 0xf5, 0xba, 0x10, 0xe5, 0x52, 0x1a, 0x5d, 0x86,
	0x03, 0x32, 0xa5, 0xc1, 0x61, 0x63, 0x18, 0x62, 0x10, 0xc8, 0xa5, 0x21, 0x49, 0x6b, 0x7a, 0xf2,
	0xcf, 0x0e, 0x74, 0xf1, 0x2c, 0x76, 0x0c, 0x03, 0x3c, 0x2d, 0x96, 0xa9, 0x77, 0xbb, 0x8f, 0xe4,
	0x95, 0x73, 0xb2, 0x94, 0x4b, 0x51, 0x7a, 0xd7, 0x3d, 0xc5, 0x9e, 0x00, 0x24, 0x3c, 0x99, 0x8b,
	0x38, 0xd7, 0xa9, 0xf0, 0x01, 0x08, 0x88, 0xf3, 0x8d, 0x4e, 0x05, 0xfb, 0x04, 0x86, 0x5c, 0x6a,
	0x27, 0xec, 0x92, 0x70, 0xc0, 0xa5, 0x26, 0x11, 0x83, 0xae, 0x91, 0x7f, 0x16, 0x61, 0xef, 0xa4,
	0x75, 0xda, 0x89, 0x68, 0xcd, 0x3e, 0x87, 0x91, 0x15, 0x79, 0x91, 0x71, 0x2b, 0xd0, 0x84, 0xbe,
	0x73, 0xa2, 0x62, 0x5d, 0xa5, 0x78, 0x9d, 0xcc, 0xf9, 0x4c, 0xc4, 0x05, 0xb7, 0x73, 0xef, 0x64,
	0x40, 0x9c, 0x6b, 0x6e, 0xe7, 0x28, 0x36, 0x56, 0x97, 0xa8, 0x20, 0x53, 0xef, 0x65, 0xe0, 0x39,
	0x57, 0x29, 0xfb, 0x14, 0x82, 0x5c, 0xce, 0x4a, 0x6e, 0xa5, 0x9a, 0x85, 0xc1, 0x49, 0xeb, 0x74,
	0x18, 0x6d, 0x18, 0xec, 0x29, 0x3c, 0xb0, 0xbc, 0x9c, 0x09, 0x1b, 0x37, 0xce, 0x00, 0x3a, 0x63,
	0xdf, 0x09, 0x6e, 0xea, 0x93, 0x18, 0x74, 0xc9, 0x82, 0x91, 0xab, 0x03, 0x5c, 0x63, 0x88, 0xa6,
	0xba, 0xcc, 0xb9, 0x0d, 0x77, 0x5c, 0x88, 0x1c, 0xc5, 0x0e, 0xa1, 0x27, 0x55, 0x2a, 0xde, 0x85,
	0xbb, 0x27, 0xad, 0xd3, 0x5e, 0xe4, 0x08, 0xf6, 0x63, 0xd8, 0xcb, 0x45, 0x39, 0x13, 0xb1, 0x51,
	0xbc, 0x30, 0x73, 0x6d, 0xc3, 0x3d, 0x32, 0x68, 0x97, 0xb8, 0x37, 0x9e, 0xc9, 0xf6, 0xa0, 0x3d,
	0x35, 0xe1, 0x3e, 0x1d, 0xd8, 0x9e, 0x52, 0x96, 0x73, 0xbd, 0x50, 0xb6, 0xd0, 0x52, 0xd9, 0xf0,
	0xc0, 0x05, 0x68, 0xc3, 0x61, 0x07, 0xd0, 0x49, 0xc5, 0x32, 0x7c, 0x40, 0x02, 0x5c, 0x4e, 0xfe,
	0xd5, 0x85, 0xce, 0xb7, 0x32, 0x41, 0x49, 0xce, 0x13, 0x9f, 0x56, 0x5c, 0xe2, 0xd9, 0xb2, 0xf0,
	0xf9, 0x6c, 0xcb, 0x02, 0x35, 0x94, 0xb0, 0x3e, 0x89, 0xb8, 0x64, 0x8f, 0xa0, 0xaf, 0x84, 0xc5,
	0x38, 0xb8, 0xe4, 0xf5, 0x94, 0xb0, 0x57, 0x29, 0x0b, 0x61, 0xb0, 0x94, 0xa5, 0x5d, 0xf0, 0x8c,
	0xb2, 0x37, 0x8c, 0x2a, 0x12, 0x25, 0x33, 0x6e, 0xc5, 0x8a, 0xaf, 0x7d, 0xf2, 0x2a, 0x92, 0x0c,
	0x53, 0xc6, 0xa7, 0x0c, 0x97, 0x8d, 0xbe, 0x19, 0x6e, 0xf5, 0xcd, 0x11, 0xf4, 0x4b, 0xbd, 0xb0,
	0xc2, 0x50, 0x8a, 0x82, 0xc8, 0x53, 0xc8, 0x97, 0x53, 0x2a, 0x5f, 0x97, 0x14, 0x4f, 0xe1, 0x9d,
	0x39, 0x37, 0x77, 0x99, 0x50, 0x94, 0x8e, 0x5e, 0x54, 0x91, 0x8d, 0xa2, 0xdd, 0xd9, 0x2a, 0xda,
	0x23, 0xe8, 0xdf, 0x96, 0x32, 0x9d, 0x09, 0x4a, 0x49, 0x10, 0x79, 0x0a, 0xab, 0x7f, 0x25, 0x4b,
	0xca, 0xfb, 0x9e, 0x13, 0x20, 0xe9, 0xd2, 0xbd, 0xcc, 0xb8, 0xa2, 0x3c, 0xf4, 0x22, 0x5a, 0x63,
	0x31, 0x49, 0x65, 0x45, 0x39, 0xe5, 0x89, 0xf0, 0x89, 0xd8, 0x30, 0x30, 0xb6, 0xb7, 0x2b, 0x4a,
	0x43, 0x2f, 0x6a, 0xdf, 0xae, 0x36, 0x45, 0xc0, 0x9a, 0x45, 0xf0, 0x39, 0x8c, 0x7c, 0xe4, 0x62,
	0x59, 0x98, 0xf0, 0xe1, 0x49, 0x07, 0xd3, 0xe9, 0x59, 0x57, 0x85, 0x41, 0x05, 0xf1, 0xce, 0x8a,
	0x52, 0x89, 0x0c, 0xad, 0x3a, 0x74, 0xf9, 0xae, 0x58, 0x57, 0x29, 0x7b, 0x0c, 0x81, 0x15, 0x3c,
	0x8f, 0x57, 0xd2, 0xce, 0xc3, 0x47, 0xae, 0xad, 0x91, 0xf1, 0x07, 0xe9, 0x2a, 0x32, 0xe7, 0x0a,
	0xd3, 0x74, 0x44, 0x69, 0xf2, 0x14, 0x76, 0xa5, 0x92, 0x49, 0x6c, 0xd7, 0x85, 0x08, 0x8f, 0x5d,
	0x9a, 0x94, 0x4c, 0xde, 0xac, 0x0b, 0x0a, 0x41, 0x26, 0xd5, 0x5d, 0xbc, 0x28, 0xc2, 0xd0, 0xed,
	0x41, 0xf2, 0x2d, 0x15, 0x47, 0x6e, 0x17, 0xe1, 0x27, 0xd4, 0xad, 0xb8, 0xac, 0xf1, 0x71, 0xbc,
	0xc1, 0xc7, 0xc9, 0x0a, 0x46, 0xbf, 0xbf, 0xbc, 0x7c, 0x7d, 0xa1, 0xd5, 0x95, 0x9a, 0x6a, 0x54,
	0x41, 0x8c, 0xa9, 0x20, 0x14, 0xd7, 0xd4, 0x3a, 0xba, 0xb4, 0x54, 0x77, 0xbd, 0x88, 0xd6, 0x04,
	0xab, 0x46, 0x94, 0xbe, 0xf4, 0x68, 0x8d, 0xc6, 0x17, 0xdc, 0x98, 0x55, 0x55, 0x7b, 0x9e, 0xc2,
	0x48, 0x2e, 0xf3, 0x52, 0x4c, 0xa9, 0xf4, 0x82, 0xc8, 0x11, 0x93, 0xff, 0xb4, 0x01, 0x2e, 0x09,
	0xd1, 0xe9, 0xe2, 0x67, 0x00, 0xc5, 0xe2, 0x36, 0x93, 0x49, 0x7c, 0x27, 0xd6, 0x74, 0xfd, 0xe8,
	0x7c, 0xd7, 0x61, 0xe6, 0xcd, 0xcd, 0xd7, 0xaf, 0xc5, 0xda, 0x44, 0x81, 0x53, 0x78, 0x2d, 0xd6,
	0xec, 0x0b, 0x18, 0xb8, 0x69, 0x60, 0xc2, 0x36, 0xc1, 0xeb, 0x43, 0x0f, 0xaf, 0xc4, 0xbc, 0xd0,
	0xca, 0x0a, 0x65, 0xa3, 0x4a, 0x07, 0x91, 0x94, 0x6c, 0xd1, 0x65, 0xea, 0x2d, 0xae, 0x69, 0x8c,
	0x9f, 0x34, 0xb1, 0x54, 0xd2, 0x92, 0xd9, 0xc3, 0xa8, 0x2f, 0xcd, 0x95, 0x92, 0x16, 0xa1, 0x49,
	0x28, 0x7e, 0x9b, 0x89, 0xd8, 0xda, 0xb5, 0x6f, 0x9b, 0xc0, 0x71, 0xde, 0xd8, 0x35, 0x82, 0x4f,
	0x2a, 0xa6, 0x7c, 0x91, 0xd9, 0xb8, 0xd4, 0xda, 0xc6, 0x14, 0x8e, 0x3e, 0x69, 0xed, 0x7b, 0x41,
	0xa4, 0xb5, 0x7d, 0x8b, 0x91, 0xf9, 0x15, 0x8c, 0x57, 0x52, 0xa5, 0x7a, 0x65, 0xe2, 0x6a, 0x0f,
	0x4f, 0x73, 0xa9, 0xdc, 0xa6, 0x01, 0x6d, 0x3a, 0xf6, 0x1a, 0x97, 0x4e, 0xe1, 0x25, 0xca, 0x69,
	0xf3, 0x53, 0x78, 0xe0, 0xed, 0x48, 0x32, 0xbd, 0x48, 0x9d, 0xa9, 0x43, 0x77, 0x91, 0x13, 0x5c,
	0x20, 0x9f, 0x6c, 0xfe, 0x11, 0xec, 0x66, 0x7a, 0x26, 0x55, 0xcc, 0x93, 0x04, 0x21, 0xc6, 0x37,
	0xe4, 0x0e, 0x31, 0x5f, 0x3a, 0xde, 0xe4, 0x2f, 0x2d, 0x18, 0xf8, 0x98, 0xa2, 0x93, 0xf7, 0xc2,
	0x1e, 0x34, 0xe3, 0x4c, 0x4e, 0x66, 0xc2, 0x8a, 0xb8, 0xa1, 0xe5, 0xf0, 0x67, 0xdf, 0x09, 0xae,
	0x6b, 0xdd, 0x53, 0x38, 0x70, 0x4e, 0x35, 0x54, 0x5d, 0xb0, 0xf7, 0x88, 0xbf, 0xd1, 0x7c, 0x06,
	0xac, 0x28, 0xf5, 0x9f, 0x44, 0x62, 0x9b, 0xba, 0xae, 0x68, 0x0e, 0xbc, 0xa4, 0xd6, 0x9e, 0xbc,
	0x85, 0xdd, 0xad, 0xb4, 0xd6, 0x50, 0xde, 0x6a, 0x40, 0x79, 0x08, 0x83, 0xc4, 0x89, 0xbd, 0x79,
	0x15, 0x89, 0x55, 0xc9, 0x13, 0x2b, 0x75, 0x3d, 0xec, 0x1d, 0x35, 0x19, 0x40, 0xef, 0xcb, 0xbc,
	0xb0, 0xeb, 0xc9, 0xdf, 0x5a, 0xf0, 0xc8, 0x5d, 0x40, 0x2f, 0x89, 0x57, 0x26, 0x12, 0xa6, 0xd0,
	0xca, 0x08, 0x42, 0x23, 0x69, 0x6c, 0xa9, 0x1b, 0xa3, 0xd5, 0x96, 0x9a, 0xd0, 0x54, 0x94, 0x06,
	0xcf, 0xf4, 0x97, 0x79, 0x12, 0x4d, 0xe3, 0x65, 0x32, 0xaf, 0xda, 0x02, 0xd7, 0x58, 0x7c, 0x19,
	0x57, 0xb3, 0x05, 0x9f, 0x55, 0x13, 0xb5, 0xa6, 0x11, 0x74, 0xb4, 0xf1, 0x7d, 0xd1, 0xd6, 0x06,
	0x4f, 0xae, 0x32, 0xe7, 0xd1, 0xd8, 0x93, 0xd8, 0xcd, 0x18, 0x24, 0x8f, 0xc6, 0x77, 0x62, 0x3d,
	0xf9, 0x7b, 0x0b, 0x76, 0x9c, 0xdd, 0xd7, 0xbc, 0xe4, 0xb9, 0x41, 0x64, 0xa1, 0xa7, 0x40, 0x23,
	0x38, 0x43, 0x64, 0xd0, 0xa0, 0x3d, 0x03, 0x98, 0xa1, 0x7b, 0x71, 0x2a, 0x4c, 0x42, 0x66, 0x8f,
	0xce, 0xf7, 0x5d, 0xd3, 0xd4, 0x0f, 0xa8, 0x28, 0x98, 0xd5, 0x6f, 0xa9, 0x9f, 0xc1, 0xc8, 0x75,
	0x4f, 0x2c, 0xd5, 0x54, 0x93, 0x43, 0xa3, 0xf3, 0x83, 0x66, 0x97, 0x61, 0xdb, 0x46, 0x90, 0x6e,
	0x5a, 0xf8, 0x0c, 0x82, 0x65, 0x9a, 0xde, 0xb9, 0x0d, 0x5d, 0xda, 0xf0, 0xc0, 0x6d, 0x68, 0x20,
	0x4c, 0x34, 0x44, 0x1d, 0x5c, 0x4d, 0xbe, 0x83, 0xbd, 0x48, 0xe0, 0x2b, 0xe2, 0x95, 0xf9, 0x18,
	0x0f, 0x3e, 0x03, 0x98, 0x6f, 0x9e, 0x4b, 0x2e, 0xf0, 0x0d, 0xce, 0xf6, 0xf5, 0x9d, 0x1f, 0xbe,
	0xfe, 0x8f, 0xb0, 0xf7, 0x8a, 0xe6, 0xfd, 0xc7, 0x5d, 0xff, 0x18, 0x82, 0xa9, 0x89, 0xfd, 0x7b,
	0xc1, 0xdd, 0x3e, 0x9c, 0x1a, 0x77, 0x42, 0xfd, 0xca, 0xec, 0x6c, 0x5e, 0x99, 0x13, 0x0d, 0xa3,
	0x48, 0x64, 0x82, 0x1b, 0x41, 0xd1, 0xf9, 0xbf, 0x17, 0xd3, 0xe4, 0x1b, 0x60, 0x37, 0x7c, 0x29,
	0xde, 0xe8, 0xaf, 0x32, 0xae, 0x12, 0xf1, 0x31, 0x4e, 0x8d, 0x61, 0x98, 0xe8, 0xbc, 0x28, 0x85,
	0x31, 0x74, 0xfb, 0x30, 0xaa, 0xe9, 0x89, 0x80, 0xc3, 0xe6, 0x71, 0x75, 0x57, 0x1c, 0xc3, 0x40,
	0x1b, 0x17, 0x65, 0xef, 0x89, 0x36, 0xe4, 0xe1, 0xcf, 0x61, 0xa7, 0x74, 0x0e, 0x3b, 0x69, 0xbb,
	0x99, 0x83, 0x46, 0x28, 0xa2, 0x51, 0xb9, 0x21, 0x26, 0x2f, 0xe0, 0xf0, 0xba, 0xd4, 0xb7, 0xe2,
	0x0a, 0xdf, 0x84, 0xc8, 0xb9, 0x2e, 0x79, 0xce, 0x3f, 0x6c, 0xf7, 0xe4, 0xaf, 0x6d, 0x08, 0xea,
	0x0d, 0xec, 0xe9, 0xb6, 0x45, 0xef, 0xbd, 0xb3, 0x32, 0xd2, 0x59, 0x4f, 0x83, 0xb4, 0x5d, 0x59,
	0x4f, 0x73, 0xf4, 0x27, 0xb0, 0x2f, 0x4d, 0xbc, 0x10, 0x53, 0x19, 0x9b, 0x45, 0x41, 0x03, 0xaf,
	0xe3, 0xde, 0x77, 0xd2, 0xbc, 0x15, 0x53, 0x79, 0xe3, 0x98, 0x08, 0x73, 0xd2, 0xc4, 0xd9, 0x32,
	0x8f, 0x0b, 0x5e, 0x5a, 0x49, 0xc8, 0xe2, 0x06, 0xc7, 0x9e, 0x34, 0xbf, 0x5d, 0xe6, 0xd7, 0x15,
	0x17, 0x9f, 0x02, 0xd2, 0xc4, 0xa5, 0xe0, 0xa9, 0x56, 0x59, 0x35, 0x41, 0x40, 0x9a, 0xc8, 0x73,
	0xd8, 0x2f, 0xe1, 0xb8, 0x98, 0xaf, 0x8d, 0x4c, 0x78, 0xb6, 0x39, 0xcc, 0xd9, 0xe6, 0xba, 0xff,
	0x51, 0x25, 0xae, 0x0f, 0x25, 0x53, 0x7f, 0x01, 0xc7, 0x34, 0xb2, 0x8c, 0xe5, 0x59, 0x26, 0xd2,
	0xe6, 0x5c, 0x70, 0xb3, 0xe4, 0x10, 0x47, 0x98, 0x97, 0xd6, 0xc3, 0x61, 0xf2, 0x53, 0xd8, 0xf9,
	0xd2, 0xbc, 0x93, 0xf8, 0xdb, 0x40, 0xa1, 0xf8, 0x60, 0x84, 0xbf, 0x83, 0xa3, 0x0b, 0xad, 0x94,
	0x48, 0x6c, 0xb5, 0xa7, 0xea, 0x92, 0xad, 0x3e, 0x6b, 0xfd, 0x60, 0x9f, 0xb1, 0x17, 0x30, 0xe2,
	0x49, 0x22, 0x8c, 0xa9, 0xaa, 0x02, 0xe7, 0x35, 0x73, 0x3b, 0x9a, 0xf6, 0x44, 0xe0, 0xd4, 0xa8,
	0x2a, 0x2e, 0xe0, 0xb8, 0xbe, 0xd7, 0xdb, 0x21, 0xfd, 0x13, 0xe5, 0xb4, 0xfa, 0xb1, 0x6a, 0xfd,
	0xcf, 0x93, 0x9c, 0xc2, 0xf9, 0x3f, 0x3a, 0x30, 0x72, 0x58, 0xf5, 0x72, 0x86, 0xa3, 0xe0, 0x37,
	0xd5, 0x24, 0xf1, 0x40, 0xcf, 0x58, 0x13, 0xcf, 0x9c, 0x7b, 0xe3, 0xc7, 0x4d, 0xde, 0xfd, 0x89,
	0xf0, 0x05, 0x0c, 0x2b, 0xc8, 0x62, 0x87, 0x55, 0x91, 0x35, 0x21, 0x6c, 0x3c, 0xf2, 0xe6, 0xe0,
	0x68, 0x41, 0xf5, 0x0a, 0x62, 0x2a, 0xf5, 0x6d, 0xc8, 0xd9, 0x56, 0xbf, 0x84, 0x9d, 0x66, 0xc7,
	0xb1, 0xd0, 0xbf, 0x7f, 0xbe, 0xd7, 0xd4, 0xe3, 0xf1, 0xf7, 0x25, 0xb5, 0x8d, 0xbf, 0x86, 0xbd,
	0xed, 0x86, 0x62, 0x5e, 0xfb, 0x7d, 0x6d, 0x36, 0xf6, 0x33, 0x60, 0xa3, 0xfc, 0x3b, 0x38, 0xb8,
	0x9f, 0x78, 0xf6, 0xa9, 0x53, 0x7a, 0x7f, 0x41, 0x8c, 0x9f, 0x6c, 0x67, 0xe0, 0x7e, 0xbe, 0x5e,
	0xc2, 0xc3, 0x4b, 0x69, 0x92, 0xfb, 0x67, 0x7e, 0x78, 0xd7, 0x56, 0x60, 0x6e, 0xfb, 0xf4, 0xcf,
	0xff, 0xe2, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x65, 0xaf, 0xd2, 0x21, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeployAgentClient is the client API for DeployAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployAgentClient interface {
	DeployGuestFs(ctx context.Context, in *DeployParams, opts ...grpc.CallOption) (*DeployGuestFsResponse, error)
	ResizeFs(ctx context.Context, in *ResizeFsParams, opts ...grpc.CallOption) (*Empty, error)
	FormatFs(ctx context.Context, in *FormatFsParams, opts ...grpc.CallOption) (*Empty, error)
	SaveToGlance(ctx context.Context, in *SaveToGlanceParams, opts ...grpc.CallOption) (*SaveToGlanceResponse, error)
	ProbeImageInfo(ctx context.Context, in *ProbeImageInfoPramas, opts ...grpc.CallOption) (*ImageInfo, error)
	ConnectEsxiDisks(ctx context.Context, in *ConnectEsxiDisksParams, opts ...grpc.CallOption) (*EsxiDisksConnectionInfo, error)
	DisconnectEsxiDisks(ctx context.Context, in *EsxiDisksConnectionInfo, opts ...grpc.CallOption) (*Empty, error)
}

type deployAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployAgentClient(cc grpc.ClientConnInterface) DeployAgentClient {
	return &deployAgentClient{cc}
}

func (c *deployAgentClient) DeployGuestFs(ctx context.Context, in *DeployParams, opts ...grpc.CallOption) (*DeployGuestFsResponse, error) {
	out := new(DeployGuestFsResponse)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/DeployGuestFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) ResizeFs(ctx context.Context, in *ResizeFsParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/ResizeFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) FormatFs(ctx context.Context, in *FormatFsParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/FormatFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) SaveToGlance(ctx context.Context, in *SaveToGlanceParams, opts ...grpc.CallOption) (*SaveToGlanceResponse, error) {
	out := new(SaveToGlanceResponse)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/SaveToGlance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) ProbeImageInfo(ctx context.Context, in *ProbeImageInfoPramas, opts ...grpc.CallOption) (*ImageInfo, error) {
	out := new(ImageInfo)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/ProbeImageInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) ConnectEsxiDisks(ctx context.Context, in *ConnectEsxiDisksParams, opts ...grpc.CallOption) (*EsxiDisksConnectionInfo, error) {
	out := new(EsxiDisksConnectionInfo)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/ConnectEsxiDisks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployAgentClient) DisconnectEsxiDisks(ctx context.Context, in *EsxiDisksConnectionInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.DeployAgent/DisconnectEsxiDisks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployAgentServer is the server API for DeployAgent service.
type DeployAgentServer interface {
	DeployGuestFs(context.Context, *DeployParams) (*DeployGuestFsResponse, error)
	ResizeFs(context.Context, *ResizeFsParams) (*Empty, error)
	FormatFs(context.Context, *FormatFsParams) (*Empty, error)
	SaveToGlance(context.Context, *SaveToGlanceParams) (*SaveToGlanceResponse, error)
	ProbeImageInfo(context.Context, *ProbeImageInfoPramas) (*ImageInfo, error)
	ConnectEsxiDisks(context.Context, *ConnectEsxiDisksParams) (*EsxiDisksConnectionInfo, error)
	DisconnectEsxiDisks(context.Context, *EsxiDisksConnectionInfo) (*Empty, error)
}

// UnimplementedDeployAgentServer can be embedded to have forward compatible implementations.
type UnimplementedDeployAgentServer struct {
}

func (*UnimplementedDeployAgentServer) DeployGuestFs(ctx context.Context, req *DeployParams) (*DeployGuestFsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployGuestFs not implemented")
}
func (*UnimplementedDeployAgentServer) ResizeFs(ctx context.Context, req *ResizeFsParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeFs not implemented")
}
func (*UnimplementedDeployAgentServer) FormatFs(ctx context.Context, req *FormatFsParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FormatFs not implemented")
}
func (*UnimplementedDeployAgentServer) SaveToGlance(ctx context.Context, req *SaveToGlanceParams) (*SaveToGlanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveToGlance not implemented")
}
func (*UnimplementedDeployAgentServer) ProbeImageInfo(ctx context.Context, req *ProbeImageInfoPramas) (*ImageInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProbeImageInfo not implemented")
}
func (*UnimplementedDeployAgentServer) ConnectEsxiDisks(ctx context.Context, req *ConnectEsxiDisksParams) (*EsxiDisksConnectionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectEsxiDisks not implemented")
}
func (*UnimplementedDeployAgentServer) DisconnectEsxiDisks(ctx context.Context, req *EsxiDisksConnectionInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectEsxiDisks not implemented")
}

func RegisterDeployAgentServer(s *grpc.Server, srv DeployAgentServer) {
	s.RegisterService(&_DeployAgent_serviceDesc, srv)
}

func _DeployAgent_DeployGuestFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).DeployGuestFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/DeployGuestFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).DeployGuestFs(ctx, req.(*DeployParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_ResizeFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeFsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).ResizeFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/ResizeFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).ResizeFs(ctx, req.(*ResizeFsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_FormatFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormatFsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).FormatFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/FormatFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).FormatFs(ctx, req.(*FormatFsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_SaveToGlance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveToGlanceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).SaveToGlance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/SaveToGlance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).SaveToGlance(ctx, req.(*SaveToGlanceParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_ProbeImageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeImageInfoPramas)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).ProbeImageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/ProbeImageInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).ProbeImageInfo(ctx, req.(*ProbeImageInfoPramas))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_ConnectEsxiDisks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectEsxiDisksParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).ConnectEsxiDisks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/ConnectEsxiDisks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).ConnectEsxiDisks(ctx, req.(*ConnectEsxiDisksParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployAgent_DisconnectEsxiDisks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EsxiDisksConnectionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAgentServer).DisconnectEsxiDisks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.DeployAgent/DisconnectEsxiDisks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAgentServer).DisconnectEsxiDisks(ctx, req.(*EsxiDisksConnectionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.DeployAgent",
	HandlerType: (*DeployAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployGuestFs",
			Handler:    _DeployAgent_DeployGuestFs_Handler,
		},
		{
			MethodName: "ResizeFs",
			Handler:    _DeployAgent_ResizeFs_Handler,
		},
		{
			MethodName: "FormatFs",
			Handler:    _DeployAgent_FormatFs_Handler,
		},
		{
			MethodName: "SaveToGlance",
			Handler:    _DeployAgent_SaveToGlance_Handler,
		},
		{
			MethodName: "ProbeImageInfo",
			Handler:    _DeployAgent_ProbeImageInfo_Handler,
		},
		{
			MethodName: "ConnectEsxiDisks",
			Handler:    _DeployAgent_ConnectEsxiDisks_Handler,
		},
		{
			MethodName: "DisconnectEsxiDisks",
			Handler:    _DeployAgent_DisconnectEsxiDisks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/hostman/hostdeployer/apis/deploy.proto",
}
