get:
  summary: 获取指定RDS实例数据库详情信息
  parameters:
    - $ref: '../parameters/dbinstance.yaml#/databaseId'
  responses:
    200:
      description: RDS实例数据库信息
      schema:
        $ref: '../schemas/dbinstance_database.yaml#/DBInstanceDatabaseResponse'
  tags:
    - dbinstancedatabase

delete:
  summary: 删除指定RDS实例数据库
  parameters:
    - $ref: '../parameters/dbinstance.yaml#/databaseId'
  responses:
    200:
      description: 被删除RDS实例的数据库信息
      schema:
        $ref: '../schemas/dbinstance_database.yaml#/DBInstanceDatabaseResponse'
  tags:
    - dbinstancedatabase
