// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by model-api-gen. DO NOT EDIT.

package cloudprovider

// DefaultAction is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.DefaultAction.
type DefaultAction struct {
	// Allow, Block, Log, Count, Alert, Detection, Prevention
	Action string `json:"action"`
	// 仅Action为Allow时生效
	InsertHeaders map[string]string `json:"insert_headers"`
	// 仅Action为Block时生效
	Response string `json:"response"`
	// 仅Action为Block时生效
	ResponseCode *int `json:"response_code"`
	// 仅Action为Block时生效
	ResponseHeaders map[string]string `json:"response_headers"`
}

// SExcludeRule is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.SExcludeRule.
type SExcludeRule struct {
	Name string `json:"name"`
}

// SExcludeRules is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.SExcludeRules.
type SExcludeRules []SExcludeRule

// SGeographicInfo is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.SGeographicInfo.
type SGeographicInfo struct {
	// 纬度
	// example: 26.647003
	Latitude float32 `json:"latitude"`
	// 经度
	// example: 106.630211
	Longitude float32 `json:"longitude"`
	// 城市
	// example: Guiyang
	City string `json:"city"`
	// 国家代码
	// example: CN
	CountryCode string `json:"country_code"`
}

// SWafStatement is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.SWafStatement.
type SWafStatement struct {
	// 管理规则组名称
	ManagedRuleGroupName string `json:"managed_rule_group_name"`
	// 不包含的规则列表
	ExcludeRules *SExcludeRules `json:"exclude_rules"`
	// 表达式类别
	// enmu: ByteMatch, GeoMatch, IPSet, LabelMatch, ManagedRuleGroup, Rate, RegexSet, RuleGroup, Size, SqliMatch, XssMatch
	Type string `json:"type"`
	// 是否取反操作, 仅对Azure生效
	Negation bool `json:"negation"`
	// 操作类型
	// enum: EQ, NE, LE, LT, GE, GT
	Operator string `json:"operator"`
	// 匹配字段
	// enmu: Body, JsonBody, Query, Method, Header, UriPath, PostArgs, Cookie
	MatchField string `json:"match_field"`
	// 匹配字段的key
	MatchFieldKey string `json:"match_field_key"`
	// 匹配字段的值列表
	MatchFieldValues *TWafMatchFieldValues `json:"match_field_values"`
	// 进行转换操作
	// enmu: CompressWithSpace, HtmlEntityDecode, Lowercase, CmdLine, UrlDecode, Trim, UrlEncode, RemoveNulls
	Transformations   *TextTransformations `json:"transformations"`
	ForwardedIPHeader string               `json:"forwarded_ip_header"`
	// 搜索字段, 仅Aws有用
	SearchString string `json:"search_string"`
	IPSetId      string `json:"ip_set_id"`
	// 正则表达式Id, 目前只读
	RegexSetId string `json:"regex_set_id"`
	// 自定义规则组Id, 目前只读
	RuleGroupId string `json:"rule_group_id"`
}

// TWafAction is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TWafAction.
type TWafAction string

// TWafMatchField is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TWafMatchField.
type TWafMatchField string

// TWafMatchFieldValues is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TWafMatchFieldValues.
type TWafMatchFieldValues []string

// TWafOperator is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TWafOperator.
type TWafOperator string

// TWafStatementType is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TWafStatementType.
type TWafStatementType string

// TWafTextTransformation is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TWafTextTransformation.
type TWafTextTransformation string

// TextTransformations is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.TextTransformations.
type TextTransformations []TWafTextTransformation

// WafAddresses is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.WafAddresses.
type WafAddresses []string

// WafRegexPatterns is an autogenerated struct via yunion.io/x/onecloud/pkg/cloudprovider.WafRegexPatterns.
type WafRegexPatterns []string
