// Copyright 2019 Yunion
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package compute

const (
	DIRECT_PCI_TYPE = "PCI"
	GPU_TYPE        = "GPU"
	USB_TYPE        = "USB"
	NIC_TYPE        = "NIC"     // nic sriov
	NVME_PT_TYPE    = "NVME-PT" // nvme passthrough
	NETINT_TYPE     = "NETINT"
	NPU_TYPE        = "NPU"
	BINDER_TYPE     = "BINDER"
)

var VALID_TYPES = []string{DIRECT_PCI_TYPE, GPU_TYPE, USB_TYPE, NIC_TYPE, NVME_PT_TYPE, NETINT_TYPE, NPU_TYPE, BINDER_TYPE}

const (
	DEVICE_SHARING_MODE_EXCLUSIVE = "EXCLUSIVE"
	DEVICE_SHARING_MODE_SRIOV     = "SRIOV"
	DEVICE_SHARING_MODE_MPS       = "MPS"
	DEVICE_SHARING_MODE_HAMI      = "HAMI"
	DEVICE_SHARING_MODE_UNLIMITED = "UNLIMITED"
	DEVICE_SHARING_MODE_MDEV      = "MDEV"
)

var VIRTUAL_SHARING_MODES = []string{DEVICE_SHARING_MODE_HAMI, DEVICE_SHARING_MODE_UNLIMITED, DEVICE_SHARING_MODE_MPS}
var VAILD_SHARING_MODES = []string{DEVICE_SHARING_MODE_EXCLUSIVE, DEVICE_SHARING_MODE_SRIOV, DEVICE_SHARING_MODE_MDEV, DEVICE_SHARING_MODE_HAMI, DEVICE_SHARING_MODE_UNLIMITED, DEVICE_SHARING_MODE_MPS}

const (
	GPU_HPC = "HPC"
	GPU_VGA = "VGA"
)

const (
	NVIDIA_VENDOR_ID     = "10de"
	AMD_VENDOR_ID        = "1002"
	VASTAITECH_VENDOR_ID = "1ec6"
)

var ID_VENDOR_MAP = map[string]string{
	NVIDIA_VENDOR_ID:     "NVIDIA",
	AMD_VENDOR_ID:        "AMD",
	VASTAITECH_VENDOR_ID: "VASTAITECH",
}

var VENDOR_ID_MAP = map[string]string{
	"NVIDIA": NVIDIA_VENDOR_ID,
	"AMD":    AMD_VENDOR_ID,
}

const (
	ISOLATED_DEVICE_MODEL_METADATA_BANDWIDTH = "bandwidth"
	ISOLATED_DEVICE_MODEL_METADATA_MEMORY_MB = "memory_mb"
	ISOLATED_DEVICE_MODEL_METADATA_TFLOPS    = "tflops"
)

////////////// deprecated

const (
	GPU_HPC_TYPE     = "GPU-HPC"     // # for compute
	GPU_VGA_TYPE     = "GPU-VGA"     // # for display
	SRIOV_VGPU_TYPE  = "SRIOV-VGPU"  //done
	LEGACY_VGPU_TYPE = "LEGACY-VGPU" //done
)

var VALID_GPU_TYPES = []string{GPU_HPC_TYPE, GPU_VGA_TYPE}                                                 //done
var VALID_ATTACH_TYPES = []string{GPU_HPC_TYPE, GPU_VGA_TYPE, USB_TYPE, SRIOV_VGPU_TYPE, LEGACY_VGPU_TYPE} //done

var GPU_TYPES = []string{
	GPU_HPC_TYPE, GPU_VGA_TYPE, SRIOV_VGPU_TYPE, LEGACY_VGPU_TYPE,
	CONTAINER_DEV_CPH_AMD_GPU, CONTAINER_DEV_NVIDIA_GPU, CONTAINER_DEV_NVIDIA_MPS, CONTAINER_DEV_NVIDIA_GPU_SHARE,
	CONTAINER_DEV_NVIDIA_HAMI, CONTAINER_DEV_VASTAITECH_GPU,
}

var NETINT_TYPES = []string{
	CONTAINER_DEV_NETINT_CA_QUADRA, CONTAINER_DEV_NETINT_CA_ASIC,
}

var VALID_CONTAINER_DEVICE_TYPES = []string{
	CONTAINER_DEV_CPH_AMD_GPU, CONTAINER_DEV_CPH_AOSP_BINDER, CONTAINER_DEV_NETINT_CA_QUADRA,
	CONTAINER_DEV_NETINT_CA_ASIC, CONTAINER_DEV_NVIDIA_GPU, CONTAINER_DEV_NVIDIA_MPS, CONTAINER_DEV_NVIDIA_GPU_SHARE, CONTAINER_DEV_NVIDIA_HAMI,
	CONTAINER_DEV_ASCEND_NPU, CONTAINER_DEV_VASTAITECH_GPU,
}

var VALID_PASSTHROUGH_TYPES = []string{
	DIRECT_PCI_TYPE, USB_TYPE, NIC_TYPE, GPU_HPC_TYPE,
	GPU_VGA_TYPE, NVME_PT_TYPE, SRIOV_VGPU_TYPE, LEGACY_VGPU_TYPE,
}

var VITRUAL_DEVICE_TYPES = []string{
	LEGACY_VGPU_TYPE,
	CONTAINER_DEV_CPH_AMD_GPU,
	CONTAINER_DEV_CPH_AOSP_BINDER,
	CONTAINER_DEV_NETINT_CA_QUADRA,
	CONTAINER_DEV_NETINT_CA_ASIC,
	CONTAINER_DEV_NVIDIA_MPS,
	CONTAINER_DEV_NVIDIA_HAMI,
	CONTAINER_DEV_ASCEND_NPU,
	CONTAINER_DEV_NVIDIA_GPU_SHARE,
	CONTAINER_DEV_VASTAITECH_GPU,
}

func init() {
	VALID_PASSTHROUGH_TYPES = append(VALID_PASSTHROUGH_TYPES, VALID_CONTAINER_DEVICE_TYPES...)
	VALID_ATTACH_TYPES = append(VALID_ATTACH_TYPES, VALID_CONTAINER_DEVICE_TYPES...)
}
