// Copyright 2019 Yunion
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package compute

import "yunion.io/x/cloudmux/pkg/apis/compute"

const (
	NETWORK_INTERFACE_ASSOCIATE_TYPE_SERVER       = compute.NETWORK_INTERFACE_ASSOCIATE_TYPE_SERVER
	NETWORK_INTERFACE_ASSOCIATE_TYPE_RESERVED     = compute.NETWORK_INTERFACE_ASSOCIATE_TYPE_RESERVED
	NETWORK_INTERFACE_ASSOCIATE_TYPE_LOADBALANCER = compute.NETWORK_INTERFACE_ASSOCIATE_TYPE_LOADBALANCER
	NETWORK_INTERFACE_ASSOCIATE_TYPE_VIP          = compute.NETWORK_INTERFACE_ASSOCIATE_TYPE_VIP
	NETWORK_INTERFACE_ASSOCIATE_TYPE_DHCP         = compute.NETWORK_INTERFACE_ASSOCIATE_TYPE_DHCP

	NETWORK_INTERFACE_STATUS_INIT      = "init"
	NETWORK_INTERFACE_STATUS_CREATING  = compute.NETWORK_INTERFACE_STATUS_CREATING
	NETWORK_INTERFACE_STATUS_AVAILABLE = compute.NETWORK_INTERFACE_STATUS_AVAILABLE
	NETWORK_INTERFACE_STATUS_DISABLED  = compute.NETWORK_INTERFACE_STATUS_DISABLED
	NETWORK_INTERFACE_STATUS_ATTACHING = compute.NETWORK_INTERFACE_STATUS_ATTACHING
	NETWORK_INTERFACE_STATUS_DETACHING = compute.NETWORK_INTERFACE_STATUS_DETACHING
	NETWORK_INTERFACE_STATUS_DELETING  = compute.NETWORK_INTERFACE_STATUS_DELETING
	NETWORK_INTERFACE_STATUS_UNKNOWN   = compute.NETWORK_INTERFACE_STATUS_UNKNOWN
)
