// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by model-api-gen. DO NOT EDIT.

package compute

import (
	time "time"

	jsonutils "yunion.io/x/jsonutils"

	"yunion.io/x/onecloud/pkg/apis"
	"yunion.io/x/onecloud/pkg/apis/cloudprovider"
)

// SAwsCachedLb is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SAwsCachedLb.
type SAwsCachedLb struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	BackendServerId      string `json:"backend_server_id"`
	BackendId            string `json:"backend_id"`
	CachedBackendGroupId string `json:"cached_backend_group_id"`
}

// SAwsCachedLbbg is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SAwsCachedLbbg.
type SAwsCachedLbbg struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	LoadbalancerId      string `json:"loadbalancer_id"`
	BackendGroupId      string `json:"backend_group_id"`
	TargetType          string `json:"target_type"`
	ProtocolType        string `json:"protocol_type"`
	Port                int    `json:"port"`
	HealthCheckProtocol string `json:"health_check_protocol"`
	HealthCheckInterval int    `json:"health_check_interval"`
}

// SBaremetalagent is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SBaremetalagent.
type SBaremetalagent struct {
	apis.SStandaloneResourceBase
	Status         string `json:"status"`
	AccessIp       string `json:"access_ip"`
	ManagerUri     string `json:"manager_uri"`
	ZoneId         string `json:"zone_id"`
	AgentType      string `json:"agent_type"`
	Version        string `json:"version"`
	StoragecacheId string `json:"storagecache_id"`
}

// SBillingResourceBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SBillingResourceBase.
type SBillingResourceBase struct {
	BillingType  string    `json:"billing_type"`
	ExpiredAt    time.Time `json:"expired_at"`
	BillingCycle string    `json:"billing_cycle"`
}

// SBucket is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SBucket.
type SBucket struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	CloudregionId  string               `json:"cloudregion_id"`
	StorageClass   string               `json:"storage_class"`
	Location       string               `json:"location"`
	Acl            string               `json:"acl"`
	SizeBytes      int64                `json:"size_bytes"`
	ObjectCnt      int                  `json:"object_cnt"`
	SizeBytesLimit int64                `json:"size_bytes_limit"`
	ObjectCntLimit int                  `json:"object_cnt_limit"`
	AccessUrls     jsonutils.JSONObject `json:"access_urls"`
}

// SCachedLoadbalancerAcl is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCachedLoadbalancerAcl.
type SCachedLoadbalancerAcl struct {
	apis.SSharableVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	AclId      string `json:"acl_id"`
	ListenerId string `json:"listener_id"`
}

// SCachedLoadbalancerCertificate is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCachedLoadbalancerCertificate.
type SCachedLoadbalancerCertificate struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	CertificateId string `json:"certificate_id"`
}

// SCachedimage is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCachedimage.
type SCachedimage struct {
	apis.SStandaloneResourceBase
	apis.SExternalizedResourceBase
	Size      int64                `json:"size"`
	Info      jsonutils.JSONObject `json:"info"`
	LastSync  time.Time            `json:"last_sync"`
	LastRef   time.Time            `json:"last_ref"`
	RefCount  int                  `json:"ref_count"`
	ImageType string               `json:"image_type"`
}

// SCloudaccount is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCloudaccount.
type SCloudaccount struct {
	apis.SEnabledStatusStandaloneResourceBase
	apis.SDomainizedResourceBase
	SSyncableBaseResource
	LastAutoSync        time.Time            `json:"last_auto_sync"`
	ProjectId           string               `json:"project_id"`
	AccessUrl           string               `json:"access_url"`
	Account             string               `json:"account"`
	Secret              string               `json:"secret"`
	AccountId           string               `json:"account_id"`
	IsPublicCloud       *bool                `json:"is_public_cloud,omitempty"`
	IsOnPremise         bool                 `json:"is_on_premise"`
	HasObjectStorage    bool                 `json:"has_object_storage"`
	Provider            string               `json:"provider"`
	EnableAutoSync      bool                 `json:"enable_auto_sync"`
	SyncIntervalSeconds int                  `json:"sync_interval_seconds"`
	Balance             float64              `json:"balance"`
	ProbeAt             time.Time            `json:"probe_at"`
	HealthStatus        string               `json:"health_status"`
	ErrorCount          int                  `json:"error_count"`
	AutoCreateProject   bool                 `json:"auto_create_project"`
	Version             string               `json:"version"`
	Sysinfo             jsonutils.JSONObject `json:"sysinfo"`
	Brand               string               `json:"brand"`
	Options             *jsonutils.JSONDict  `json:"options"`
	IsPublic            bool                 `json:"is_public"`
	ShareMode           string               `json:"share_mode"`
}

// SCloudprovider is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCloudprovider.
type SCloudprovider struct {
	apis.SEnabledStatusStandaloneResourceBase
	apis.SProjectizedResourceBase
	SSyncableBaseResource
	HealthStatus   string `json:"health_status"`
	AccessUrl      string `json:"access_url"`
	Account        string `json:"account"`
	Secret         string `json:"secret"`
	CloudaccountId string `json:"cloudaccount_id"`
	Provider       string `json:"provider"`
}

// SCloudproviderregion is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCloudproviderregion.
type SCloudproviderregion struct {
	apis.SJointResourceBase
	SSyncableBaseResource
	CloudproviderId string               `json:"cloudprovider_id"`
	CloudregionId   string               `json:"cloudregion_id"`
	Enabled         bool                 `json:"enabled"`
	SyncResults     jsonutils.JSONObject `json:"sync_results"`
	LastDeepSyncAt  time.Time            `json:"last_deep_sync_at"`
}

// SCloudregion is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCloudregion.
type SCloudregion struct {
	apis.SEnabledStatusStandaloneResourceBase
	SManagedResourceBase
	apis.SExternalizedResourceBase
	cloudprovider.SGeographicInfo
	Provider string `json:"provider"`
}

// SCloudregionResourceBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SCloudregionResourceBase.
type SCloudregionResourceBase struct {
	CloudregionId string `json:"cloudregion_id"`
}

// SDBInstance is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstance.
type SDBInstance struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SBillingResourceBase
	SCloudregionResourceBase
	SDeletePreventableResourceBase
	MasterInstanceId      string `json:"master_instance_id"`
	VcpuCount             int    `json:"vcpu_count"`
	VmemSizeMb            int    `json:"vmem_size_mb"`
	StorageType           string `json:"storage_type"`
	DiskSizeGB            int    `json:"disk_size_gb"`
	Port                  int    `json:"port"`
	Category              string `json:"category"`
	Engine                string `json:"engine"`
	EngineVersion         string `json:"engine_version"`
	InstanceType          string `json:"instance_type"`
	MaintainTime          string `json:"maintain_time"`
	SecgroupId            string `json:"secgroup_id"`
	VpcId                 string `json:"vpc_id"`
	ConnectionStr         string `json:"connection_str"`
	InternalConnectionStr string `json:"internal_connection_str"`
	Zone1                 string `json:"zone1"`
	Zone2                 string `json:"zone2"`
	Zone3                 string `json:"zone3"`
	ZoneId                string `json:"zone_id"`
}

// SDBInstanceAccount is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceAccount.
type SDBInstanceAccount struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	Secret       string `json:"secret"`
	DBInstanceId string `json:"db_instance_id"`
}

// SDBInstanceBackup is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceBackup.
type SDBInstanceBackup struct {
	apis.SVirtualResourceBase
	SCloudregionResourceBase
	SManagedResourceBase
	apis.SExternalizedResourceBase
	Engine        string    `json:"engine"`
	EngineVersion string    `json:"engine_version"`
	StartTime     time.Time `json:"start_time"`
	EndTime       time.Time `json:"end_time"`
	BackupMode    string    `json:"backup_mode"`
	DBNames       string    `json:"db_names"`
	BackupSizeMb  int       `json:"backup_size_mb"`
	DBInstanceId  string    `json:"db_instance_id"`
}

// SDBInstanceDatabase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceDatabase.
type SDBInstanceDatabase struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	CharacterSet string `json:"character_set"`
	DBInstanceId string `json:"db_instance_id"`
}

// SDBInstanceJointsBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceJointsBase.
type SDBInstanceJointsBase struct {
	apis.SVirtualJointResourceBase
	DBInstanceId string `json:"db_instance_id"`
}

// SDBInstanceNetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceNetwork.
type SDBInstanceNetwork struct {
	SDBInstanceJointsBase
	NetworkId string `json:"network_id"`
	IpAddr    string `json:"ip_addr"`
}

// SDBInstanceParameter is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceParameter.
type SDBInstanceParameter struct {
	apis.SStandaloneResourceBase
	apis.SExternalizedResourceBase
	DBInstanceId string `json:"db_instance_id"`
	Key          string `json:"key"`
	Value        string `json:"value"`
}

// SDBInstancePrivilege is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstancePrivilege.
type SDBInstancePrivilege struct {
	apis.SResourceBase
	apis.SExternalizedResourceBase
	Id                   string `json:"id"`
	Privilege            string `json:"privilege"`
	DBInstanceaccountId  string `json:"db_instanceaccount_id"`
	DBInstancedatabaseId string `json:"db_instancedatabase_id"`
}

// SDBInstanceSku is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDBInstanceSku.
type SDBInstanceSku struct {
	apis.SEnabledStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SCloudregionResourceBase
	Provider       string `json:"provider"`
	StorageType    string `json:"storage_type"`
	DiskSizeStep   int    `json:"disk_size_step"`
	MaxDiskSizeGb  int    `json:"max_disk_size_gb"`
	MinDiskSizeGb  int    `json:"min_disk_size_gb"`
	IOPS           int    `json:"iops"`
	TPS            int    `json:"tps"`
	QPS            int    `json:"qps"`
	MaxConnections int    `json:"max_connections"`
	VcpuCount      int    `json:"vcpu_count"`
	VmemSizeMb     int    `json:"vmem_size_mb"`
	Category       string `json:"category"`
	Engine         string `json:"engine"`
	EngineVersion  string `json:"engine_version"`
	Zone1          string `json:"zone1"`
	Zone2          string `json:"zone2"`
	Zone3          string `json:"zone3"`
	ZoneId         string `json:"zone_id"`
}

// SDeletePreventableResourceBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDeletePreventableResourceBase.
type SDeletePreventableResourceBase struct {
	DisableDelete *bool `json:"disable_delete,omitempty"`
}

// SDisk is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDisk.
type SDisk struct {
	apis.SSharableVirtualResourceBase
	apis.SExternalizedResourceBase
	SBillingResourceBase
	DiskFormat      string `json:"disk_format"`
	DiskSize        int    `json:"disk_size"`
	AccessPath      string `json:"access_path"`
	AutoDelete      bool   `json:"auto_delete"`
	StorageId       string `json:"storage_id"`
	BackupStorageId string `json:"backup_storage_id"`
	TemplateId      string `json:"template_id"`
	SnapshotId      string `json:"snapshot_id"`
	FsFormat        string `json:"fs_format"`
	DiskType        string `json:"disk_type"`
	Nonpersistent   bool   `json:"nonpersistent"`
}

// SDnsRecord is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDnsRecord.
type SDnsRecord struct {
	apis.SAdminSharableVirtualResourceBase
	Ttl     int   `json:"ttl"`
	Enabled *bool `json:"enabled,omitempty"`
}

// SDynamicschedtag is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SDynamicschedtag.
type SDynamicschedtag struct {
	apis.SStandaloneResourceBase
	Condition  string `json:"condition"`
	SchedtagId string `json:"schedtag_id"`
	Enabled    *bool  `json:"enabled,omitempty"`
}

// SElasticcache is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticcache.
type SElasticcache struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SBillingResourceBase
	SManagedResourceBase
	SDeletePreventableResourceBase
	SCloudregionResourceBase
	SZoneResourceBase
	SlaveZones         string `json:"slave_zones"`
	InstanceType       string `json:"instance_type"`
	CapacityMB         int    `json:"capacity_mb"`
	LocalCategory      string `json:"local_category"`
	NodeType           string `json:"node_type"`
	Engine             string `json:"engine"`
	EngineVersion      string `json:"engine_version"`
	VpcId              string `json:"vpc_id"`
	NetworkType        string `json:"network_type"`
	NetworkId          string `json:"network_id"`
	SecurityGroupId    string `json:"security_group_id"`
	PrivateDNS         string `json:"private_dns"`
	PrivateIpAddr      string `json:"private_ip_addr"`
	PrivateConnectPort int    `json:"private_connect_port"`
	PublicDNS          string `json:"public_dns"`
	PublicIpAddr       string `json:"public_ip_addr"`
	PublicConnectPort  int    `json:"public_connect_port"`
	MaintainStartTime  string `json:"maintain_start_time"`
	MaintainEndTime    string `json:"maintain_end_time"`
	AuthMode           string `json:"auth_mode"`
}

// SElasticcacheAccount is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticcacheAccount.
type SElasticcacheAccount struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	ElasticcacheId   string `json:"elasticcache_id"`
	AccountType      string `json:"account_type"`
	AccountPrivilege string `json:"account_privilege"`
	Password         string `json:"password"`
}

// SElasticcacheAcl is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticcacheAcl.
type SElasticcacheAcl struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	ElasticcacheId string `json:"elasticcache_id"`
	IpList         string `json:"ip_list"`
}

// SElasticcacheBackup is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticcacheBackup.
type SElasticcacheBackup struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	ElasticcacheId string    `json:"elasticcache_id"`
	BackupSizeMb   int       `json:"backup_size_mb"`
	BackupType     string    `json:"backup_type"`
	BackupMode     string    `json:"backup_mode"`
	DownloadURL    string    `json:"download_url"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
}

// SElasticcacheParameter is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticcacheParameter.
type SElasticcacheParameter struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	ElasticcacheId string `json:"elasticcache_id"`
	Key            string `json:"key"`
	Value          string `json:"value"`
	ValueRange     string `json:"value_range"`
	Modifiable     bool   `json:"modifiable"`
	ForceRestart   bool   `json:"force_restart"`
}

// SElasticcacheSku is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticcacheSku.
type SElasticcacheSku struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SCloudregionResourceBase
	SZoneResourceBase
	SlaveZoneId      string `json:"slave_zone_id"`
	InstanceSpec     string `json:"instance_spec"`
	EngineArch       string `json:"engine_arch"`
	LocalCategory    string `json:"local_category"`
	PrepaidStatus    string `json:"prepaid_status"`
	PostpaidStatus   string `json:"postpaid_status"`
	Engine           string `json:"engine"`
	EngineVersion    string `json:"engine_version"`
	CpuArch          string `json:"cpu_arch"`
	StorageType      string `json:"storage_type"`
	PerformanceType  string `json:"performance_type"`
	NodeType         string `json:"node_type"`
	MemorySizeMB     int    `json:"memory_size_mb"`
	DiskSizeGB       int    `json:"disk_size_gb"`
	ShardNum         int    `json:"shard_num"`
	MaxShardNum      int    `json:"max_shard_num"`
	ReplicasNum      int    `json:"replicas_num"`
	MaxReplicasNum   int    `json:"max_replicas_num"`
	MaxClients       int    `json:"max_clients"`
	MaxConnections   int    `json:"max_connections"`
	MaxInBandwidthMb int    `json:"max_in_bandwidth_mb"`
	MaxMemoryMB      int    `json:"max_memory_mb"`
	QPS              int    `json:"qps"`
	Provider         string `json:"provider"`
}

// SElasticip is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SElasticip.
type SElasticip struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SBillingResourceBase
	NetworkId     string `json:"network_id"`
	Mode          string `json:"mode"`
	IpAddr        string `json:"ip_addr"`
	AssociateType string `json:"associate_type"`
	AssociateId   string `json:"associate_id"`
	Bandwidth     int    `json:"bandwidth"`
	ChargeType    string `json:"charge_type"`
	BgpType       string `json:"bgp_type"`
	AutoDellocate *bool  `json:"auto_dellocate,omitempty"`
	CloudregionId string `json:"cloudregion_id"`
}

// SExternalProject is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SExternalProject.
type SExternalProject struct {
	apis.SStandaloneResourceBase
	SManagedResourceBase
	apis.SProjectizedResourceBase
	apis.SExternalizedResourceBase
}

// SGlobalNetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGlobalNetwork.
type SGlobalNetwork struct {
	apis.SEnabledStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	Provider string `json:"provider"`
}

// SGlobalnetworkVpc is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGlobalnetworkVpc.
type SGlobalnetworkVpc struct {
	apis.SJointResourceBase
	GlobalnetworkId string `json:"globalnetwork_id"`
	VpcId           string `json:"vpc_id"`
}

// SGroup is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGroup.
type SGroup struct {
	apis.SVirtualResourceBase
	ServiceType     string `json:"service_type"`
	ParentId        string `json:"parent_id"`
	ZoneId          string `json:"zone_id"`
	SchedStrategy   string `json:"sched_strategy"`
	Granularity     int    `json:"granularity"`
	ForceDispersion *bool  `json:"force_dispersion,omitempty"`
	Enabled         *bool  `json:"enabled,omitempty"`
}

// SGroupJointsBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGroupJointsBase.
type SGroupJointsBase struct {
	apis.SVirtualJointResourceBase
	GroupId string `json:"group_id"`
}

// SGroupguest is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGroupguest.
type SGroupguest struct {
	SGroupJointsBase
	Tag     string `json:"tag"`
	GuestId string `json:"guest_id"`
}

// SGroupnetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGroupnetwork.
type SGroupnetwork struct {
	SGroupJointsBase
	NetworkId string `json:"network_id"`
	IpAddr    string `json:"ip_addr"`
	Index     byte   `json:"index"`
	EipId     string `json:"eip_id"`
}

// SGuest is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGuest.
type SGuest struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SBillingResourceBase
	SDeletePreventableResourceBase
	VcpuCount        int    `json:"vcpu_count"`
	VmemSize         int    `json:"vmem_size"`
	BootOrder        string `json:"boot_order"`
	ShutdownBehavior string `json:"shutdown_behavior"`
	KeypairId        string `json:"keypair_id"`
	HostId           string `json:"host_id"`
	BackupHostId     string `json:"backup_host_id"`
	Vga              string `json:"vga"`
	Vdi              string `json:"vdi"`
	Machine          string `json:"machine"`
	Bios             string `json:"bios"`
	OsType           string `json:"os_type"`
	FlavorId         string `json:"flavor_id"`
	SecgrpId         string `json:"secgrp_id"`
	AdminSecgrpId    string `json:"admin_secgrp_id"`
	Hypervisor       string `json:"hypervisor"`
	InstanceType     string `json:"instance_type"`
}

// SGuestJointsBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGuestJointsBase.
type SGuestJointsBase struct {
	apis.SVirtualJointResourceBase
	GuestId string `json:"guest_id"`
}

// SGuestdisk is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGuestdisk.
type SGuestdisk struct {
	SGuestJointsBase
	DiskId     string `json:"disk_id"`
	ImagePath  string `json:"image_path"`
	Driver     string `json:"driver"`
	CacheMode  string `json:"cache_mode"`
	AioMode    string `json:"aio_mode"`
	Iops       int    `json:"iops"`
	Bps        int    `json:"bps"`
	Mountpoint string `json:"mountpoint"`
	Index      byte   `json:"index"`
}

// SGuestnetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGuestnetwork.
type SGuestnetwork struct {
	SGuestJointsBase
	NetworkId string `json:"network_id"`
	MacAddr   string `json:"mac_addr"`
	IpAddr    string `json:"ip_addr"`
	Ip6Addr   string `json:"ip6_addr"`
	Driver    string `json:"driver"`
	BwLimit   int    `json:"bw_limit"`
	Index     byte   `json:"index"`
	Virtual   bool   `json:"virtual"`
	Ifname    string `json:"ifname"`
	TeamWith  string `json:"team_with"`
}

// SGuestsecgroup is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SGuestsecgroup.
type SGuestsecgroup struct {
	SGuestJointsBase
	SecgroupId string `json:"secgroup_id"`
}

// SHost is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHost.
type SHost struct {
	apis.SEnabledStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SBillingResourceBase
	Rack            string               `json:"rack"`
	Slots           string               `json:"slots"`
	AccessMac       string               `json:"access_mac"`
	AccessIp        string               `json:"access_ip"`
	ManagerUri      string               `json:"manager_uri"`
	SysInfo         jsonutils.JSONObject `json:"sys_info"`
	SN              string               `json:"sn"`
	CpuCount        int                  `json:"cpu_count"`
	NodeCount       byte                 `json:"node_count"`
	CpuDesc         string               `json:"cpu_desc"`
	CpuMhz          int                  `json:"cpu_mhz"`
	CpuCache        int                  `json:"cpu_cache"`
	CpuReserved     int                  `json:"cpu_reserved"`
	CpuCmtbound     float32              `json:"cpu_cmtbound"`
	CpuMicrocode    string               `json:"cpu_microcode"`
	CpuArchitecture string               `json:"cpu_architecture"`
	MemSize         int                  `json:"mem_size"`
	MemReserved     int                  `json:"mem_reserved"`
	MemCmtbound     float32              `json:"mem_cmtbound"`
	StorageSize     int                  `json:"storage_size"`
	StorageType     string               `json:"storage_type"`
	StorageDriver   string               `json:"storage_driver"`
	StorageInfo     jsonutils.JSONObject `json:"storage_info"`
	IpmiIp          string               `json:"ipmi_ip"`
	IpmiInfo        jsonutils.JSONObject `json:"ipmi_info"`
	HostStatus      string               `json:"host_status"`
	ZoneId          string               `json:"zone_id"`
	HostType        string               `json:"host_type"`
	Version         string               `json:"version"`
	IsBaremetal     bool                 `json:"is_baremetal"`
	IsMaintenance   bool                 `json:"is_maintenance"`
	LastPingAt      time.Time            `json:"last_ping_at"`
	ResourceType    string               `json:"resource_type"`
	RealExternalId  string               `json:"real_external_id"`
	IsImport        bool                 `json:"is_import"`
	EnablePxeBoot   *bool                `json:"enable_pxe_boot,omitempty"`
	Uuid            string               `json:"uuid"`
	BootMode        string               `json:"boot_mode"`
}

// SHostJointsBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHostJointsBase.
type SHostJointsBase struct {
	apis.SJointResourceBase
}

// SHostnetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHostnetwork.
type SHostnetwork struct {
	SHostJointsBase
	BaremetalId string `json:"baremetal_id"`
	NetworkId   string `json:"network_id"`
	IpAddr      string `json:"ip_addr"`
	MacAddr     string `json:"mac_addr"`
}

// SHostschedtag is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHostschedtag.
type SHostschedtag struct {
	SSchedtagJointsBase
	HostId string `json:"host_id"`
}

// SHoststorage is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHoststorage.
type SHoststorage struct {
	SHostJointsBase
	MountPoint   string               `json:"mount_point"`
	HostId       string               `json:"host_id"`
	StorageId    string               `json:"storage_id"`
	Config       *jsonutils.JSONArray `json:"config"`
	RealCapacity int64                `json:"real_capacity"`
}

// SHostwire is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHostwire.
type SHostwire struct {
	SHostJointsBase
	Bridge    string `json:"bridge"`
	Interface string `json:"interface"`
	IsMaster  bool   `json:"is_master"`
	MacAddr   string `json:"mac_addr"`
	HostId    string `json:"host_id"`
	WireId    string `json:"wire_id"`
}

// SHuaweiCachedLb is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHuaweiCachedLb.
type SHuaweiCachedLb struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	BackendServerId      string `json:"backend_server_id"`
	BackendId            string `json:"backend_id"`
	CachedBackendGroupId string `json:"cached_backend_group_id"`
}

// SHuaweiCachedLbbg is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SHuaweiCachedLbbg.
type SHuaweiCachedLbbg struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	LoadbalancerId string `json:"loadbalancer_id"`
	BackendGroupId string `json:"backend_group_id"`
	AssociatedId   string `json:"associated_id"`
	AssociatedType string `json:"associated_type"`
	ProtocolType   string `json:"protocol_type"`
}

// SInstanceSnapshot is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SInstanceSnapshot.
type SInstanceSnapshot struct {
	apis.SVirtualResourceBase
	GuestId        string               `json:"guest_id"`
	ServerConfig   jsonutils.JSONObject `json:"server_config"`
	ServerMetadata jsonutils.JSONObject `json:"server_metadata"`
	AutoDelete     bool                 `json:"auto_delete"`
	RefCount       int                  `json:"ref_count"`
	SecGroups      jsonutils.JSONObject `json:"sec_groups"`
	KeypairId      string               `json:"keypair_id"`
	OsType         string               `json:"os_type"`
}

// SInstanceSnapshotJoint is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SInstanceSnapshotJoint.
type SInstanceSnapshotJoint struct {
	apis.SVirtualJointResourceBase
	InstanceSnapshotId string `json:"instance_snapshot_id"`
	SnapshotId         string `json:"snapshot_id"`
	DiskIndex          byte   `json:"disk_index"`
}

// SIsolatedDevice is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SIsolatedDevice.
type SIsolatedDevice struct {
	apis.SStandaloneResourceBase
	HostId         string `json:"host_id"`
	DevType        string `json:"dev_type"`
	Model          string `json:"model"`
	GuestId        string `json:"guest_id"`
	Addr           string `json:"addr"`
	VendorDeviceId string `json:"vendor_device_id"`
}

// SKeypair is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SKeypair.
type SKeypair struct {
	apis.SStandaloneResourceBase
	Scheme      string `json:"scheme"`
	Fingerprint string `json:"fingerprint"`
	PrivateKey  string `json:"private_key"`
	PublicKey   string `json:"public_key"`
	OwnerId     string `json:"owner_id"`
}

// SLoadbalancer is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancer.
type SLoadbalancer struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	SZoneResourceBase
	SLoadbalancerRateLimiter
	Address          string               `json:"address"`
	AddressType      string               `json:"address_type"`
	NetworkType      string               `json:"network_type"`
	NetworkId        string               `json:"network_id"`
	VpcId            string               `json:"vpc_id"`
	ClusterId        string               `json:"cluster_id"`
	ChargeType       string               `json:"charge_type"`
	LoadbalancerSpec string               `json:"loadbalancer_spec"`
	BackendGroupId   string               `json:"backend_group_id"`
	LBInfo           jsonutils.JSONObject `json:"lb_info"`
}

// SLoadbalancerAcl is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAcl.
type SLoadbalancerAcl struct {
	apis.SSharableVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	AclEntries  *SLoadbalancerAclEntries `json:"acl_entries"`
	Fingerprint string                   `json:"fingerprint"`
}

// SLoadbalancerAclEntries is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAclEntries.
type SLoadbalancerAclEntries []*SLoadbalancerAclEntry

// SLoadbalancerAclEntry is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAclEntry.
type SLoadbalancerAclEntry struct {
	Cidr    string `json:"cidr"`
	Comment string `json:"comment"`
}

// SLoadbalancerAgent is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAgent.
type SLoadbalancerAgent struct {
	apis.SStandaloneResourceBase
	Version                   string                        `json:"version"`
	IP                        string                        `json:"ip"`
	HaState                   string                        `json:"ha_state"`
	HbLastSeen                time.Time                     `json:"hb_last_seen"`
	HbTimeout                 int                           `json:"hb_timeout"`
	Params                    *SLoadbalancerAgentParams     `json:"params"`
	Loadbalancers             time.Time                     `json:"loadbalancers"`
	LoadbalancerListeners     time.Time                     `json:"loadbalancer_listeners"`
	LoadbalancerListenerRules time.Time                     `json:"loadbalancer_listener_rules"`
	LoadbalancerBackendGroups time.Time                     `json:"loadbalancer_backend_groups"`
	LoadbalancerBackends      time.Time                     `json:"loadbalancer_backends"`
	LoadbalancerAcls          time.Time                     `json:"loadbalancer_acls"`
	LoadbalancerCertificates  time.Time                     `json:"loadbalancer_certificates"`
	Deployment                *SLoadbalancerAgentDeployment `json:"deployment"`
	ClusterId                 string                        `json:"cluster_id"`
}

// SLoadbalancerAgentDeployment is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAgentDeployment.
type SLoadbalancerAgentDeployment struct {
	Host                        string `json:"host"`
	AnsiblePlaybook             string `json:"ansible_playbook"`
	AnsiblePlaybookUndeployment string `json:"ansible_playbook_undeployment"`
}

// SLoadbalancerAgentParams is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAgentParams.
type SLoadbalancerAgentParams struct {
	KeepalivedConfTmpl string                           `json:"keepalived_conf_tmpl"`
	HaproxyConfTmpl    string                           `json:"haproxy_conf_tmpl"`
	TelegrafConfTmpl   string                           `json:"telegraf_conf_tmpl"`
	Vrrp               SLoadbalancerAgentParamsVrrp     `json:"vrrp"`
	Haproxy            SLoadbalancerAgentParamsHaproxy  `json:"haproxy"`
	Telegraf           SLoadbalancerAgentParamsTelegraf `json:"telegraf"`
}

// SLoadbalancerAgentParamsHaproxy is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAgentParamsHaproxy.
type SLoadbalancerAgentParamsHaproxy struct {
	GlobalLog      string `json:"global_log"`
	GlobalNbthread int    `json:"global_nbthread"`
	LogHttp        bool   `json:"log_http"`
	LogTcp         bool   `json:"log_tcp"`
	LogNormal      bool   `json:"log_normal"`
}

// SLoadbalancerAgentParamsTelegraf is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAgentParamsTelegraf.
type SLoadbalancerAgentParamsTelegraf struct {
	InfluxDbOutputUrl       string `json:"influx_db_output_url"`
	InfluxDbOutputName      string `json:"influx_db_output_name"`
	InfluxDbOutputUnsafeSsl bool   `json:"influx_db_output_unsafe_ssl"`
	HaproxyInputInterval    int    `json:"haproxy_input_interval"`
}

// SLoadbalancerAgentParamsVrrp is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerAgentParamsVrrp.
type SLoadbalancerAgentParamsVrrp struct {
	Priority          int    `json:"priority"`
	VirtualRouterId   int    `json:"virtual_router_id"`
	GarpMasterRefresh int    `json:"garp_master_refresh"`
	Preempt           bool   `json:"preempt"`
	Interface         string `json:"interface"`
	AdvertInt         int    `json:"advert_int"`
	Pass              string `json:"pass"`
}

// SLoadbalancerBackend is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerBackend.
type SLoadbalancerBackend struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	BackendGroupId string `json:"backend_group_id"`
	BackendId      string `json:"backend_id"`
	BackendType    string `json:"backend_type"`
	BackendRole    string `json:"backend_role"`
	Weight         int    `json:"weight"`
	Address        string `json:"address"`
	Port           int    `json:"port"`
	SendProxy      string `json:"send_proxy"`
}

// SLoadbalancerBackendGroup is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerBackendGroup.
type SLoadbalancerBackendGroup struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	Type           string `json:"type"`
	LoadbalancerId string `json:"loadbalancer_id"`
}

// SLoadbalancerCertificate is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerCertificate.
type SLoadbalancerCertificate struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	Certificate             string    `json:"certificate"`
	PrivateKey              string    `json:"private_key"`
	PublicKeyAlgorithm      string    `json:"public_key_algorithm"`
	PublicKeyBitLen         int       `json:"public_key_bit_len"`
	SignatureAlgorithm      string    `json:"signature_algorithm"`
	Fingerprint             string    `json:"fingerprint"`
	NotBefore               time.Time `json:"not_before"`
	NotAfter                time.Time `json:"not_after"`
	CommonName              string    `json:"common_name"`
	SubjectAlternativeNames string    `json:"subject_alternative_names"`
}

// SLoadbalancerCluster is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerCluster.
type SLoadbalancerCluster struct {
	apis.SStandaloneResourceBase
	SZoneResourceBase
	WireId string `json:"wire_id"`
}

// SLoadbalancerHTTPListener is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerHTTPListener.
type SLoadbalancerHTTPListener struct {
	StickySession              string `json:"sticky_session"`
	StickySessionType          string `json:"sticky_session_type"`
	StickySessionCookie        string `json:"sticky_session_cookie"`
	StickySessionCookieTimeout int    `json:"sticky_session_cookie_timeout"`
	XForwardedFor              bool   `json:"xforwarded_for"`
	Gzip                       bool   `json:"gzip"`
}

// SLoadbalancerHTTPRateLimiter is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerHTTPRateLimiter.
type SLoadbalancerHTTPRateLimiter struct {
	HTTPRequestRate       int `json:"http_request_rate"`
	HTTPRequestRatePerSrc int `json:"http_request_rate_per_src"`
}

// SLoadbalancerHTTPSListener is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerHTTPSListener.
type SLoadbalancerHTTPSListener struct {
	CertificateId       string `json:"certificate_id"`
	CachedCertificateId string `json:"cached_certificate_id"`
	TLSCipherPolicy     string `json:"tls_cipher_policy"`
	EnableHttp2         bool   `json:"enable_http2"`
}

// SLoadbalancerHealthCheck is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerHealthCheck.
type SLoadbalancerHealthCheck struct {
	HealthCheck         string `json:"health_check"`
	HealthCheckType     string `json:"health_check_type"`
	HealthCheckDomain   string `json:"health_check_domain"`
	HealthCheckURI      string `json:"health_check_uri"`
	HealthCheckHttpCode string `json:"health_check_http_code"`
	HealthCheckRise     int    `json:"health_check_rise"`
	HealthCheckFall     int    `json:"health_check_fall"`
	HealthCheckTimeout  int    `json:"health_check_timeout"`
	HealthCheckInterval int    `json:"health_check_interval"`
	HealthCheckReq      string `json:"health_check_req"`
	HealthCheckExp      string `json:"health_check_exp"`
}

// SLoadbalancerListener is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerListener.
type SLoadbalancerListener struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	LoadbalancerId        string `json:"loadbalancer_id"`
	ListenerType          string `json:"listener_type"`
	ListenerPort          int    `json:"listener_port"`
	BackendGroupId        string `json:"backend_group_id"`
	BackendServerPort     int    `json:"backend_server_port"`
	Scheduler             string `json:"scheduler"`
	SendProxy             string `json:"send_proxy"`
	ClientRequestTimeout  int    `json:"client_request_timeout"`
	ClientIdleTimeout     int    `json:"client_idle_timeout"`
	BackendConnectTimeout int    `json:"backend_connect_timeout"`
	BackendIdleTimeout    int    `json:"backend_idle_timeout"`
	AclStatus             string `json:"acl_status"`
	AclType               string `json:"acl_type"`
	AclId                 string `json:"acl_id"`
	CachedAclId           string `json:"cached_acl_id"`
	SLoadbalancerRateLimiter
	SLoadbalancerTCPListener
	SLoadbalancerUDPListener
	SLoadbalancerHTTPListener
	SLoadbalancerHTTPSListener
	SLoadbalancerHealthCheck
	SLoadbalancerHTTPRateLimiter
}

// SLoadbalancerListenerRule is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerListenerRule.
type SLoadbalancerListenerRule struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	IsDefault      bool   `json:"is_default"`
	ListenerId     string `json:"listener_id"`
	BackendGroupId string `json:"backend_group_id"`
	Domain         string `json:"domain"`
	Path           string `json:"path"`
	Condition      string `json:"condition"`
	SLoadbalancerHealthCheck
	SLoadbalancerHTTPRateLimiter
}

// SLoadbalancerNetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerNetwork.
type SLoadbalancerNetwork struct {
	apis.SVirtualJointResourceBase
	LoadbalancerId string `json:"loadbalancer_id"`
	NetworkId      string `json:"network_id"`
	IpAddr         string `json:"ip_addr"`
}

// SLoadbalancerRateLimiter is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerRateLimiter.
type SLoadbalancerRateLimiter struct {
	EgressMbps int `json:"egress_mbps"`
}

// SLoadbalancerTCPListener is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerTCPListener.
type SLoadbalancerTCPListener struct {
}

// SLoadbalancerUDPListener is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SLoadbalancerUDPListener.
type SLoadbalancerUDPListener struct {
}

// SManagedResourceBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SManagedResourceBase.
type SManagedResourceBase struct {
	ManagerId string `json:"manager_id"`
}

// SNatEntry is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SNatEntry.
type SNatEntry struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	NatgatewayId string `json:"natgateway_id"`
}

// SNatGateway is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SNatGateway.
type SNatGateway struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	SBillingResourceBase
	VpcId   string `json:"vpc_id"`
	NatSpec string `json:"nat_spec"`
}

// SNetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SNetwork.
type SNetwork struct {
	apis.SSharableVirtualResourceBase
	apis.SExternalizedResourceBase
	IfnameHint         string `json:"ifname_hint"`
	GuestIpStart       string `json:"guest_ip_start"`
	GuestIpEnd         string `json:"guest_ip_end"`
	GuestIpMask        byte   `json:"guest_ip_mask"`
	GuestGateway       string `json:"guest_gateway"`
	GuestDns           string `json:"guest_dns"`
	GuestDhcp          string `json:"guest_dhcp"`
	GuestDomain        string `json:"guest_domain"`
	GuestIp6Start      string `json:"guest_ip6_start"`
	GuestIp6End        string `json:"guest_ip6_end"`
	GuestIp6Mask       byte   `json:"guest_ip6_mask"`
	GuestGateway6      string `json:"guest_gateway6"`
	GuestDns6          string `json:"guest_dns6"`
	GuestDomain6       string `json:"guest_domain6"`
	VlanId             int    `json:"vlan_id"`
	WireId             string `json:"wire_id"`
	ServerType         string `json:"server_type"`
	AllocPolicy        string `json:"alloc_policy"`
	AllocTimoutSeconds int    `json:"alloc_timout_seconds"`
}

// SNetworkInterface is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SNetworkInterface.
type SNetworkInterface struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	SCloudregionResourceBase
	Mac           string `json:"mac"`
	AssociateType string `json:"associate_type"`
	AssociateId   string `json:"associate_id"`
}

// SNetworkinterfacenetwork is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SNetworkinterfacenetwork.
type SNetworkinterfacenetwork struct {
	apis.SJointResourceBase
	Primary            bool   `json:"primary"`
	IpAddr             string `json:"ip_addr"`
	NetworkinterfaceId string `json:"networkinterface_id"`
	NetworkId          string `json:"network_id"`
}

// SNetworkschedtag is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SNetworkschedtag.
type SNetworkschedtag struct {
	SSchedtagJointsBase
	NetworkId string `json:"network_id"`
}

// SReservedip is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SReservedip.
type SReservedip struct {
	apis.SResourceBase
	Id        int64     `json:"id"`
	NetworkId string    `json:"network_id"`
	IpAddr    string    `json:"ip_addr"`
	Notes     string    `json:"notes"`
	ExpiredAt time.Time `json:"expired_at"`
	Status    string    `json:"status"`
}

// SRoute is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SRoute.
type SRoute struct {
	Type        string `json:"type"`
	Cidr        string `json:"cidr"`
	NextHopType string `json:"next_hop_type"`
	NextHopId   string `json:"next_hop_id"`
}

// SRouteTable is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SRouteTable.
type SRouteTable struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	VpcId         string   `json:"vpc_id"`
	CloudregionId string   `json:"cloudregion_id"`
	Type          string   `json:"type"`
	Routes        *SRoutes `json:"routes"`
}

// SRoutes is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SRoutes.
type SRoutes []*SRoute

// SSchedpolicy is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSchedpolicy.
type SSchedpolicy struct {
	apis.SStandaloneResourceBase
	Condition  string `json:"condition"`
	SchedtagId string `json:"schedtag_id"`
	Strategy   string `json:"strategy"`
	Enabled    *bool  `json:"enabled,omitempty"`
}

// SSchedtag is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSchedtag.
type SSchedtag struct {
	apis.SStandaloneResourceBase
	apis.SScopedResourceBase
	DefaultStrategy string `json:"default_strategy"`
	ResourceType    string `json:"resource_type"`
}

// SSchedtagJointsBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSchedtagJointsBase.
type SSchedtagJointsBase struct {
	apis.SJointResourceBase
	SchedtagId string `json:"schedtag_id"`
}

// SSecurityGroup is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSecurityGroup.
type SSecurityGroup struct {
	apis.SSharableVirtualResourceBase
	IsDirty bool `json:"is_dirty"`
}

// SSecurityGroupCache is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSecurityGroupCache.
type SSecurityGroupCache struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SCloudregionResourceBase
	SManagedResourceBase
	SecgroupId string `json:"secgroup_id"`
	VpcId      string `json:"vpc_id"`
}

// SSecurityGroupRule is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSecurityGroupRule.
type SSecurityGroupRule struct {
	apis.SResourceBase
	Id          string `json:"id"`
	Priority    int64  `json:"priority"`
	Protocol    string `json:"protocol"`
	Ports       string `json:"ports"`
	Direction   string `json:"direction"`
	CIDR        string `json:"cidr"`
	Action      string `json:"action"`
	Description string `json:"description"`
	SecgroupID  string `json:"secgroup_id"`
}

// SServerSku is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SServerSku.
type SServerSku struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SCloudregionResourceBase
	SZoneResourceBase
	Enabled              bool   `json:"enabled"`
	InstanceTypeFamily   string `json:"instance_type_family"`
	InstanceTypeCategory string `json:"instance_type_category"`
	LocalCategory        string `json:"local_category"`
	PrepaidStatus        string `json:"prepaid_status"`
	PostpaidStatus       string `json:"postpaid_status"`
	CpuCoreCount         int    `json:"cpu_core_count"`
	MemorySizeMB         int    `json:"memory_size_mb"`
	OsName               string `json:"os_name"`
	SysDiskResizable     *bool  `json:"omitempty,sys_disk_resizable"`
	SysDiskType          string `json:"sys_disk_type"`
	SysDiskMinSizeGB     int    `json:"sys_disk_min_size_gb"`
	SysDiskMaxSizeGB     int    `json:"sys_disk_max_size_gb"`
	AttachedDiskType     string `json:"attached_disk_type"`
	AttachedDiskSizeGB   int    `json:"attached_disk_size_gb"`
	AttachedDiskCount    int    `json:"attached_disk_count"`
	DataDiskTypes        string `json:"data_disk_types"`
	DataDiskMaxCount     int    `json:"data_disk_max_count"`
	NicType              string `json:"nic_type"`
	NicMaxCount          int    `json:"nic_max_count"`
	GpuAttachable        *bool  `json:"gpu_attachable,omitempty"`
	GpuSpec              string `json:"gpu_spec"`
	GpuCount             int    `json:"gpu_count"`
	GpuMaxCount          int    `json:"gpu_max_count"`
	Provider             string `json:"provider"`
}

// SSnapshot is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSnapshot.
type SSnapshot struct {
	apis.SVirtualResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	DiskId        string    `json:"disk_id"`
	StorageId     string    `json:"storage_id"`
	CreatedBy     string    `json:"created_by"`
	Location      string    `json:"location"`
	Size          int       `json:"size"`
	OutOfChain    bool      `json:"out_of_chain"`
	FakeDeleted   bool      `json:"fake_deleted"`
	DiskType      string    `json:"disk_type"`
	OsType        string    `json:"os_type"`
	RefCount      int       `json:"ref_count"`
	CloudregionId string    `json:"cloudregion_id"`
	BackingDiskId string    `json:"backing_disk_id"`
	ExpiredAt     time.Time `json:"expired_at"`
}

// SSnapshotPolicy is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSnapshotPolicy.
type SSnapshotPolicy struct {
	apis.SVirtualResourceBase
	RetentionDays  int    `json:"retention_days"`
	RepeatWeekdays byte   `json:"repeat_weekdays"`
	TimePoints     uint32 `json:"time_points"`
	IsActivated    *bool  `json:"is_activated,omitempty"`
}

// SSnapshotPolicyCache is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSnapshotPolicyCache.
type SSnapshotPolicyCache struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SCloudregionResourceBase
	SManagedResourceBase
	SnapshotpolicyId string `json:"snapshotpolicy_id"`
}

// SSnapshotPolicyDisk is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSnapshotPolicyDisk.
type SSnapshotPolicyDisk struct {
	apis.SVirtualJointResourceBase
	SnapshotpolicyId string `json:"snapshotpolicy_id"`
	DiskId           string `json:"disk_id"`
	Status           string `json:"status"`
}

// SStorage is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SStorage.
type SStorage struct {
	apis.SStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	Capacity       int64                `json:"capacity"`
	Reserved       int64                `json:"reserved"`
	StorageType    string               `json:"storage_type"`
	MediumType     string               `json:"medium_type"`
	Cmtbound       float32              `json:"cmtbound"`
	StorageConf    jsonutils.JSONObject `json:"storage_conf"`
	ZoneId         string               `json:"zone_id"`
	StoragecacheId string               `json:"storagecache_id"`
	Enabled        *bool                `json:"enabled,omitempty"`
	Status         string               `json:"status"`
	IsSysDiskStore *bool                `json:"is_sys_disk_store,omitempty"`
}

// SStoragecache is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SStoragecache.
type SStoragecache struct {
	apis.SStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	Path string `json:"path"`
}

// SStoragecachedimage is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SStoragecachedimage.
type SStoragecachedimage struct {
	apis.SJointResourceBase
	StoragecacheId string    `json:"storagecache_id"`
	CachedimageId  string    `json:"cachedimage_id"`
	ExternalId     string    `json:"external_id"`
	Status         string    `json:"status"`
	Path           string    `json:"path"`
	LastDownload   time.Time `json:"last_download"`
	DownloadRefcnt int       `json:"download_refcnt"`
}

// SStorageschedtag is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SStorageschedtag.
type SStorageschedtag struct {
	SSchedtagJointsBase
	StorageId string `json:"storage_id"`
}

// SSyncableBaseResource is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SSyncableBaseResource.
type SSyncableBaseResource struct {
	SyncStatus    string    `json:"sync_status"`
	LastSync      time.Time `json:"last_sync"`
	LastSyncEndAt time.Time `json:"last_sync_end_at"`
}

// SVCenter is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SVCenter.
type SVCenter struct {
	apis.SEnabledStatusStandaloneResourceBase
	Hostname string               `json:"hostname"`
	Port     int                  `json:"port"`
	Account  string               `json:"account"`
	Password string               `json:"password"`
	LastSync time.Time            `json:"last_sync"`
	Version  string               `json:"version"`
	Sysinfo  jsonutils.JSONObject `json:"sysinfo"`
}

// SVpc is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SVpc.
type SVpc struct {
	apis.SEnabledStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	SManagedResourceBase
	IsDefault     bool   `json:"is_default"`
	CidrBlock     string `json:"cidr_block"`
	CloudregionId string `json:"cloudregion_id"`
}

// SWire is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SWire.
type SWire struct {
	apis.SStandaloneResourceBase
	apis.SExternalizedResourceBase
	Bandwidth    int    `json:"bandwidth"`
	Mtu          int    `json:"mtu"`
	ScheduleRank int    `json:"schedule_rank"`
	ZoneId       string `json:"zone_id"`
	VpcId        string `json:"vpc_id"`
}

// SZone is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SZone.
type SZone struct {
	apis.SStatusStandaloneResourceBase
	apis.SExternalizedResourceBase
	Location      string `json:"location"`
	Contacts      string `json:"contacts"`
	NameCn        string `json:"name_cn"`
	ManagerUri    string `json:"manager_uri"`
	CloudregionId string `json:"cloudregion_id"`
}

// SZoneResourceBase is an autogenerated struct via yunion.io/x/onecloud/pkg/compute/models.SZoneResourceBase.
type SZoneResourceBase struct {
	ZoneId string `json:"zone_id"`
}
