// Copyright 2019 Yunion
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: send_server.proto

package apis

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendParams struct {
	Contact              string   `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Priority             string   `protobuf:"bytes,4,opt,name=Priority,proto3" json:"Priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendParams) Reset()         { *m = SendParams{} }
func (m *SendParams) String() string { return proto.CompactTextString(m) }
func (*SendParams) ProtoMessage()    {}
func (*SendParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_63fdd68f7eb311f9, []int{0}
}

func (m *SendParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendParams.Unmarshal(m, b)
}
func (m *SendParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendParams.Marshal(b, m, deterministic)
}
func (m *SendParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendParams.Merge(m, src)
}
func (m *SendParams) XXX_Size() int {
	return xxx_messageInfo_SendParams.Size(m)
}
func (m *SendParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendParams proto.InternalMessageInfo

func (m *SendParams) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *SendParams) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendParams) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendParams) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

type UpdateConfigParams struct {
	Configs              map[string]string `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateConfigParams) Reset()         { *m = UpdateConfigParams{} }
func (m *UpdateConfigParams) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigParams) ProtoMessage()    {}
func (*UpdateConfigParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_63fdd68f7eb311f9, []int{1}
}

func (m *UpdateConfigParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigParams.Unmarshal(m, b)
}
func (m *UpdateConfigParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigParams.Marshal(b, m, deterministic)
}
func (m *UpdateConfigParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigParams.Merge(m, src)
}
func (m *UpdateConfigParams) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigParams.Size(m)
}
func (m *UpdateConfigParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigParams proto.InternalMessageInfo

func (m *UpdateConfigParams) GetConfigs() map[string]string {
	if m != nil {
		return m.Configs
	}
	return nil
}

type UseridByMobileParams struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseridByMobileParams) Reset()         { *m = UseridByMobileParams{} }
func (m *UseridByMobileParams) String() string { return proto.CompactTextString(m) }
func (*UseridByMobileParams) ProtoMessage()    {}
func (*UseridByMobileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_63fdd68f7eb311f9, []int{2}
}

func (m *UseridByMobileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseridByMobileParams.Unmarshal(m, b)
}
func (m *UseridByMobileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseridByMobileParams.Marshal(b, m, deterministic)
}
func (m *UseridByMobileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseridByMobileParams.Merge(m, src)
}
func (m *UseridByMobileParams) XXX_Size() int {
	return xxx_messageInfo_UseridByMobileParams.Size(m)
}
func (m *UseridByMobileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UseridByMobileParams.DiscardUnknown(m)
}

var xxx_messageInfo_UseridByMobileParams proto.InternalMessageInfo

func (m *UseridByMobileParams) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_63fdd68f7eb311f9, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type UseridByMobileReply struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseridByMobileReply) Reset()         { *m = UseridByMobileReply{} }
func (m *UseridByMobileReply) String() string { return proto.CompactTextString(m) }
func (*UseridByMobileReply) ProtoMessage()    {}
func (*UseridByMobileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_63fdd68f7eb311f9, []int{4}
}

func (m *UseridByMobileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseridByMobileReply.Unmarshal(m, b)
}
func (m *UseridByMobileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseridByMobileReply.Marshal(b, m, deterministic)
}
func (m *UseridByMobileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseridByMobileReply.Merge(m, src)
}
func (m *UseridByMobileReply) XXX_Size() int {
	return xxx_messageInfo_UseridByMobileReply.Size(m)
}
func (m *UseridByMobileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UseridByMobileReply.DiscardUnknown(m)
}

var xxx_messageInfo_UseridByMobileReply proto.InternalMessageInfo

func (m *UseridByMobileReply) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func init() {
	proto.RegisterType((*SendParams)(nil), "apis.SendParams")
	proto.RegisterType((*UpdateConfigParams)(nil), "apis.UpdateConfigParams")
	proto.RegisterMapType((map[string]string)(nil), "apis.UpdateConfigParams.ConfigsEntry")
	proto.RegisterType((*UseridByMobileParams)(nil), "apis.UseridByMobileParams")
	proto.RegisterType((*Empty)(nil), "apis.Empty")
	proto.RegisterType((*UseridByMobileReply)(nil), "apis.UseridByMobileReply")
}

func init() { proto.RegisterFile("send_server.proto", fileDescriptor_63fdd68f7eb311f9) }

var fileDescriptor_63fdd68f7eb311f9 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xd9, 0x7e, 0xda, 0x69, 0x91, 0x1a, 0x8b, 0xc4, 0x3d, 0x95, 0x85, 0x42, 0x2f, 0xee,
	0xa1, 0x22, 0x48, 0x2f, 0xa2, 0x52, 0x3c, 0x09, 0xa5, 0xd2, 0xb3, 0xa4, 0xdd, 0xe9, 0x12, 0xec,
	0x6e, 0x96, 0x24, 0x2d, 0xec, 0x63, 0xf8, 0x2a, 0x3e, 0xa1, 0xe4, 0x63, 0xb5, 0xc5, 0x7a, 0xcb,
	0x6f, 0x66, 0xfe, 0x99, 0xf9, 0x4f, 0x02, 0x17, 0x0a, 0xf3, 0xe4, 0x5d, 0xa1, 0xdc, 0xa3, 0x8c,
	0x0b, 0x29, 0xb4, 0x20, 0x0d, 0x56, 0x70, 0x15, 0x49, 0x80, 0x37, 0xcc, 0x93, 0x39, 0x93, 0x2c,
	0x53, 0x84, 0x42, 0x7b, 0x2d, 0x72, 0xcd, 0xd6, 0x9a, 0x06, 0xc3, 0x60, 0xdc, 0x59, 0x54, 0x48,
	0x06, 0xd0, 0xd4, 0xa2, 0xe0, 0x6b, 0x5a, 0xb3, 0x71, 0x07, 0xa6, 0x3e, 0x43, 0xa5, 0x58, 0x8a,
	0xb4, 0xee, 0xea, 0x3d, 0x92, 0x10, 0xce, 0xe6, 0x92, 0x0b, 0xc9, 0x75, 0x49, 0x1b, 0x36, 0xf5,
	0xc3, 0xd1, 0x67, 0x00, 0x64, 0x59, 0x24, 0x4c, 0xe3, 0xb3, 0xc8, 0x37, 0x3c, 0xf5, 0xcd, 0x1f,
	0x6c, 0xf3, 0x0d, 0x4f, 0x15, 0x0d, 0x86, 0xf5, 0x71, 0x77, 0x32, 0x8a, 0xcd, 0x88, 0xf1, 0xdf,
	0xd2, 0xd8, 0x81, 0x9a, 0xe5, 0x5a, 0x96, 0x8b, 0x4a, 0x15, 0x4e, 0xa1, 0x77, 0x98, 0x20, 0x7d,
	0xa8, 0x7f, 0x60, 0xe9, 0x9d, 0x98, 0xa3, 0x71, 0xb1, 0x67, 0xdb, 0x1d, 0x56, 0x2e, 0x2c, 0x4c,
	0x6b, 0xf7, 0x41, 0x14, 0xc3, 0x60, 0xa9, 0x50, 0xf2, 0xe4, 0xa9, 0x7c, 0x15, 0x2b, 0xbe, 0x45,
	0x3f, 0xd4, 0x15, 0xb4, 0x32, 0xcb, 0xfe, 0x1a, 0x4f, 0x51, 0x1b, 0x9a, 0xb3, 0xac, 0xd0, 0x65,
	0x74, 0x03, 0x97, 0xc7, 0xc2, 0x05, 0x16, 0xdb, 0xd2, 0xe8, 0x76, 0x36, 0x5c, 0xe9, 0x1c, 0x4d,
	0xbe, 0x02, 0xe8, 0x98, 0x85, 0x3f, 0xa6, 0x98, 0x6b, 0x32, 0x82, 0x86, 0x01, 0xd2, 0x77, 0x4e,
	0x7f, 0x5f, 0x22, 0xec, 0xba, 0x88, 0xed, 0x41, 0xee, 0xa0, 0x77, 0xb8, 0x04, 0x42, 0xff, 0x5b,
	0xcc, 0xb1, 0xec, 0x05, 0xce, 0x8f, 0x47, 0x23, 0xa1, 0x17, 0x9e, 0x70, 0x1a, 0x5e, 0x9f, 0xca,
	0x59, 0x33, 0xab, 0x96, 0xfd, 0x31, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x49, 0x12, 0x30,
	0x1e, 0x46, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendAgentClient is the client API for SendAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendAgentClient interface {
	Send(ctx context.Context, in *SendParams, opts ...grpc.CallOption) (*Empty, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigParams, opts ...grpc.CallOption) (*Empty, error)
	UseridByMobile(ctx context.Context, in *UseridByMobileParams, opts ...grpc.CallOption) (*UseridByMobileReply, error)
}

type sendAgentClient struct {
	cc *grpc.ClientConn
}

func NewSendAgentClient(cc *grpc.ClientConn) SendAgentClient {
	return &sendAgentClient{cc}
}

func (c *sendAgentClient) Send(ctx context.Context, in *SendParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.SendAgent/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendAgentClient) UpdateConfig(ctx context.Context, in *UpdateConfigParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/apis.SendAgent/UpdateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendAgentClient) UseridByMobile(ctx context.Context, in *UseridByMobileParams, opts ...grpc.CallOption) (*UseridByMobileReply, error) {
	out := new(UseridByMobileReply)
	err := c.cc.Invoke(ctx, "/apis.SendAgent/UseridByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendAgentServer is the server API for SendAgent service.
type SendAgentServer interface {
	Send(context.Context, *SendParams) (*Empty, error)
	UpdateConfig(context.Context, *UpdateConfigParams) (*Empty, error)
	UseridByMobile(context.Context, *UseridByMobileParams) (*UseridByMobileReply, error)
}

// UnimplementedSendAgentServer can be embedded to have forward compatible implementations.
type UnimplementedSendAgentServer struct {
}

func (*UnimplementedSendAgentServer) Send(ctx context.Context, req *SendParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedSendAgentServer) UpdateConfig(ctx context.Context, req *UpdateConfigParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (*UnimplementedSendAgentServer) UseridByMobile(ctx context.Context, req *UseridByMobileParams) (*UseridByMobileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseridByMobile not implemented")
}

func RegisterSendAgentServer(s *grpc.Server, srv SendAgentServer) {
	s.RegisterService(&_SendAgent_serviceDesc, srv)
}

func _SendAgent_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAgentServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SendAgent/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAgentServer).Send(ctx, req.(*SendParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendAgent_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAgentServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SendAgent/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAgentServer).UpdateConfig(ctx, req.(*UpdateConfigParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendAgent_UseridByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseridByMobileParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAgentServer).UseridByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SendAgent/UseridByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAgentServer).UseridByMobile(ctx, req.(*UseridByMobileParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.SendAgent",
	HandlerType: (*SendAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SendAgent_Send_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _SendAgent_UpdateConfig_Handler,
		},
		{
			MethodName: "UseridByMobile",
			Handler:    _SendAgent_UseridByMobile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "send_server.proto",
}
