swagger: "2.0"
info:
  title: "OneCloud API"
  version: "1.0"
  termsOfService: ""
  contact:
    email: zhouyousong@yunion.cn
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "10.168.222.136:8889"
basePath: "/"

schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  keystone:
    type: apiKey
    in: header
    name: X-Auth-Token
security:
  - keystone: []

paths:
  /v2.0/tokens:
    $ref: "./identity/auth_v2.yaml"
  /v2.0/tokens/{token}:
    $ref: "./identity/verify_v2.yaml"
  /v3/auth/tokens:
    $ref: "./identity/auth_v3.yaml"

  /storages:
    $ref: "./storage/storages.yaml"
  /storages/{storageId}:
    $ref: "./storage/storage.yaml"
  /storages/{storageId}/enable:
    $ref: "./storage/storage.yaml#/enable"
  /storages/{storageId}/disable:
    $ref: "./storage/storage.yaml#/disable"
  /storages/{storageId}/online:
    $ref: "./storage/storage.yaml#/online"
  /storages/{storageId}/offline:
    $ref: "./storage/storage.yaml#/offline"

  /hoststorages:
    $ref: "./hoststorage/hoststorage.yaml"
  /hosts/{hostId}/storages/{storageId}:
    $ref: "./hoststorage/hoststorages.yaml"

  /networks:
    $ref: "./network/networks.yaml"
  /networks/{networkId}:
    $ref: "./network/network.yaml"
  /networks/{networkId}/private:
    $ref: "./network/network.yaml#/private"
  /networks/{networkId}/public:
    $ref: "./network/network.yaml#/public"
  /networks/{networkId}/split:
    $ref: "./network/network.yaml#/split"
  /networks/{networkId}/merge:
    $ref: "./network/network.yaml#/merge"
  /networks/{networkId}/reserve-ip:
    $ref: "./network/network.yaml#/reserve-ip"
  /networks/{networkId}/release-reserve-ip:
    $ref: "./network/network.yaml#/release-reserve-ip"
  /networks/{networkId}/networkinterface:
    $ref: "./network/networkinterface.yaml"

  /servers:
    $ref: "./instance/instances.yaml"
  /servers/{instanceId}/add-secgroup:
    $ref: "./instance/add-secgroup.yaml"
  /servers/{instanceId}/assign-secgroup:
    $ref: "./instance/assign-secgroup.yaml"
  /servers/{instanceId}/associate-eip:
    $ref: "./instance/associate-eip.yaml"
  /servers/{instanceId}/attachdisk:
    $ref: "./instance/attachdisk.yaml"
  /servers/{instanceId}/attach-isolate-device:
    $ref: "./instance/attach-isolate-device.yaml"
  /servers/{instanceId}/attachnetwork:
    $ref: "./instance/attachnetwork.yaml"
  /servers/{instanceId}/cancel-delete:
    $ref: "./instance/cancel-delete.yaml"
  /servers/{instanceId}/change-bandwidth:
    $ref: "./instance/change-bandwidth.yaml"
  /servers/{instanceId}/change-config:
    $ref: "./instance/change-bandwidth.yaml"
  /servers/{instanceId}/change-ip-addr:
    $ref: "./instance/change-ip-addr.yaml"
  /servers/{instanceId}/create-backup:
    $ref: "./instance/create-backup.yaml"
  /servers/{instanceId}/createdisk:
    $ref: "./instance/createdisk.yaml"
  /servers/{instanceId}/create-eip:
    $ref: "./instance/create-eip.yaml"
  /servers/{instanceId}/del-extra-option:
    $ref: "./instance/del-extra-option.yaml"
  /servers/{instanceId}/delete-backup:
    $ref: "./instance/delete-backup.yaml"
  /servers/{instanceId}/deploy:
    $ref: "./instance/deploy.yaml"
  /servers/{instanceId}/detachdisk:
    $ref: "./instance/detachdisk.yaml"
  /servers/{instanceId}/detach-isolate-device:
    $ref: "./instance/detach-isolate-device.yaml"
  /servers/{instanceId}/detachnetwork:
    $ref: "./instance/detachnetwork.yaml"
  /servers/{instanceId}/dissociate-eip:
    $ref: "./instance/dissociate-eip.yaml"
  /servers/{instanceId}/ejectiso:
    $ref: "./instance/ejectiso.yaml"
  /servers/{instanceId}/insertiso:
    $ref: "./instance/insertiso.yaml"
  /servers/{instanceId}/live-migrate:
    $ref: "./instance/live-migrate.yaml"
  /servers/{instanceId}/migrate:
    $ref: "./instance/migrate.yaml"
  /servers/{instanceId}/monitor:
    $ref: "./instance/monitor.yaml"
  /servers/{instanceId}/purge:
    $ref: "./instance/purge.yaml"
  /servers/{instanceId}/rebuild-root:
    $ref: "./instance/rebuild-root.yaml"
  /servers/{instanceId}/renew:
    $ref: "./instance/renew.yaml"
  /servers/{instanceId}/reset:
    $ref: "./instance/reset.yaml"
  /servers/{instanceId}/restart:
    $ref: "./instance/restart.yaml"
  /servers/{instanceId}/revoke-secgroup:
    $ref: "./instance/revoke-secgroup.yaml"
  /servers/{instanceId}/save-image:
    $ref: "./instance/save-image.yaml"
  /servers/{instanceId}/save-guest-image:
    $ref: "./instance/save-guest-image.yaml"
  /servers/{instanceId}/send-keys:
    $ref: "./instance/send-keys.yaml"
  /servers/{instanceId}/set-extra-option:
    $ref: "./instance/set-extra-option.yaml"
  /servers/{instanceId}/set-secgroup:
    $ref: "./instance/set-secgroup.yaml"
  /servers/{instanceId}:
    $ref: "./instance/instance.yaml"
  /servers/{instanceId}/start:
    $ref: "./instance/start.yaml"
  /servers/{instanceId}/status:
    $ref: "./instance/status.yaml"
  /servers/{instanceId}/stop:
    $ref: "./instance/stop.yaml"
  /servers/{instanceId}/suspend:
    $ref: "./instance/suspend.yaml"
  /servers/{instanceId}/switch-to-backup:
    $ref: "./instance/switch-to-backup.yaml"
  /servers/{instanceId}/sync:
    $ref: "./instance/sync.yaml"
  /servers/{instanceId}/syncstatus:
    $ref: "./instance/syncstatus.yaml"
  /servers/{instanceId}/user-data:
    $ref: "./instance/user-data.yaml"
  /servers/{instanceId}/vnc:
    $ref: "./instance/vnc.yaml"
  /servers/{instanceId}/io-throttle:
    $ref: "./instance/io-throttle.yaml"
  /servers/{instanceId}/bind-groups:
    $ref: "./instance/bind-groups.yaml"
  /servers/{instanceId}/unbind-groups:
    $ref: "./instance/unbind-groups.yaml"

  /images:
    $ref: "./image/images.yaml"
  /images/{imageId}:
    $ref: "./image/image.yaml"
  /images/{imageId}/mark-standard:
    $ref: "./image/image-standard.yaml"

  /guestimages:
    $ref: "./image/guest-images.yaml"
  /guestimages/{imageId}:
    $ref: "./image/guest-image.yaml"

  /instancegroups:
    $ref: "./instancegroup/instancegroups.yaml"
  /instancegroups/{instancegroupId}:
    $ref: "./instancegroup/instancegroup.yaml"
  /instancegroups/{instancegroupId}/bind-guests:
    $ref: "./instancegroup/bind-guest.yaml"
  /instancegroups/{instancegroupId}/unbind-guests:
    $ref: "./instancegroup/unbind-guest.yaml"

  /natgateways:
    $ref: "./natgateway/natgateways.yaml"
  /natgateways/{natgatewayId}:
    $ref: "./natgateway/natgateway.yaml"
  /natgateways/{natgatewayId}/dnat-resources:
    $ref: "./natgateway/dnat-resources.yaml"
  /natgateways/{natgatewayId}/snat-resources:
    $ref: "./natgateway/snat-resources.yaml"
  /natdentries:
    $ref: "./natgateway/dnatentries.yaml"
  /natdentries/{dnatentryId}:
    $ref: "./natgateway/dnatentry.yaml"
  /natsentries:
    $ref: "./natgateway/snatentries.yaml"
  /natsentries/{snatentryId}:
    $ref: "./natgateway/snatentry.yaml"

  /snapshotpolicies:
    $ref: "./snapshotpolicy/snapshotpolicies.yaml"
  /snapshotpolicies/{snapshotpolicyId}:
    $ref: "./snapshotpolicy/snapshotpolicy.yaml"
  /disks/{disk_id}/snapshotpolicies:
    $ref: "./snapshotpolicy/snapshotpolicydisk.yaml"
  /snapshotpolicies/{snapshotpolicy_id}/disks:
    $ref: "./snapshotpolicy/snapshotpolicydisk2.yaml"
  /disks/{disk_id}/snapshotpolicies/{snapshotpolicy_id}:
    $ref: "./snapshotpolicy/snapshotpolicydisk3.yaml"
  /snapshotpolicies/{snapshotpolicyId}/bind-disks:
    $ref: "./snapshotpolicy/bind-disk.yaml"
  /snapshotpolicies/{snapshotpolicyId}/unbind-disks:
    $ref: "./snapshotpolicy/unbind-disk.yaml"
  /snapshotpolicies/{snapshotpolicyId}/cache:
    $ref: "./snapshotpolicy/cache.yaml"

  /loadbalancers:
    $ref: "./loadbalancer/loadbalancers.yaml"
  /loadbalancers/{loadbalancerId}:
    $ref: "./loadbalancer/loadbalancer.yaml"

  /cached_loadbalancer_acls:
    $ref: "./loadbalancer/loadbalancercachedacls.yaml"
  /cached_loadbalancer_acls/{loadbalancercachedaclId}:
    $ref: "./loadbalancer/loadbalancercachedacl.yaml"

  /cached_loadbalancercertificates:
    $ref: "./loadbalancer/loadbalancercachedcertificates.yaml"
  /cached_loadbalancercertificates/{loadbalancercachedcertificateId}:
    $ref: "./loadbalancer/loadbalancercachedcertificate.yaml"

  /loadbalancerlisteners:
    $ref: "./loadbalancer/loadbalancerlisteners.yaml"
  /loadbalancerlisteners/{loadbalancerlistenerId}:
    $ref: "./loadbalancer/loadbalancerlistener.yaml"

  /loadbalancerbackendgroups:
    $ref: "./loadbalancer/loadbalancerbackendgroups.yaml"
  /loadbalancerbackendgroups/{loadbalancerbackendgroupId}:
    $ref: "./loadbalancer/loadbalancerbackendgroup.yaml"

  /loadbalancerbackends:
    $ref: "./loadbalancer/loadbalancerbackends.yaml"
  /loadbalancerbackends/{loadbalancerbackendId}:
    $ref: "./loadbalancer/loadbalancerbackend.yaml"

  /identity_providers:
    $ref: "./identity/identity_providers.yaml"
  /identity_providers/{idp_id}:
    $ref: "./identity/identity_provider.yaml"

  /domains:
    $ref: "./identity/domains.yaml"
  /domains/{domain_id}:
    $ref: "./identity/domain.yaml"

  /users:
    $ref: "./identity/users.yaml"
  /users/{user_id}:
    $ref: "./identity/user.yaml"
  /users/{user_id}/join:
    $ref: "./identity/user_join.yaml"
  /users/{user_id}/leave:
    $ref: "./identity/user_leave.yaml"

  /groups:
    $ref: "./identity/groups.yaml"
  /groups/{group_id}:
    $ref: "./identity/group.yaml"
  /groups/{group_id}/join:
    $ref: "./identity/group_join.yaml"
  /groups/{group_id}/leave:
    $ref: "./identity/group_leave.yaml"
  /groups/{group_id}/users/{user_id}:
    $ref: "./identity/groupuser.yaml"

  /projects:
    $ref: "./identity/projects.yaml"
  /projects/{project_id}:
    $ref: "./identity/project.yaml"
  /projects/{project_id}/join:
    $ref: "./identity/project_join.yaml"
  /projects/{project_id}/leave:
    $ref: "./identity/project_leave.yaml"

  /roles:
    $ref: "./identity/roles.yaml"
  /roles/{role_id}:
    $ref: "./identity/role.yaml"
  /projects/{project_id}/users/{user_id}/roles/{role_id}:
    $ref: "./identity/projectuserrole.yaml"
  /projects/{project_id}/groups/{group_id}/roles/{role_id}:
    $ref: "./identity/projectgrouprole.yaml"

  /policies:
    $ref: "./identity/policies.yaml"
  /policies/{policy_id}:
    $ref: "./identity/policy.yaml"

  /credentials:
    $ref: "./identity/credentials.yaml"

  /role_assignments:
    $ref: "./identity/roleassignments.yaml"

  /regions:
    $ref: "./identity/regions.yaml"
  /regions/{region_id}:
    $ref: "./identity/region.yaml"

  /services:
    $ref: "./identity/services.yaml"
  /services/{service_id}:
    $ref: "./identity/service.yaml"

  /endpoints:
    $ref: "./identity/endpoints.yaml"
  /endpoints/{endpoint_id}:
    $ref: "./identity/endpoint.yaml"

  /quotas:
    $ref: "./quotas/quotas.yaml"
  /quotas/{project_id}:
    $ref: "./quotas/projectquotas.yaml"
  /quotas/projects/{project_id}:
    $ref: "./quotas/projectquotas.yaml"
  /quotas/domains/{domain_id}:
    $ref: "./quotas/domainquotas.yaml"
  /quotas/projects:
    $ref: "./quotas/projectquotalist.yaml"
  /quotas/domains:
    $ref: "./quotas/quotalist.yaml"

  /serverskus:
    $ref: "./serversku/serverskus.yaml"
  /serverskus/{serverskuId}:
    $ref: "./serversku/serversku.yaml"
  /serverskus/{serverskuId}/enable:
    $ref: "./serversku/enable.yaml"
  /serverskus/{serverskuId}/disable:
    $ref: "./serversku/disable.yaml"

  /secgroupcaches:
    $ref: "./secgroupcache/secgroupcaches.yaml"
  /secgroupcaches/{cacheId}:
    $ref: "./secgroupcache/secgroupcache.yaml"

  /keypairs:
    $ref: "./keypair/keypairs.yaml"
  /keypairs/{keypairId}:
    $ref: "./keypair/keypair.yaml"

  /elasticips:
    $ref: "./elasticip/elasticips.yaml"
  /elasticips/{elasticipId}:
    $ref: "./elasticip/elasticip.yaml"
  /elasticips/{elasticipId}/associate:
    $ref: "./elasticip/associate.yaml"
  /elasticips/{elasticipId}/dissociate:
    $ref: "./elasticip/dissociate.yaml"
  /elasticips/{elasticipId}/change-bandwidth:
    $ref: "./elasticip/change-bandwidth.yaml"
  /elasticips/{elasticipId}/purge:
    $ref: "./elasticip/purge.yaml"
  /elasticips/{elasticipId}/sync:
    $ref: "./elasticip/sync.yaml"

  /networkinterfaces:
    $ref: "./networkinterface/networkinterfaces.yaml"
  /networkinterfaces/{networkinterfaceId}:
    $ref: "./networkinterface/networkinterface.yaml"
  /networkinterfaces/{networkinterfaceId}/networks:
    $ref: "./networkinterface/networks.yaml"

  /buckets:
    $ref: "./bucket/buckets.yaml"
  /buckets/{bucketName}:
    $ref: "./bucket/bucket.yaml"
  /buckets/{bucketName}/objects:
    $ref: "./bucket/listobjects.yaml"
  /buckets/{bucketName}/delete:
    $ref: "./bucket/deleteobjects.yaml"
  /buckets/{bucketName}/makedir:
    $ref: "./bucket/makedir.yaml"
  /buckets/{bucketName}/upload:
    $ref: "./bucket/uploadobject.yaml"
  /buckets/{bucketName}/temp-url:
    $ref: "./bucket/tempurl.yaml"
  /buckets/{bucketName}/acl:
    $ref: "./bucket/acl.yaml"
  /buckets/{bucketName}/limit:
    $ref: "./bucket/limit.yaml"
  /buckets/{bucketName}/access-info:
    $ref: "./bucket/access.yaml"

  /dbinstances:
    $ref: "./dbinstance/dbinstances.yaml"
  /dbinstances/{dbinstanceId}:
    $ref: "./dbinstance/dbinstance.yaml"
  /dbinstances/{dbinstanceId}/networks:
    $ref: "./dbinstance/dbinstancenetwork.yaml"
  /dbinstances/{dbinstanceId}/reboot:
    $ref: "./dbinstance/reboot.yaml"
  /dbinstances/{dbinstanceId}/sync-status:
    $ref: "./dbinstance/sync-status.yaml"
  /dbinstances/{dbinstanceId}/purge:
    $ref: "./dbinstance/purge.yaml"
  /dbinstances/{dbinstanceId}/change-config:
    $ref: "./dbinstance/change-config.yaml"
  /dbinstances/{dbinstanceId}/public-connection:
    $ref: "./dbinstance/public-connection.yaml"
  /dbinstances/{dbinstanceId}/recovery:
    $ref: "./dbinstance/recovery.yaml"



  /dbinstance_skus:
    $ref: "./dbinstance_sku/dbinstance_skus.yaml"
  /dbinstance_skus/{skuId}:
    $ref: "./dbinstance_sku/dbinstance_sku.yaml"



  /dbinstancenetworks:
    $ref: "./dbinstance/dbinstancenetworks.yaml"

  /dbinstanceparameters:
    $ref: "./dbinstance/dbinstanceparameters.yaml"
  /dbinstanceparameters/{parameterId}:
    $ref: "./dbinstance/dbinstanceparameter.yaml"

  /dbinstancedatabases:
    $ref: "./dbinstancedatabase/databases.yaml"
  /dbinstancedatabases/{databaseId}:
    $ref: "./dbinstancedatabase/database.yaml"

  /dbinstancebackups:
    $ref: "./dbinstancebackup/backups.yaml"
  /dbinstancebackups/{backupId}:
    $ref: "./dbinstancebackup/backup.yaml"

  /dbinstanceaccounts:
    $ref: "./dbinstanceaccount/accounts.yaml"
  /dbinstanceaccounts/{accountId}:
    $ref: "./dbinstanceaccount/account.yaml"
  /dbinstanceaccounts/{accountId}/reset-password:
    $ref: "./dbinstanceaccount/reset-password.yaml"
  /dbinstanceaccounts/{accountId}/grant-privilege:
    $ref: "./dbinstanceaccount/grant-privilege.yaml"
  /dbinstanceaccounts/{accountId}/revoke-privilege:
    $ref: "./dbinstanceaccount/revoke-privilege.yaml"
  /dbinstanceaccounts/{accountId}/set-privileges:
    $ref: "./dbinstanceaccount/set-privileges.yaml"


  /elasticcaches:
    $ref: "./elasticcache/elasticcaches.yaml"
  /elasticcaches/{elasticcacheId}:
    $ref: "./elasticcache/elasticcache.yaml"
  /elasticcaches/{elasticcacheId}/allocate-public-connection:
    $ref: "./elasticcache/allocate-public-connection.yaml"
  /elasticcaches/{elasticcacheId}/release-public-connection:
    $ref: "./elasticcache/release-public-connection.yaml"
  /elasticcaches/{elasticcacheId}/change-spec:
    $ref: "./elasticcache/change-spec.yaml"
  /elasticcaches/{elasticcacheId}/login-info:
    $ref: "./elasticcache/login-info.yaml"
  /elasticcaches/{elasticcacheId}/flush-instance:
    $ref: "./elasticcache/flush-instance.yaml"
  /elasticcaches/{elasticcacheId}/restart:
    $ref: "./elasticcache/restart.yaml"
  /elasticcaches/{elasticcacheId}/set-maintain-time:
    $ref: "./elasticcache/set-maintain-time.yaml"
  /elasticcaches/{elasticcacheId}/update-auth-mode:
    $ref: "./elasticcache/update-auth-mode.yaml"
  /elasticcaches/{elasticcacheId}/update-backup-policy:
    $ref: "./elasticcache/update-backup-policy.yaml"
  /elasticcaches/{elasticcacheId}/update-instance-parameters:
    $ref: "./elasticcache/update-instance-parameters.yaml"
  /elasticcacheparameters:
    $ref: "./elasticcache/elasticcacheparameters.yaml"
  /elasticcacheparameters/{parameterId}:
    $ref: "./elasticcache/elasticcacheparameter.yaml"
  /elasticcacheacls:
    $ref: "./elasticcache/elasticcacheacls.yaml"
  /elasticcacheacls/{aclId}:
    $ref: "./elasticcache/elasticcacheacl.yaml"
  /elasticcachebackups:
    $ref: "./elasticcache/elasticcachebackups.yaml"
  /elasticcachebackups/{backupId}:
    $ref: "./elasticcache/elasticcachebackup.yaml"
  /elasticcachebackups/{backupId}/restore-instance:
    $ref: "./elasticcache/restore-instance.yaml"
  /elasticcacheaccounts:
    $ref: "./elasticcache/elasticcacheaccounts.yaml"
  /elasticcacheaccounts/{accountId}:
    $ref: "./elasticcache/elasticcacheaccount.yaml"
  /elasticcacheaccounts/{accountId}/reset-password:
    $ref: "./elasticcache/reset-password.yaml"
  /elasticcacheskus:
    $ref: "./elasticcache/elasticcacheskus.yaml"

  /cloudaccounts:
    $ref: "./cloudaccount/cloudaccounts.yaml"
  /cloudaccounts/{cloudaccountId}:
    $ref: "./cloudaccount/cloudaccount.yaml"
  /cloudaccounts/{cloudaccountId}/change-project:
    $ref: "./cloudaccount/change-project.yaml"
  /cloudaccounts/{cloudaccountId}/disable:
    $ref: "./cloudaccount/disable.yaml"
  /cloudaccounts/{cloudaccountId}/enable:
    $ref: "./cloudaccount/enable.yaml"
  /cloudaccounts/{cloudaccountId}/sync:
    $ref: "./cloudaccount/sync.yaml"
  /cloudaccounts/{cloudaccountId}/update-credential:
    $ref: "./cloudaccount/update-credential.yaml"
  /cloudaccounts/{cloudaccountId}/enable-auto-sync:
    $ref: "./cloudaccount/enable-auto-sync.yaml"
  /cloudaccounts/{cloudaccountId}/disable-auto-sync:
    $ref: "./cloudaccount/disable-auto-sync.yaml"
>>>>>>> add rds operation
