name: Issue Close Check

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  issue-closed-remove-labels:
    runs-on: ubuntu-latest
    if: "!contains(github.event.issue.labels.*.name, 'stale')"
    steps:
      - name: Remove state labels when issue that hasn't stale label is closed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue edit "${{ github.event.issue.number }}" \
            --repo "${{ github.repository }}" \
            --remove-label "state/awaiting processing" \
            --remove-label "state/awaiting user feedback" || true
