name: Issue Open Check

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  issue-open-add-labels:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Add labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue edit "${{ github.event.issue.number }}" \
            --repo "${{ github.repository }}" \
            --add-label "state/awaiting processing"

      - name: Remove require reply label
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue edit "${{ github.event.issue.number }}" \
            --repo "${{ github.repository }}" \
            --remove-label "state/awaiting user feedback" \
            --remove-label "stale" || true

  notify-author-comment:
    runs-on: ubuntu-latest
    steps:
      - name: feishu notify
        uses: zexi/action-issues-notify@v1
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          issue_title: "${{ github.event.issue.user.login }} 提交了 issue: ${{ github.event.issue.title }}"
          issue_body: "${{ tojson(github.event.issue.body) }}"
          issue_link_url: "${{github.event.issue.html_url}}"
